// feb_system_v3_pipe_upload_subsystem.v

// Generated using ACDS version 18.1 625

`timescale 1 ps / 1 ps
module feb_system_v3_pipe_upload_subsystem (
		input  wire        control_clock_clk,                //            control_clock.clk
		input  wire        control_clock_reset_reset_n,      //      control_clock_reset.reset_n
		output wire        control_plane_hard_reset_reset,   // control_plane_hard_reset.reset
		output wire        data_path_hard_reset_reset,       //     data_path_hard_reset.reset
		output wire        ext_hard_reset_reset,             //           ext_hard_reset.reset
		input  wire        lvds_outclock_clk,                //            lvds_outclock.clk
		input  wire        lvds_outclock_reset_reset_n,      //      lvds_outclock_reset.reset_n
		input  wire        upload_sc_clock_clk,              //          upload_sc_clock.clk
		input  wire        upload_sc_clock_reset_reset_n,    //    upload_sc_clock_reset.reset_n
		output wire        csr_waitrequest,                  //                      csr.waitrequest
		output wire [31:0] csr_readdata,                     //                         .readdata
		output wire        csr_readdatavalid,                //                         .readdatavalid
		output wire [1:0]  csr_response,                     //                         .response
		input  wire [0:0]  csr_burstcount,                   //                         .burstcount
		input  wire [31:0] csr_writedata,                    //                         .writedata
		input  wire [4:0]  csr_address,                      //                         .address
		input  wire        csr_write,                        //                         .write
		input  wire        csr_read,                         //                         .read
		input  wire [3:0]  csr_byteenable,                   //                         .byteenable
		input  wire        csr_debugaccess,                  //                         .debugaccess
		output wire [8:0]  runctl_mgmt_host_data,            //         runctl_mgmt_host.data
		output wire        runctl_mgmt_host_valid,           //                         .valid
		input  wire        runctl_mgmt_host_ready,           //                         .ready
		input  wire [8:0]  synclink_data,                    //                 synclink.data
		input  wire [2:0]  synclink_error,                   //                         .error
		input  wire [35:0] upload_data_data,                 //              upload_data.data
		input  wire        upload_data_valid,                //                         .valid
		output wire        upload_data_ready,                //                         .ready
		input  wire        upload_data_startofpacket,        //                         .startofpacket
		input  wire        upload_data_endofpacket,          //                         .endofpacket
		output wire [35:0] upload_data0_sc_rc_data,          //       upload_data0_sc_rc.data
		output wire        upload_data0_sc_rc_valid,         //                         .valid
		input  wire        upload_data0_sc_rc_ready,         //                         .ready
		output wire        upload_data0_sc_rc_startofpacket, //                         .startofpacket
		output wire        upload_data0_sc_rc_endofpacket,   //                         .endofpacket
		output wire [1:0]  upload_data0_sc_rc_channel,       //                         .channel
		input  wire [35:0] upload_sc_data,                   //                upload_sc.data
		input  wire        upload_sc_valid,                  //                         .valid
		output wire        upload_sc_ready,                  //                         .ready
		input  wire        upload_sc_startofpacket,          //                         .startofpacket
		input  wire        upload_sc_endofpacket             //                         .endofpacket
	);

	wire         upload_cdc_fifo_out_valid;                            // upload_cdc_fifo:out_valid -> upload_pkt_mux:in2_valid
	wire  [35:0] upload_cdc_fifo_out_data;                             // upload_cdc_fifo:out_data -> upload_pkt_mux:in2_data
	wire         upload_cdc_fifo_out_ready;                            // upload_pkt_mux:in2_ready -> upload_cdc_fifo:out_ready
	wire         upload_cdc_fifo_out_startofpacket;                    // upload_cdc_fifo:out_startofpacket -> upload_pkt_mux:in2_startofpacket
	wire         upload_cdc_fifo_out_endofpacket;                      // upload_cdc_fifo:out_endofpacket -> upload_pkt_mux:in2_endofpacket
	wire         upload_sc_cdc_fifo_out_valid;                         // upload_sc_cdc_fifo:out_valid -> upload_pkt_mux:in1_valid
	wire  [35:0] upload_sc_cdc_fifo_out_data;                          // upload_sc_cdc_fifo:out_data -> upload_pkt_mux:in1_data
	wire         upload_sc_cdc_fifo_out_ready;                         // upload_pkt_mux:in1_ready -> upload_sc_cdc_fifo:out_ready
	wire         upload_sc_cdc_fifo_out_startofpacket;                 // upload_sc_cdc_fifo:out_startofpacket -> upload_pkt_mux:in1_startofpacket
	wire         upload_sc_cdc_fifo_out_endofpacket;                   // upload_sc_cdc_fifo:out_endofpacket -> upload_pkt_mux:in1_endofpacket
	wire         runctl_mgmt_host_0_upload_valid;                      // runctl_mgmt_host_0:aso_upload_valid -> upload_cdc_fifo:in_valid
	wire  [35:0] runctl_mgmt_host_0_upload_data;                       // runctl_mgmt_host_0:aso_upload_data -> upload_cdc_fifo:in_data
	wire         runctl_mgmt_host_0_upload_ready;                      // upload_cdc_fifo:in_ready -> runctl_mgmt_host_0:aso_upload_ready
	wire         runctl_mgmt_host_0_upload_startofpacket;              // runctl_mgmt_host_0:aso_upload_startofpacket -> upload_cdc_fifo:in_startofpacket
	wire         runctl_mgmt_host_0_upload_endofpacket;                // runctl_mgmt_host_0:aso_upload_endofpacket -> upload_cdc_fifo:in_endofpacket
	wire         csr_bridge_m0_waitrequest;                            // mm_interconnect_0:csr_bridge_m0_waitrequest -> csr_bridge:m0_waitrequest
	wire  [31:0] csr_bridge_m0_readdata;                               // mm_interconnect_0:csr_bridge_m0_readdata -> csr_bridge:m0_readdata
	wire         csr_bridge_m0_debugaccess;                            // csr_bridge:m0_debugaccess -> mm_interconnect_0:csr_bridge_m0_debugaccess
	wire   [4:0] csr_bridge_m0_address;                                // csr_bridge:m0_address -> mm_interconnect_0:csr_bridge_m0_address
	wire         csr_bridge_m0_read;                                   // csr_bridge:m0_read -> mm_interconnect_0:csr_bridge_m0_read
	wire   [3:0] csr_bridge_m0_byteenable;                             // csr_bridge:m0_byteenable -> mm_interconnect_0:csr_bridge_m0_byteenable
	wire         csr_bridge_m0_readdatavalid;                          // mm_interconnect_0:csr_bridge_m0_readdatavalid -> csr_bridge:m0_readdatavalid
	wire   [1:0] csr_bridge_m0_response;                               // mm_interconnect_0:csr_bridge_m0_response -> csr_bridge:m0_response
	wire  [31:0] csr_bridge_m0_writedata;                              // csr_bridge:m0_writedata -> mm_interconnect_0:csr_bridge_m0_writedata
	wire         csr_bridge_m0_write;                                  // csr_bridge:m0_write -> mm_interconnect_0:csr_bridge_m0_write
	wire   [0:0] csr_bridge_m0_burstcount;                             // csr_bridge:m0_burstcount -> mm_interconnect_0:csr_bridge_m0_burstcount
	wire  [31:0] upload_system_jtag_master_master_readdata;            // mm_interconnect_0:upload_system_jtag_master_master_readdata -> upload_system_jtag_master:master_readdata
	wire         upload_system_jtag_master_master_waitrequest;         // mm_interconnect_0:upload_system_jtag_master_master_waitrequest -> upload_system_jtag_master:master_waitrequest
	wire  [31:0] upload_system_jtag_master_master_address;             // upload_system_jtag_master:master_address -> mm_interconnect_0:upload_system_jtag_master_master_address
	wire         upload_system_jtag_master_master_read;                // upload_system_jtag_master:master_read -> mm_interconnect_0:upload_system_jtag_master_master_read
	wire   [3:0] upload_system_jtag_master_master_byteenable;          // upload_system_jtag_master:master_byteenable -> mm_interconnect_0:upload_system_jtag_master_master_byteenable
	wire         upload_system_jtag_master_master_readdatavalid;       // mm_interconnect_0:upload_system_jtag_master_master_readdatavalid -> upload_system_jtag_master:master_readdatavalid
	wire         upload_system_jtag_master_master_write;               // upload_system_jtag_master:master_write -> mm_interconnect_0:upload_system_jtag_master_master_write
	wire  [31:0] upload_system_jtag_master_master_writedata;           // upload_system_jtag_master:master_writedata -> mm_interconnect_0:upload_system_jtag_master_master_writedata
	wire  [31:0] mm_interconnect_0_runctl_mgmt_host_0_csr_readdata;    // runctl_mgmt_host_0:avs_csr_readdata -> mm_interconnect_0:runctl_mgmt_host_0_csr_readdata
	wire         mm_interconnect_0_runctl_mgmt_host_0_csr_waitrequest; // runctl_mgmt_host_0:avs_csr_waitrequest -> mm_interconnect_0:runctl_mgmt_host_0_csr_waitrequest
	wire   [4:0] mm_interconnect_0_runctl_mgmt_host_0_csr_address;     // mm_interconnect_0:runctl_mgmt_host_0_csr_address -> runctl_mgmt_host_0:avs_csr_address
	wire         mm_interconnect_0_runctl_mgmt_host_0_csr_read;        // mm_interconnect_0:runctl_mgmt_host_0_csr_read -> runctl_mgmt_host_0:avs_csr_read
	wire         mm_interconnect_0_runctl_mgmt_host_0_csr_write;       // mm_interconnect_0:runctl_mgmt_host_0_csr_write -> runctl_mgmt_host_0:avs_csr_write
	wire  [31:0] mm_interconnect_0_runctl_mgmt_host_0_csr_writedata;   // mm_interconnect_0:runctl_mgmt_host_0_csr_writedata -> runctl_mgmt_host_0:avs_csr_writedata
	wire         rst_controller_reset_out_reset;                       // rst_controller:reset_out -> [csr_bridge:reset, mm_interconnect_0:csr_bridge_reset_reset_bridge_in_reset_reset, mm_interconnect_0:runctl_mgmt_host_0_mm_reset_reset_bridge_in_reset_reset, mm_interconnect_0:upload_system_jtag_master_clk_reset_reset_bridge_in_reset_reset, upload_cdc_fifo:out_reset_n, upload_pkt_mux:reset_n, upload_sc_cdc_fifo:out_reset_n]
	wire         rst_controller_001_reset_out_reset;                   // rst_controller_001:reset_out -> upload_cdc_fifo:in_reset_n
	wire         rst_controller_002_reset_out_reset;                   // rst_controller_002:reset_out -> upload_sc_cdc_fifo:in_reset_n

	altera_avalon_mm_bridge #(
		.DATA_WIDTH        (32),
		.SYMBOL_WIDTH      (8),
		.HDL_ADDR_WIDTH    (5),
		.BURSTCOUNT_WIDTH  (1),
		.PIPELINE_COMMAND  (0),
		.PIPELINE_RESPONSE (0)
	) csr_bridge (
		.clk              (control_clock_clk),              //   clk.clk
		.reset            (rst_controller_reset_out_reset), // reset.reset
		.s0_waitrequest   (csr_waitrequest),                //    s0.waitrequest
		.s0_readdata      (csr_readdata),                   //      .readdata
		.s0_readdatavalid (csr_readdatavalid),              //      .readdatavalid
		.s0_response      (csr_response),                   //      .response
		.s0_burstcount    (csr_burstcount),                 //      .burstcount
		.s0_writedata     (csr_writedata),                  //      .writedata
		.s0_address       (csr_address),                    //      .address
		.s0_write         (csr_write),                      //      .write
		.s0_read          (csr_read),                       //      .read
		.s0_byteenable    (csr_byteenable),                 //      .byteenable
		.s0_debugaccess   (csr_debugaccess),                //      .debugaccess
		.m0_waitrequest   (csr_bridge_m0_waitrequest),      //    m0.waitrequest
		.m0_readdata      (csr_bridge_m0_readdata),         //      .readdata
		.m0_readdatavalid (csr_bridge_m0_readdatavalid),    //      .readdatavalid
		.m0_response      (csr_bridge_m0_response),         //      .response
		.m0_burstcount    (csr_bridge_m0_burstcount),       //      .burstcount
		.m0_writedata     (csr_bridge_m0_writedata),        //      .writedata
		.m0_address       (csr_bridge_m0_address),          //      .address
		.m0_write         (csr_bridge_m0_write),            //      .write
		.m0_read          (csr_bridge_m0_read),             //      .read
		.m0_byteenable    (csr_bridge_m0_byteenable),       //      .byteenable
		.m0_debugaccess   (csr_bridge_m0_debugaccess)       //      .debugaccess
	);

	runctl_mgmt_host #(
		.RUN_START_ACK_SYMBOL        (8'b11000110),
		.RUN_END_ACK_SYMBOL          (8'b10111101),
		.DEBUG                       (1),
		.EXT_HARD_RESET_PULSE_CYCLES (16384),
		.IP_UID                      (32'b01010010010000110100110101001000),
		.VERSION_MAJOR               (26),
		.VERSION_MINOR               (2),
		.VERSION_PATCH               (6),
		.BUILD                       (425),
		.VERSION_DATE                (32'b00000001001101010010011001001001),
		.VERSION_GIT                 (32'b00000011011110011110000100111010),
		.INSTANCE_ID                 (32'b00000000000000000000000000000000)
	) runctl_mgmt_host_0 (
		.asi_synclink_data        (synclink_data),                                        //       synclink.data
		.asi_synclink_error       (synclink_error),                                       //               .error
		.aso_upload_data          (runctl_mgmt_host_0_upload_data),                       //         upload.data
		.aso_upload_valid         (runctl_mgmt_host_0_upload_valid),                      //               .valid
		.aso_upload_ready         (runctl_mgmt_host_0_upload_ready),                      //               .ready
		.aso_upload_startofpacket (runctl_mgmt_host_0_upload_startofpacket),              //               .startofpacket
		.aso_upload_endofpacket   (runctl_mgmt_host_0_upload_endofpacket),                //               .endofpacket
		.aso_runctl_data          (runctl_mgmt_host_data),                                //         runctl.data
		.aso_runctl_valid         (runctl_mgmt_host_valid),                               //               .valid
		.aso_runctl_ready         (runctl_mgmt_host_ready),                               //               .ready
		.avs_csr_address          (mm_interconnect_0_runctl_mgmt_host_0_csr_address),     //            csr.address
		.avs_csr_read             (mm_interconnect_0_runctl_mgmt_host_0_csr_read),        //               .read
		.avs_csr_readdata         (mm_interconnect_0_runctl_mgmt_host_0_csr_readdata),    //               .readdata
		.avs_csr_write            (mm_interconnect_0_runctl_mgmt_host_0_csr_write),       //               .write
		.avs_csr_writedata        (mm_interconnect_0_runctl_mgmt_host_0_csr_writedata),   //               .writedata
		.avs_csr_waitrequest      (mm_interconnect_0_runctl_mgmt_host_0_csr_waitrequest), //               .waitrequest
		.mm_clk                   (control_clock_clk),                                    //       mm_clock.clk
		.mm_reset                 (~control_clock_reset_reset_n),                         //       mm_reset.reset
		.lvdspll_clk              (lvds_outclock_clk),                                    //  lvdspll_clock.clk
		.lvdspll_reset            (~lvds_outclock_reset_reset_n),                         //  lvdspll_reset.reset
		.dp_hard_reset            (data_path_hard_reset_reset),                           //  dp_hard_reset.reset
		.ct_hard_reset            (control_plane_hard_reset_reset),                       //  ct_hard_reset.reset
		.ext_hard_reset           (ext_hard_reset_reset)                                  // ext_hard_reset.reset
	);

	altera_avalon_dc_fifo #(
		.SYMBOLS_PER_BEAT   (1),
		.BITS_PER_SYMBOL    (36),
		.FIFO_DEPTH         (16),
		.CHANNEL_WIDTH      (0),
		.ERROR_WIDTH        (0),
		.USE_PACKETS        (1),
		.USE_IN_FILL_LEVEL  (0),
		.USE_OUT_FILL_LEVEL (0),
		.WR_SYNC_DEPTH      (2),
		.RD_SYNC_DEPTH      (2)
	) upload_cdc_fifo (
		.in_clk            (lvds_outclock_clk),                       //        in_clk.clk
		.in_reset_n        (~rst_controller_001_reset_out_reset),     //  in_clk_reset.reset_n
		.out_clk           (control_clock_clk),                       //       out_clk.clk
		.out_reset_n       (~rst_controller_reset_out_reset),         // out_clk_reset.reset_n
		.in_data           (runctl_mgmt_host_0_upload_data),          //            in.data
		.in_valid          (runctl_mgmt_host_0_upload_valid),         //              .valid
		.in_ready          (runctl_mgmt_host_0_upload_ready),         //              .ready
		.in_startofpacket  (runctl_mgmt_host_0_upload_startofpacket), //              .startofpacket
		.in_endofpacket    (runctl_mgmt_host_0_upload_endofpacket),   //              .endofpacket
		.out_data          (upload_cdc_fifo_out_data),                //           out.data
		.out_valid         (upload_cdc_fifo_out_valid),               //              .valid
		.out_ready         (upload_cdc_fifo_out_ready),               //              .ready
		.out_startofpacket (upload_cdc_fifo_out_startofpacket),       //              .startofpacket
		.out_endofpacket   (upload_cdc_fifo_out_endofpacket),         //              .endofpacket
		.in_csr_address    (1'b0),                                    //   (terminated)
		.in_csr_read       (1'b0),                                    //   (terminated)
		.in_csr_write      (1'b0),                                    //   (terminated)
		.in_csr_readdata   (),                                        //   (terminated)
		.in_csr_writedata  (32'b00000000000000000000000000000000),    //   (terminated)
		.out_csr_address   (1'b0),                                    //   (terminated)
		.out_csr_read      (1'b0),                                    //   (terminated)
		.out_csr_write     (1'b0),                                    //   (terminated)
		.out_csr_readdata  (),                                        //   (terminated)
		.out_csr_writedata (32'b00000000000000000000000000000000),    //   (terminated)
		.in_empty          (1'b0),                                    //   (terminated)
		.out_empty         (),                                        //   (terminated)
		.in_error          (1'b0),                                    //   (terminated)
		.out_error         (),                                        //   (terminated)
		.in_channel        (1'b0),                                    //   (terminated)
		.out_channel       (),                                        //   (terminated)
		.space_avail_data  ()                                         //   (terminated)
	);

	altera_avalon_dc_fifo #(
		.SYMBOLS_PER_BEAT   (1),
		.BITS_PER_SYMBOL    (36),
		.FIFO_DEPTH         (256),
		.CHANNEL_WIDTH      (0),
		.ERROR_WIDTH        (0),
		.USE_PACKETS        (1),
		.USE_IN_FILL_LEVEL  (0),
		.USE_OUT_FILL_LEVEL (0),
		.WR_SYNC_DEPTH      (2),
		.RD_SYNC_DEPTH      (2)
	) upload_sc_cdc_fifo (
		.in_clk            (upload_sc_clock_clk),                  //        in_clk.clk
		.in_reset_n        (~rst_controller_002_reset_out_reset),  //  in_clk_reset.reset_n
		.out_clk           (control_clock_clk),                    //       out_clk.clk
		.out_reset_n       (~rst_controller_reset_out_reset),      // out_clk_reset.reset_n
		.in_data           (upload_sc_data),                       //            in.data
		.in_valid          (upload_sc_valid),                      //              .valid
		.in_ready          (upload_sc_ready),                      //              .ready
		.in_startofpacket  (upload_sc_startofpacket),              //              .startofpacket
		.in_endofpacket    (upload_sc_endofpacket),                //              .endofpacket
		.out_data          (upload_sc_cdc_fifo_out_data),          //           out.data
		.out_valid         (upload_sc_cdc_fifo_out_valid),         //              .valid
		.out_ready         (upload_sc_cdc_fifo_out_ready),         //              .ready
		.out_startofpacket (upload_sc_cdc_fifo_out_startofpacket), //              .startofpacket
		.out_endofpacket   (upload_sc_cdc_fifo_out_endofpacket),   //              .endofpacket
		.in_csr_address    (1'b0),                                 //   (terminated)
		.in_csr_read       (1'b0),                                 //   (terminated)
		.in_csr_write      (1'b0),                                 //   (terminated)
		.in_csr_readdata   (),                                     //   (terminated)
		.in_csr_writedata  (32'b00000000000000000000000000000000), //   (terminated)
		.out_csr_address   (1'b0),                                 //   (terminated)
		.out_csr_read      (1'b0),                                 //   (terminated)
		.out_csr_write     (1'b0),                                 //   (terminated)
		.out_csr_readdata  (),                                     //   (terminated)
		.out_csr_writedata (32'b00000000000000000000000000000000), //   (terminated)
		.in_empty          (1'b0),                                 //   (terminated)
		.out_empty         (),                                     //   (terminated)
		.in_error          (1'b0),                                 //   (terminated)
		.out_error         (),                                     //   (terminated)
		.in_channel        (1'b0),                                 //   (terminated)
		.out_channel       (),                                     //   (terminated)
		.space_avail_data  ()                                      //   (terminated)
	);

	feb_system_v3_pipe_upload_subsystem_upload_pkt_mux upload_pkt_mux (
		.clk               (control_clock_clk),                    //   clk.clk
		.reset_n           (~rst_controller_reset_out_reset),      // reset.reset_n
		.out_data          (upload_data0_sc_rc_data),              //   out.data
		.out_valid         (upload_data0_sc_rc_valid),             //      .valid
		.out_ready         (upload_data0_sc_rc_ready),             //      .ready
		.out_startofpacket (upload_data0_sc_rc_startofpacket),     //      .startofpacket
		.out_endofpacket   (upload_data0_sc_rc_endofpacket),       //      .endofpacket
		.out_channel       (upload_data0_sc_rc_channel),           //      .channel
		.in0_data          (upload_data_data),                     //   in0.data
		.in0_valid         (upload_data_valid),                    //      .valid
		.in0_ready         (upload_data_ready),                    //      .ready
		.in0_startofpacket (upload_data_startofpacket),            //      .startofpacket
		.in0_endofpacket   (upload_data_endofpacket),              //      .endofpacket
		.in1_data          (upload_sc_cdc_fifo_out_data),          //   in1.data
		.in1_valid         (upload_sc_cdc_fifo_out_valid),         //      .valid
		.in1_ready         (upload_sc_cdc_fifo_out_ready),         //      .ready
		.in1_startofpacket (upload_sc_cdc_fifo_out_startofpacket), //      .startofpacket
		.in1_endofpacket   (upload_sc_cdc_fifo_out_endofpacket),   //      .endofpacket
		.in2_data          (upload_cdc_fifo_out_data),             //   in2.data
		.in2_valid         (upload_cdc_fifo_out_valid),            //      .valid
		.in2_ready         (upload_cdc_fifo_out_ready),            //      .ready
		.in2_startofpacket (upload_cdc_fifo_out_startofpacket),    //      .startofpacket
		.in2_endofpacket   (upload_cdc_fifo_out_endofpacket)       //      .endofpacket
	);

	feb_system_v3_pipe_data_path_subsystem_master_datapath #(
		.USE_PLI     (0),
		.PLI_PORT    (50000),
		.FIFO_DEPTHS (2)
	) upload_system_jtag_master (
		.clk_clk              (control_clock_clk),                              //          clk.clk
		.clk_reset_reset      (~control_clock_reset_reset_n),                   //    clk_reset.reset
		.master_address       (upload_system_jtag_master_master_address),       //       master.address
		.master_readdata      (upload_system_jtag_master_master_readdata),      //             .readdata
		.master_read          (upload_system_jtag_master_master_read),          //             .read
		.master_write         (upload_system_jtag_master_master_write),         //             .write
		.master_writedata     (upload_system_jtag_master_master_writedata),     //             .writedata
		.master_waitrequest   (upload_system_jtag_master_master_waitrequest),   //             .waitrequest
		.master_readdatavalid (upload_system_jtag_master_master_readdatavalid), //             .readdatavalid
		.master_byteenable    (upload_system_jtag_master_master_byteenable),    //             .byteenable
		.master_reset_reset   ()                                                // master_reset.reset
	);

	feb_system_v3_pipe_upload_subsystem_mm_interconnect_0 mm_interconnect_0 (
		.control_plane_clock_156_clk_clk                                 (control_clock_clk),                                    //                               control_plane_clock_156_clk.clk
		.csr_bridge_reset_reset_bridge_in_reset_reset                    (rst_controller_reset_out_reset),                       //                    csr_bridge_reset_reset_bridge_in_reset.reset
		.runctl_mgmt_host_0_mm_reset_reset_bridge_in_reset_reset         (rst_controller_reset_out_reset),                       //         runctl_mgmt_host_0_mm_reset_reset_bridge_in_reset.reset
		.upload_system_jtag_master_clk_reset_reset_bridge_in_reset_reset (rst_controller_reset_out_reset),                       // upload_system_jtag_master_clk_reset_reset_bridge_in_reset.reset
		.csr_bridge_m0_address                                           (csr_bridge_m0_address),                                //                                             csr_bridge_m0.address
		.csr_bridge_m0_waitrequest                                       (csr_bridge_m0_waitrequest),                            //                                                          .waitrequest
		.csr_bridge_m0_burstcount                                        (csr_bridge_m0_burstcount),                             //                                                          .burstcount
		.csr_bridge_m0_byteenable                                        (csr_bridge_m0_byteenable),                             //                                                          .byteenable
		.csr_bridge_m0_read                                              (csr_bridge_m0_read),                                   //                                                          .read
		.csr_bridge_m0_readdata                                          (csr_bridge_m0_readdata),                               //                                                          .readdata
		.csr_bridge_m0_readdatavalid                                     (csr_bridge_m0_readdatavalid),                          //                                                          .readdatavalid
		.csr_bridge_m0_write                                             (csr_bridge_m0_write),                                  //                                                          .write
		.csr_bridge_m0_writedata                                         (csr_bridge_m0_writedata),                              //                                                          .writedata
		.csr_bridge_m0_debugaccess                                       (csr_bridge_m0_debugaccess),                            //                                                          .debugaccess
		.csr_bridge_m0_response                                          (csr_bridge_m0_response),                               //                                                          .response
		.upload_system_jtag_master_master_address                        (upload_system_jtag_master_master_address),             //                          upload_system_jtag_master_master.address
		.upload_system_jtag_master_master_waitrequest                    (upload_system_jtag_master_master_waitrequest),         //                                                          .waitrequest
		.upload_system_jtag_master_master_byteenable                     (upload_system_jtag_master_master_byteenable),          //                                                          .byteenable
		.upload_system_jtag_master_master_read                           (upload_system_jtag_master_master_read),                //                                                          .read
		.upload_system_jtag_master_master_readdata                       (upload_system_jtag_master_master_readdata),            //                                                          .readdata
		.upload_system_jtag_master_master_readdatavalid                  (upload_system_jtag_master_master_readdatavalid),       //                                                          .readdatavalid
		.upload_system_jtag_master_master_write                          (upload_system_jtag_master_master_write),               //                                                          .write
		.upload_system_jtag_master_master_writedata                      (upload_system_jtag_master_master_writedata),           //                                                          .writedata
		.runctl_mgmt_host_0_csr_address                                  (mm_interconnect_0_runctl_mgmt_host_0_csr_address),     //                                    runctl_mgmt_host_0_csr.address
		.runctl_mgmt_host_0_csr_write                                    (mm_interconnect_0_runctl_mgmt_host_0_csr_write),       //                                                          .write
		.runctl_mgmt_host_0_csr_read                                     (mm_interconnect_0_runctl_mgmt_host_0_csr_read),        //                                                          .read
		.runctl_mgmt_host_0_csr_readdata                                 (mm_interconnect_0_runctl_mgmt_host_0_csr_readdata),    //                                                          .readdata
		.runctl_mgmt_host_0_csr_writedata                                (mm_interconnect_0_runctl_mgmt_host_0_csr_writedata),   //                                                          .writedata
		.runctl_mgmt_host_0_csr_waitrequest                              (mm_interconnect_0_runctl_mgmt_host_0_csr_waitrequest)  //                                                          .waitrequest
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (0),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller (
		.reset_in0      (~control_clock_reset_reset_n),   // reset_in0.reset
		.clk            (control_clock_clk),              //       clk.clk
		.reset_out      (rst_controller_reset_out_reset), // reset_out.reset
		.reset_req      (),                               // (terminated)
		.reset_req_in0  (1'b0),                           // (terminated)
		.reset_in1      (1'b0),                           // (terminated)
		.reset_req_in1  (1'b0),                           // (terminated)
		.reset_in2      (1'b0),                           // (terminated)
		.reset_req_in2  (1'b0),                           // (terminated)
		.reset_in3      (1'b0),                           // (terminated)
		.reset_req_in3  (1'b0),                           // (terminated)
		.reset_in4      (1'b0),                           // (terminated)
		.reset_req_in4  (1'b0),                           // (terminated)
		.reset_in5      (1'b0),                           // (terminated)
		.reset_req_in5  (1'b0),                           // (terminated)
		.reset_in6      (1'b0),                           // (terminated)
		.reset_req_in6  (1'b0),                           // (terminated)
		.reset_in7      (1'b0),                           // (terminated)
		.reset_req_in7  (1'b0),                           // (terminated)
		.reset_in8      (1'b0),                           // (terminated)
		.reset_req_in8  (1'b0),                           // (terminated)
		.reset_in9      (1'b0),                           // (terminated)
		.reset_req_in9  (1'b0),                           // (terminated)
		.reset_in10     (1'b0),                           // (terminated)
		.reset_req_in10 (1'b0),                           // (terminated)
		.reset_in11     (1'b0),                           // (terminated)
		.reset_req_in11 (1'b0),                           // (terminated)
		.reset_in12     (1'b0),                           // (terminated)
		.reset_req_in12 (1'b0),                           // (terminated)
		.reset_in13     (1'b0),                           // (terminated)
		.reset_req_in13 (1'b0),                           // (terminated)
		.reset_in14     (1'b0),                           // (terminated)
		.reset_req_in14 (1'b0),                           // (terminated)
		.reset_in15     (1'b0),                           // (terminated)
		.reset_req_in15 (1'b0)                            // (terminated)
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (0),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller_001 (
		.reset_in0      (~lvds_outclock_reset_reset_n),       // reset_in0.reset
		.clk            (lvds_outclock_clk),                  //       clk.clk
		.reset_out      (rst_controller_001_reset_out_reset), // reset_out.reset
		.reset_req      (),                                   // (terminated)
		.reset_req_in0  (1'b0),                               // (terminated)
		.reset_in1      (1'b0),                               // (terminated)
		.reset_req_in1  (1'b0),                               // (terminated)
		.reset_in2      (1'b0),                               // (terminated)
		.reset_req_in2  (1'b0),                               // (terminated)
		.reset_in3      (1'b0),                               // (terminated)
		.reset_req_in3  (1'b0),                               // (terminated)
		.reset_in4      (1'b0),                               // (terminated)
		.reset_req_in4  (1'b0),                               // (terminated)
		.reset_in5      (1'b0),                               // (terminated)
		.reset_req_in5  (1'b0),                               // (terminated)
		.reset_in6      (1'b0),                               // (terminated)
		.reset_req_in6  (1'b0),                               // (terminated)
		.reset_in7      (1'b0),                               // (terminated)
		.reset_req_in7  (1'b0),                               // (terminated)
		.reset_in8      (1'b0),                               // (terminated)
		.reset_req_in8  (1'b0),                               // (terminated)
		.reset_in9      (1'b0),                               // (terminated)
		.reset_req_in9  (1'b0),                               // (terminated)
		.reset_in10     (1'b0),                               // (terminated)
		.reset_req_in10 (1'b0),                               // (terminated)
		.reset_in11     (1'b0),                               // (terminated)
		.reset_req_in11 (1'b0),                               // (terminated)
		.reset_in12     (1'b0),                               // (terminated)
		.reset_req_in12 (1'b0),                               // (terminated)
		.reset_in13     (1'b0),                               // (terminated)
		.reset_req_in13 (1'b0),                               // (terminated)
		.reset_in14     (1'b0),                               // (terminated)
		.reset_req_in14 (1'b0),                               // (terminated)
		.reset_in15     (1'b0),                               // (terminated)
		.reset_req_in15 (1'b0)                                // (terminated)
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (0),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller_002 (
		.reset_in0      (~upload_sc_clock_reset_reset_n),     // reset_in0.reset
		.clk            (upload_sc_clock_clk),                //       clk.clk
		.reset_out      (rst_controller_002_reset_out_reset), // reset_out.reset
		.reset_req      (),                                   // (terminated)
		.reset_req_in0  (1'b0),                               // (terminated)
		.reset_in1      (1'b0),                               // (terminated)
		.reset_req_in1  (1'b0),                               // (terminated)
		.reset_in2      (1'b0),                               // (terminated)
		.reset_req_in2  (1'b0),                               // (terminated)
		.reset_in3      (1'b0),                               // (terminated)
		.reset_req_in3  (1'b0),                               // (terminated)
		.reset_in4      (1'b0),                               // (terminated)
		.reset_req_in4  (1'b0),                               // (terminated)
		.reset_in5      (1'b0),                               // (terminated)
		.reset_req_in5  (1'b0),                               // (terminated)
		.reset_in6      (1'b0),                               // (terminated)
		.reset_req_in6  (1'b0),                               // (terminated)
		.reset_in7      (1'b0),                               // (terminated)
		.reset_req_in7  (1'b0),                               // (terminated)
		.reset_in8      (1'b0),                               // (terminated)
		.reset_req_in8  (1'b0),                               // (terminated)
		.reset_in9      (1'b0),                               // (terminated)
		.reset_req_in9  (1'b0),                               // (terminated)
		.reset_in10     (1'b0),                               // (terminated)
		.reset_req_in10 (1'b0),                               // (terminated)
		.reset_in11     (1'b0),                               // (terminated)
		.reset_req_in11 (1'b0),                               // (terminated)
		.reset_in12     (1'b0),                               // (terminated)
		.reset_req_in12 (1'b0),                               // (terminated)
		.reset_in13     (1'b0),                               // (terminated)
		.reset_req_in13 (1'b0),                               // (terminated)
		.reset_in14     (1'b0),                               // (terminated)
		.reset_req_in14 (1'b0),                               // (terminated)
		.reset_in15     (1'b0),                               // (terminated)
		.reset_req_in15 (1'b0)                                // (terminated)
	);

endmodule
