# TCL File Generated by Component Editor 18.1
# Mon Mar 30 12:00:00 CEST 2026
# DO NOT MODIFY

package require -exact qsys 16.1

set_module_property DESCRIPTION "Bundle six split one-wire sensor conduits into the shared 6-bit sense_dq bus used at the FEB top level."
set_module_property NAME onewire_sense_vector_bridge
set_module_property VERSION 26.0.330
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Mu3e Control Plane/Helpers"
set_module_property AUTHOR "Yifeng Wang"
set_module_property ICON_PATH figures/mu3e_logo.png
set_module_property DISPLAY_NAME "One-Wire Sense Vector Bridge"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false

add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL onewire_sense_vector_bridge
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file onewire_temp_sense/onewire_sense_vector_bridge.vhd VHDL PATH onewire_temp_sense/onewire_sense_vector_bridge.vhd TOP_LEVEL_FILE

add_interface reset_interface reset end
set_interface_property reset_interface associatedClock clock_interface
set_interface_property reset_interface synchronousEdges DEASSERT
set_interface_property reset_interface ENABLED true
set_interface_property reset_interface EXPORT_OF ""
set_interface_property reset_interface PORT_NAME_MAP ""
set_interface_property reset_interface CMSIS_SVD_VARIABLES ""
set_interface_property reset_interface SVD_ADDRESS_GROUP ""
add_interface_port reset_interface rsi_reset_n reset_n Input 1

add_interface clock_interface clock end
set_interface_property clock_interface clockRate 125000000
set_interface_property clock_interface ENABLED true
set_interface_property clock_interface EXPORT_OF ""
set_interface_property clock_interface PORT_NAME_MAP ""
set_interface_property clock_interface CMSIS_SVD_VARIABLES ""
set_interface_property clock_interface SVD_ADDRESS_GROUP ""
add_interface_port clock_interface csi_clk_125 clk Input 1

proc add_sensor_interface {if_name port_prefix} {
    add_interface $if_name conduit start
    set_interface_property $if_name associatedClock clock_interface
    set_interface_property $if_name associatedReset reset_interface
    set_interface_property $if_name ENABLED true
    set_interface_property $if_name EXPORT_OF ""
    set_interface_property $if_name PORT_NAME_MAP ""
    set_interface_property $if_name CMSIS_SVD_VARIABLES ""
    set_interface_property $if_name SVD_ADDRESS_GROUP ""

    add_interface_port $if_name ${port_prefix}_dq_in  in  Output 1
    add_interface_port $if_name ${port_prefix}_dq_out out Input 1
    add_interface_port $if_name ${port_prefix}_dq_oe  oe  Input 1
}

add_sensor_interface temp_sensor_mutrig0 temp_mutrig0
add_sensor_interface temp_sensor_mutrig1 temp_mutrig1
add_sensor_interface temp_sensor_sipm0   temp_sipm0
add_sensor_interface temp_sensor_sipm1   temp_sipm1
add_sensor_interface temp_sensor_dab0    temp_dab0
add_sensor_interface temp_sensor_dab1    temp_dab1

add_interface sense_dq conduit end
set_interface_property sense_dq associatedClock clock_interface
set_interface_property sense_dq associatedReset reset_interface
set_interface_property sense_dq ENABLED true
set_interface_property sense_dq EXPORT_OF ""
set_interface_property sense_dq PORT_NAME_MAP ""
set_interface_property sense_dq CMSIS_SVD_VARIABLES ""
set_interface_property sense_dq SVD_ADDRESS_GROUP ""

add_interface_port sense_dq sense_dq_in  in  Input 6
add_interface_port sense_dq sense_dq_out out Output 6
add_interface_port sense_dq sense_dq_oe  oe  Output 6
