// scifi_datapath_system_v3_pipe_hit_stack_subsystem_0.v

// Generated using ACDS version 18.1 625

`timescale 1 ps / 1 ps
module scifi_datapath_system_v3_pipe_hit_stack_subsystem_0 (
		input  wire        datapath_clock_clk,                 //              datapath_clock.clk
		input  wire        datapath_reset_reset_n,             //              datapath_reset.reset_n
		output wire [31:0] feb_frame_assembly_csr_readdata,    //      feb_frame_assembly_csr.readdata
		input  wire        feb_frame_assembly_csr_read,        //                            .read
		input  wire [3:0]  feb_frame_assembly_csr_address,     //                            .address
		output wire        feb_frame_assembly_csr_waitrequest, //                            .waitrequest
		input  wire        feb_frame_assembly_csr_write,       //                            .write
		input  wire [31:0] feb_frame_assembly_csr_writedata,   //                            .writedata
		output wire        frame_debug_burst_valid,            //           frame_debug_burst.valid
		output wire [15:0] frame_debug_burst_data,             //                            .data
		output wire        frame_debug_delay8loss_valid,       //      frame_debug_delay8loss.valid
		output wire [15:0] frame_debug_delay8loss_data,        //                            .data
		output wire        frame_debug_filllevel_valid,        //       frame_debug_filllevel.valid
		output wire [15:0] frame_debug_filllevel_data,         //                            .data
		output wire        frame_debug_loss8fill_valid,        //       frame_debug_loss8fill.valid
		output wire [15:0] frame_debug_loss8fill_data,         //                            .data
		output wire [15:0] frame_debug_ts_data,                //              frame_debug_ts.data
		output wire        frame_debug_ts_valid,               //                            .valid
		output wire        frame_ts_delta_valid,               //              frame_ts_delta.valid
		output wire [15:0] frame_ts_delta_data,                //                            .data
		output wire [35:0] hit_type3_data,                     //                   hit_type3.data
		output wire        hit_type3_valid,                    //                            .valid
		input  wire        hit_type3_ready,                    //                            .ready
		output wire        hit_type3_startofpacket,            //                            .startofpacket
		output wire        hit_type3_endofpacket,              //                            .endofpacket
		output wire        hit_type_1_ready,                   //                  hit_type_1.ready
		input  wire        hit_type_1_valid,                   //                            .valid
		input  wire        hit_type_1_startofpacket,           //                            .startofpacket
		input  wire        hit_type_1_endofpacket,             //                            .endofpacket
		input  wire [0:0]  hit_type_1_empty,                   //                            .empty
		input  wire [3:0]  hit_type_1_channel,                 //                            .channel
		input  wire [0:0]  hit_type_1_error,                   //                            .error
		input  wire [38:0] hit_type_1_data,                    //                            .data
		output wire [31:0] ring_buffer_cam_0_csr_readdata,     //       ring_buffer_cam_0_csr.readdata
		input  wire        ring_buffer_cam_0_csr_read,         //                            .read
		input  wire [4:0]  ring_buffer_cam_0_csr_address,      //                            .address
		output wire        ring_buffer_cam_0_csr_waitrequest,  //                            .waitrequest
		input  wire        ring_buffer_cam_0_csr_write,        //                            .write
		input  wire [31:0] ring_buffer_cam_0_csr_writedata,    //                            .writedata
		output wire [15:0] ring_buffer_cam_0_filllevel_data,   // ring_buffer_cam_0_filllevel.data
		output wire        ring_buffer_cam_0_filllevel_valid,  //                            .valid
		output wire [31:0] ring_buffer_cam_1_csr_readdata,     //       ring_buffer_cam_1_csr.readdata
		input  wire        ring_buffer_cam_1_csr_read,         //                            .read
		input  wire [4:0]  ring_buffer_cam_1_csr_address,      //                            .address
		output wire        ring_buffer_cam_1_csr_waitrequest,  //                            .waitrequest
		input  wire        ring_buffer_cam_1_csr_write,        //                            .write
		input  wire [31:0] ring_buffer_cam_1_csr_writedata,    //                            .writedata
		output wire [15:0] ring_buffer_cam_1_filllevel_data,   // ring_buffer_cam_1_filllevel.data
		output wire        ring_buffer_cam_1_filllevel_valid,  //                            .valid
		output wire [31:0] ring_buffer_cam_2_csr_readdata,     //       ring_buffer_cam_2_csr.readdata
		input  wire        ring_buffer_cam_2_csr_read,         //                            .read
		input  wire [4:0]  ring_buffer_cam_2_csr_address,      //                            .address
		output wire        ring_buffer_cam_2_csr_waitrequest,  //                            .waitrequest
		input  wire        ring_buffer_cam_2_csr_write,        //                            .write
		input  wire [31:0] ring_buffer_cam_2_csr_writedata,    //                            .writedata
		output wire [15:0] ring_buffer_cam_2_filllevel_data,   // ring_buffer_cam_2_filllevel.data
		output wire        ring_buffer_cam_2_filllevel_valid,  //                            .valid
		output wire [31:0] ring_buffer_cam_3_csr_readdata,     //       ring_buffer_cam_3_csr.readdata
		input  wire        ring_buffer_cam_3_csr_read,         //                            .read
		input  wire [4:0]  ring_buffer_cam_3_csr_address,      //                            .address
		output wire        ring_buffer_cam_3_csr_waitrequest,  //                            .waitrequest
		input  wire        ring_buffer_cam_3_csr_write,        //                            .write
		input  wire [31:0] ring_buffer_cam_3_csr_writedata,    //                            .writedata
		output wire [15:0] ring_buffer_cam_3_filllevel_data,   // ring_buffer_cam_3_filllevel.data
		output wire        ring_buffer_cam_3_filllevel_valid,  //                            .valid
		output wire        run_control_signal_ready,           //          run_control_signal.ready
		input  wire        run_control_signal_valid,           //                            .valid
		input  wire [8:0]  run_control_signal_data,            //                            .data
		input  wire        xcvr_clock_clk,                     //                  xcvr_clock.clk
		input  wire        xcvr_reset_reset_n                  //                  xcvr_reset.reset_n
	);

	wire         ring_buffer_cam_0_hit_type2_valid;         // ring_buffer_cam_0:aso_hit_type2_valid -> feb_frame_assembly_0:asi_hit_type2_0_valid
	wire  [35:0] ring_buffer_cam_0_hit_type2_data;          // ring_buffer_cam_0:aso_hit_type2_data -> feb_frame_assembly_0:asi_hit_type2_0_data
	wire         ring_buffer_cam_0_hit_type2_ready;         // feb_frame_assembly_0:asi_hit_type2_0_ready -> ring_buffer_cam_0:aso_hit_type2_ready
	wire   [3:0] ring_buffer_cam_0_hit_type2_channel;       // ring_buffer_cam_0:aso_hit_type2_channel -> feb_frame_assembly_0:asi_hit_type2_0_channel
	wire         ring_buffer_cam_0_hit_type2_startofpacket; // ring_buffer_cam_0:aso_hit_type2_startofpacket -> feb_frame_assembly_0:asi_hit_type2_0_startofpacket
	wire         ring_buffer_cam_0_hit_type2_endofpacket;   // ring_buffer_cam_0:aso_hit_type2_endofpacket -> feb_frame_assembly_0:asi_hit_type2_0_endofpacket
	wire         ring_buffer_cam_0_hit_type2_error;         // ring_buffer_cam_0:aso_hit_type2_error -> feb_frame_assembly_0:asi_hit_type2_0_error
	wire         ring_buffer_cam_1_hit_type2_valid;         // ring_buffer_cam_1:aso_hit_type2_valid -> feb_frame_assembly_0:asi_hit_type2_1_valid
	wire  [35:0] ring_buffer_cam_1_hit_type2_data;          // ring_buffer_cam_1:aso_hit_type2_data -> feb_frame_assembly_0:asi_hit_type2_1_data
	wire         ring_buffer_cam_1_hit_type2_ready;         // feb_frame_assembly_0:asi_hit_type2_1_ready -> ring_buffer_cam_1:aso_hit_type2_ready
	wire   [3:0] ring_buffer_cam_1_hit_type2_channel;       // ring_buffer_cam_1:aso_hit_type2_channel -> feb_frame_assembly_0:asi_hit_type2_1_channel
	wire         ring_buffer_cam_1_hit_type2_startofpacket; // ring_buffer_cam_1:aso_hit_type2_startofpacket -> feb_frame_assembly_0:asi_hit_type2_1_startofpacket
	wire         ring_buffer_cam_1_hit_type2_endofpacket;   // ring_buffer_cam_1:aso_hit_type2_endofpacket -> feb_frame_assembly_0:asi_hit_type2_1_endofpacket
	wire         ring_buffer_cam_1_hit_type2_error;         // ring_buffer_cam_1:aso_hit_type2_error -> feb_frame_assembly_0:asi_hit_type2_1_error
	wire         ring_buffer_cam_2_hit_type2_valid;         // ring_buffer_cam_2:aso_hit_type2_valid -> feb_frame_assembly_0:asi_hit_type2_2_valid
	wire  [35:0] ring_buffer_cam_2_hit_type2_data;          // ring_buffer_cam_2:aso_hit_type2_data -> feb_frame_assembly_0:asi_hit_type2_2_data
	wire         ring_buffer_cam_2_hit_type2_ready;         // feb_frame_assembly_0:asi_hit_type2_2_ready -> ring_buffer_cam_2:aso_hit_type2_ready
	wire   [3:0] ring_buffer_cam_2_hit_type2_channel;       // ring_buffer_cam_2:aso_hit_type2_channel -> feb_frame_assembly_0:asi_hit_type2_2_channel
	wire         ring_buffer_cam_2_hit_type2_startofpacket; // ring_buffer_cam_2:aso_hit_type2_startofpacket -> feb_frame_assembly_0:asi_hit_type2_2_startofpacket
	wire         ring_buffer_cam_2_hit_type2_endofpacket;   // ring_buffer_cam_2:aso_hit_type2_endofpacket -> feb_frame_assembly_0:asi_hit_type2_2_endofpacket
	wire         ring_buffer_cam_2_hit_type2_error;         // ring_buffer_cam_2:aso_hit_type2_error -> feb_frame_assembly_0:asi_hit_type2_2_error
	wire         ring_buffer_cam_3_hit_type2_valid;         // ring_buffer_cam_3:aso_hit_type2_valid -> feb_frame_assembly_0:asi_hit_type2_3_valid
	wire  [35:0] ring_buffer_cam_3_hit_type2_data;          // ring_buffer_cam_3:aso_hit_type2_data -> feb_frame_assembly_0:asi_hit_type2_3_data
	wire         ring_buffer_cam_3_hit_type2_ready;         // feb_frame_assembly_0:asi_hit_type2_3_ready -> ring_buffer_cam_3:aso_hit_type2_ready
	wire   [3:0] ring_buffer_cam_3_hit_type2_channel;       // ring_buffer_cam_3:aso_hit_type2_channel -> feb_frame_assembly_0:asi_hit_type2_3_channel
	wire         ring_buffer_cam_3_hit_type2_startofpacket; // ring_buffer_cam_3:aso_hit_type2_startofpacket -> feb_frame_assembly_0:asi_hit_type2_3_startofpacket
	wire         ring_buffer_cam_3_hit_type2_endofpacket;   // ring_buffer_cam_3:aso_hit_type2_endofpacket -> feb_frame_assembly_0:asi_hit_type2_3_endofpacket
	wire         ring_buffer_cam_3_hit_type2_error;         // ring_buffer_cam_3:aso_hit_type2_error -> feb_frame_assembly_0:asi_hit_type2_3_error
	wire         run_ctrl_cdc_d2x_out_valid;                // run_ctrl_cdc_d2x:out_valid -> feb_frame_assembly_0:asi_ctrl_xcvr_valid
	wire   [8:0] run_ctrl_cdc_d2x_out_data;                 // run_ctrl_cdc_d2x:out_data -> feb_frame_assembly_0:asi_ctrl_xcvr_data
	wire         run_ctrl_cdc_d2x_out_ready;                // feb_frame_assembly_0:asi_ctrl_xcvr_ready -> run_ctrl_cdc_d2x:out_ready
	wire         data_splitter_0_out0_valid;                // data_splitter_0:out0_valid -> ring_buffer_cam_0:asi_hit_type1_valid
	wire  [38:0] data_splitter_0_out0_data;                 // data_splitter_0:out0_data -> ring_buffer_cam_0:asi_hit_type1_data
	wire         data_splitter_0_out0_ready;                // ring_buffer_cam_0:asi_hit_type1_ready -> data_splitter_0:out0_ready
	wire   [3:0] data_splitter_0_out0_channel;              // data_splitter_0:out0_channel -> ring_buffer_cam_0:asi_hit_type1_channel
	wire         data_splitter_0_out0_startofpacket;        // data_splitter_0:out0_startofpacket -> ring_buffer_cam_0:asi_hit_type1_startofpacket
	wire         data_splitter_0_out0_endofpacket;          // data_splitter_0:out0_endofpacket -> ring_buffer_cam_0:asi_hit_type1_endofpacket
	wire   [0:0] data_splitter_0_out0_error;                // data_splitter_0:out0_error -> ring_buffer_cam_0:asi_hit_type1_error
	wire   [0:0] data_splitter_0_out0_empty;                // data_splitter_0:out0_empty -> ring_buffer_cam_0:asi_hit_type1_empty
	wire         run_control_splitter_0_out0_valid;         // run_control_splitter_0:out0_valid -> ring_buffer_cam_0:asi_ctrl_valid
	wire   [8:0] run_control_splitter_0_out0_data;          // run_control_splitter_0:out0_data -> ring_buffer_cam_0:asi_ctrl_data
	wire         run_control_splitter_0_out0_ready;         // ring_buffer_cam_0:asi_ctrl_ready -> run_control_splitter_0:out0_ready
	wire         data_splitter_0_out1_valid;                // data_splitter_0:out1_valid -> ring_buffer_cam_1:asi_hit_type1_valid
	wire  [38:0] data_splitter_0_out1_data;                 // data_splitter_0:out1_data -> ring_buffer_cam_1:asi_hit_type1_data
	wire         data_splitter_0_out1_ready;                // ring_buffer_cam_1:asi_hit_type1_ready -> data_splitter_0:out1_ready
	wire   [3:0] data_splitter_0_out1_channel;              // data_splitter_0:out1_channel -> ring_buffer_cam_1:asi_hit_type1_channel
	wire         data_splitter_0_out1_startofpacket;        // data_splitter_0:out1_startofpacket -> ring_buffer_cam_1:asi_hit_type1_startofpacket
	wire         data_splitter_0_out1_endofpacket;          // data_splitter_0:out1_endofpacket -> ring_buffer_cam_1:asi_hit_type1_endofpacket
	wire   [0:0] data_splitter_0_out1_error;                // data_splitter_0:out1_error -> ring_buffer_cam_1:asi_hit_type1_error
	wire   [0:0] data_splitter_0_out1_empty;                // data_splitter_0:out1_empty -> ring_buffer_cam_1:asi_hit_type1_empty
	wire         run_control_splitter_0_out1_valid;         // run_control_splitter_0:out1_valid -> ring_buffer_cam_1:asi_ctrl_valid
	wire   [8:0] run_control_splitter_0_out1_data;          // run_control_splitter_0:out1_data -> ring_buffer_cam_1:asi_ctrl_data
	wire         run_control_splitter_0_out1_ready;         // ring_buffer_cam_1:asi_ctrl_ready -> run_control_splitter_0:out1_ready
	wire         data_splitter_0_out2_valid;                // data_splitter_0:out2_valid -> ring_buffer_cam_2:asi_hit_type1_valid
	wire  [38:0] data_splitter_0_out2_data;                 // data_splitter_0:out2_data -> ring_buffer_cam_2:asi_hit_type1_data
	wire         data_splitter_0_out2_ready;                // ring_buffer_cam_2:asi_hit_type1_ready -> data_splitter_0:out2_ready
	wire   [3:0] data_splitter_0_out2_channel;              // data_splitter_0:out2_channel -> ring_buffer_cam_2:asi_hit_type1_channel
	wire         data_splitter_0_out2_startofpacket;        // data_splitter_0:out2_startofpacket -> ring_buffer_cam_2:asi_hit_type1_startofpacket
	wire         data_splitter_0_out2_endofpacket;          // data_splitter_0:out2_endofpacket -> ring_buffer_cam_2:asi_hit_type1_endofpacket
	wire   [0:0] data_splitter_0_out2_error;                // data_splitter_0:out2_error -> ring_buffer_cam_2:asi_hit_type1_error
	wire   [0:0] data_splitter_0_out2_empty;                // data_splitter_0:out2_empty -> ring_buffer_cam_2:asi_hit_type1_empty
	wire         run_control_splitter_0_out2_valid;         // run_control_splitter_0:out2_valid -> ring_buffer_cam_2:asi_ctrl_valid
	wire   [8:0] run_control_splitter_0_out2_data;          // run_control_splitter_0:out2_data -> ring_buffer_cam_2:asi_ctrl_data
	wire         run_control_splitter_0_out2_ready;         // ring_buffer_cam_2:asi_ctrl_ready -> run_control_splitter_0:out2_ready
	wire         data_splitter_0_out3_valid;                // data_splitter_0:out3_valid -> ring_buffer_cam_3:asi_hit_type1_valid
	wire  [38:0] data_splitter_0_out3_data;                 // data_splitter_0:out3_data -> ring_buffer_cam_3:asi_hit_type1_data
	wire         data_splitter_0_out3_ready;                // ring_buffer_cam_3:asi_hit_type1_ready -> data_splitter_0:out3_ready
	wire   [3:0] data_splitter_0_out3_channel;              // data_splitter_0:out3_channel -> ring_buffer_cam_3:asi_hit_type1_channel
	wire         data_splitter_0_out3_startofpacket;        // data_splitter_0:out3_startofpacket -> ring_buffer_cam_3:asi_hit_type1_startofpacket
	wire         data_splitter_0_out3_endofpacket;          // data_splitter_0:out3_endofpacket -> ring_buffer_cam_3:asi_hit_type1_endofpacket
	wire   [0:0] data_splitter_0_out3_error;                // data_splitter_0:out3_error -> ring_buffer_cam_3:asi_hit_type1_error
	wire   [0:0] data_splitter_0_out3_empty;                // data_splitter_0:out3_empty -> ring_buffer_cam_3:asi_hit_type1_empty
	wire         run_control_splitter_0_out3_valid;         // run_control_splitter_0:out3_valid -> ring_buffer_cam_3:asi_ctrl_valid
	wire   [8:0] run_control_splitter_0_out3_data;          // run_control_splitter_0:out3_data -> ring_buffer_cam_3:asi_ctrl_data
	wire         run_control_splitter_0_out3_ready;         // ring_buffer_cam_3:asi_ctrl_ready -> run_control_splitter_0:out3_ready
	wire         run_control_splitter_0_out4_valid;         // run_control_splitter_0:out4_valid -> feb_frame_assembly_0:asi_ctrl_datapath_valid
	wire   [8:0] run_control_splitter_0_out4_data;          // run_control_splitter_0:out4_data -> feb_frame_assembly_0:asi_ctrl_datapath_data
	wire         run_control_splitter_0_out4_ready;         // feb_frame_assembly_0:asi_ctrl_datapath_ready -> run_control_splitter_0:out4_ready
	wire         run_control_splitter_0_out5_valid;         // run_control_splitter_0:out5_valid -> run_ctrl_cdc_d2x:in_valid
	wire   [8:0] run_control_splitter_0_out5_data;          // run_control_splitter_0:out5_data -> run_ctrl_cdc_d2x:in_data
	wire         run_control_splitter_0_out5_ready;         // run_ctrl_cdc_d2x:in_ready -> run_control_splitter_0:out5_ready
	wire         rst_controller_reset_out_reset;            // rst_controller:reset_out -> [data_splitter_0:reset, ring_buffer_cam_0:i_rst, ring_buffer_cam_1:i_rst, ring_buffer_cam_2:i_rst, ring_buffer_cam_3:i_rst, run_control_splitter_0:reset, run_ctrl_cdc_d2x:in_reset_n]
	wire         rst_controller_001_reset_out_reset;        // rst_controller_001:reset_out -> run_ctrl_cdc_d2x:out_reset_n

	altera_avalon_st_splitter #(
		.NUMBER_OF_OUTPUTS (4),
		.QUALIFY_VALID_OUT (0),
		.USE_PACKETS       (1),
		.DATA_WIDTH        (39),
		.CHANNEL_WIDTH     (4),
		.ERROR_WIDTH       (1),
		.BITS_PER_SYMBOL   (39),
		.EMPTY_WIDTH       (1)
	) data_splitter_0 (
		.clk                 (datapath_clock_clk),                 //   clk.clk
		.reset               (rst_controller_reset_out_reset),     // reset.reset
		.in0_ready           (hit_type_1_ready),                   //    in.ready
		.in0_valid           (hit_type_1_valid),                   //      .valid
		.in0_startofpacket   (hit_type_1_startofpacket),           //      .startofpacket
		.in0_endofpacket     (hit_type_1_endofpacket),             //      .endofpacket
		.in0_empty           (hit_type_1_empty),                   //      .empty
		.in0_channel         (hit_type_1_channel),                 //      .channel
		.in0_error           (hit_type_1_error),                   //      .error
		.in0_data            (hit_type_1_data),                    //      .data
		.out0_ready          (data_splitter_0_out0_ready),         //  out0.ready
		.out0_valid          (data_splitter_0_out0_valid),         //      .valid
		.out0_startofpacket  (data_splitter_0_out0_startofpacket), //      .startofpacket
		.out0_endofpacket    (data_splitter_0_out0_endofpacket),   //      .endofpacket
		.out0_empty          (data_splitter_0_out0_empty),         //      .empty
		.out0_channel        (data_splitter_0_out0_channel),       //      .channel
		.out0_error          (data_splitter_0_out0_error),         //      .error
		.out0_data           (data_splitter_0_out0_data),          //      .data
		.out1_ready          (data_splitter_0_out1_ready),         //  out1.ready
		.out1_valid          (data_splitter_0_out1_valid),         //      .valid
		.out1_startofpacket  (data_splitter_0_out1_startofpacket), //      .startofpacket
		.out1_endofpacket    (data_splitter_0_out1_endofpacket),   //      .endofpacket
		.out1_empty          (data_splitter_0_out1_empty),         //      .empty
		.out1_channel        (data_splitter_0_out1_channel),       //      .channel
		.out1_error          (data_splitter_0_out1_error),         //      .error
		.out1_data           (data_splitter_0_out1_data),          //      .data
		.out2_ready          (data_splitter_0_out2_ready),         //  out2.ready
		.out2_valid          (data_splitter_0_out2_valid),         //      .valid
		.out2_startofpacket  (data_splitter_0_out2_startofpacket), //      .startofpacket
		.out2_endofpacket    (data_splitter_0_out2_endofpacket),   //      .endofpacket
		.out2_empty          (data_splitter_0_out2_empty),         //      .empty
		.out2_channel        (data_splitter_0_out2_channel),       //      .channel
		.out2_error          (data_splitter_0_out2_error),         //      .error
		.out2_data           (data_splitter_0_out2_data),          //      .data
		.out3_ready          (data_splitter_0_out3_ready),         //  out3.ready
		.out3_valid          (data_splitter_0_out3_valid),         //      .valid
		.out3_startofpacket  (data_splitter_0_out3_startofpacket), //      .startofpacket
		.out3_endofpacket    (data_splitter_0_out3_endofpacket),   //      .endofpacket
		.out3_empty          (data_splitter_0_out3_empty),         //      .empty
		.out3_channel        (data_splitter_0_out3_channel),       //      .channel
		.out3_error          (data_splitter_0_out3_error),         //      .error
		.out3_data           (data_splitter_0_out3_data),          //      .data
		.out4_ready          (1'b1),                               // (terminated)
		.out4_valid          (),                                   // (terminated)
		.out4_startofpacket  (),                                   // (terminated)
		.out4_endofpacket    (),                                   // (terminated)
		.out4_empty          (),                                   // (terminated)
		.out4_channel        (),                                   // (terminated)
		.out4_error          (),                                   // (terminated)
		.out4_data           (),                                   // (terminated)
		.out5_ready          (1'b1),                               // (terminated)
		.out5_valid          (),                                   // (terminated)
		.out5_startofpacket  (),                                   // (terminated)
		.out5_endofpacket    (),                                   // (terminated)
		.out5_empty          (),                                   // (terminated)
		.out5_channel        (),                                   // (terminated)
		.out5_error          (),                                   // (terminated)
		.out5_data           (),                                   // (terminated)
		.out6_ready          (1'b1),                               // (terminated)
		.out6_valid          (),                                   // (terminated)
		.out6_startofpacket  (),                                   // (terminated)
		.out6_endofpacket    (),                                   // (terminated)
		.out6_empty          (),                                   // (terminated)
		.out6_channel        (),                                   // (terminated)
		.out6_error          (),                                   // (terminated)
		.out6_data           (),                                   // (terminated)
		.out7_ready          (1'b1),                               // (terminated)
		.out7_valid          (),                                   // (terminated)
		.out7_startofpacket  (),                                   // (terminated)
		.out7_endofpacket    (),                                   // (terminated)
		.out7_empty          (),                                   // (terminated)
		.out7_channel        (),                                   // (terminated)
		.out7_error          (),                                   // (terminated)
		.out7_data           (),                                   // (terminated)
		.out8_ready          (1'b1),                               // (terminated)
		.out8_valid          (),                                   // (terminated)
		.out8_startofpacket  (),                                   // (terminated)
		.out8_endofpacket    (),                                   // (terminated)
		.out8_empty          (),                                   // (terminated)
		.out8_channel        (),                                   // (terminated)
		.out8_error          (),                                   // (terminated)
		.out8_data           (),                                   // (terminated)
		.out9_ready          (1'b1),                               // (terminated)
		.out9_valid          (),                                   // (terminated)
		.out9_startofpacket  (),                                   // (terminated)
		.out9_endofpacket    (),                                   // (terminated)
		.out9_empty          (),                                   // (terminated)
		.out9_channel        (),                                   // (terminated)
		.out9_error          (),                                   // (terminated)
		.out9_data           (),                                   // (terminated)
		.out10_ready         (1'b1),                               // (terminated)
		.out10_valid         (),                                   // (terminated)
		.out10_startofpacket (),                                   // (terminated)
		.out10_endofpacket   (),                                   // (terminated)
		.out10_empty         (),                                   // (terminated)
		.out10_channel       (),                                   // (terminated)
		.out10_error         (),                                   // (terminated)
		.out10_data          (),                                   // (terminated)
		.out11_ready         (1'b1),                               // (terminated)
		.out11_valid         (),                                   // (terminated)
		.out11_startofpacket (),                                   // (terminated)
		.out11_endofpacket   (),                                   // (terminated)
		.out11_empty         (),                                   // (terminated)
		.out11_channel       (),                                   // (terminated)
		.out11_error         (),                                   // (terminated)
		.out11_data          (),                                   // (terminated)
		.out12_ready         (1'b1),                               // (terminated)
		.out12_valid         (),                                   // (terminated)
		.out12_startofpacket (),                                   // (terminated)
		.out12_endofpacket   (),                                   // (terminated)
		.out12_empty         (),                                   // (terminated)
		.out12_channel       (),                                   // (terminated)
		.out12_error         (),                                   // (terminated)
		.out12_data          (),                                   // (terminated)
		.out13_ready         (1'b1),                               // (terminated)
		.out13_valid         (),                                   // (terminated)
		.out13_startofpacket (),                                   // (terminated)
		.out13_endofpacket   (),                                   // (terminated)
		.out13_empty         (),                                   // (terminated)
		.out13_channel       (),                                   // (terminated)
		.out13_error         (),                                   // (terminated)
		.out13_data          (),                                   // (terminated)
		.out14_ready         (1'b1),                               // (terminated)
		.out14_valid         (),                                   // (terminated)
		.out14_startofpacket (),                                   // (terminated)
		.out14_endofpacket   (),                                   // (terminated)
		.out14_empty         (),                                   // (terminated)
		.out14_channel       (),                                   // (terminated)
		.out14_error         (),                                   // (terminated)
		.out14_data          (),                                   // (terminated)
		.out15_ready         (1'b1),                               // (terminated)
		.out15_valid         (),                                   // (terminated)
		.out15_startofpacket (),                                   // (terminated)
		.out15_endofpacket   (),                                   // (terminated)
		.out15_empty         (),                                   // (terminated)
		.out15_channel       (),                                   // (terminated)
		.out15_error         (),                                   // (terminated)
		.out15_data          ()                                    // (terminated)
	);

	feb_frame_assembly #(
		.INTERLEAVING_FACTOR (4),
		.N_SHD               (128),
		.DEBUG               (1)
	) feb_frame_assembly_0 (
		.asi_hit_type2_0_channel       (ring_buffer_cam_0_hit_type2_channel),       //      hit_type2_0.channel
		.asi_hit_type2_0_startofpacket (ring_buffer_cam_0_hit_type2_startofpacket), //                 .startofpacket
		.asi_hit_type2_0_endofpacket   (ring_buffer_cam_0_hit_type2_endofpacket),   //                 .endofpacket
		.asi_hit_type2_0_data          (ring_buffer_cam_0_hit_type2_data),          //                 .data
		.asi_hit_type2_0_valid         (ring_buffer_cam_0_hit_type2_valid),         //                 .valid
		.asi_hit_type2_0_ready         (ring_buffer_cam_0_hit_type2_ready),         //                 .ready
		.asi_hit_type2_0_error         (ring_buffer_cam_0_hit_type2_error),         //                 .error
		.asi_hit_type2_1_channel       (ring_buffer_cam_1_hit_type2_channel),       //      hit_type2_1.channel
		.asi_hit_type2_1_startofpacket (ring_buffer_cam_1_hit_type2_startofpacket), //                 .startofpacket
		.asi_hit_type2_1_endofpacket   (ring_buffer_cam_1_hit_type2_endofpacket),   //                 .endofpacket
		.asi_hit_type2_1_data          (ring_buffer_cam_1_hit_type2_data),          //                 .data
		.asi_hit_type2_1_valid         (ring_buffer_cam_1_hit_type2_valid),         //                 .valid
		.asi_hit_type2_1_ready         (ring_buffer_cam_1_hit_type2_ready),         //                 .ready
		.asi_hit_type2_1_error         (ring_buffer_cam_1_hit_type2_error),         //                 .error
		.asi_hit_type2_2_channel       (ring_buffer_cam_2_hit_type2_channel),       //      hit_type2_2.channel
		.asi_hit_type2_2_startofpacket (ring_buffer_cam_2_hit_type2_startofpacket), //                 .startofpacket
		.asi_hit_type2_2_endofpacket   (ring_buffer_cam_2_hit_type2_endofpacket),   //                 .endofpacket
		.asi_hit_type2_2_data          (ring_buffer_cam_2_hit_type2_data),          //                 .data
		.asi_hit_type2_2_valid         (ring_buffer_cam_2_hit_type2_valid),         //                 .valid
		.asi_hit_type2_2_ready         (ring_buffer_cam_2_hit_type2_ready),         //                 .ready
		.asi_hit_type2_2_error         (ring_buffer_cam_2_hit_type2_error),         //                 .error
		.asi_hit_type2_3_channel       (ring_buffer_cam_3_hit_type2_channel),       //      hit_type2_3.channel
		.asi_hit_type2_3_startofpacket (ring_buffer_cam_3_hit_type2_startofpacket), //                 .startofpacket
		.asi_hit_type2_3_endofpacket   (ring_buffer_cam_3_hit_type2_endofpacket),   //                 .endofpacket
		.asi_hit_type2_3_data          (ring_buffer_cam_3_hit_type2_data),          //                 .data
		.asi_hit_type2_3_valid         (ring_buffer_cam_3_hit_type2_valid),         //                 .valid
		.asi_hit_type2_3_ready         (ring_buffer_cam_3_hit_type2_ready),         //                 .ready
		.asi_hit_type2_3_error         (ring_buffer_cam_3_hit_type2_error),         //                 .error
		.aso_hit_type3_data            (hit_type3_data),                            //        hit_type3.data
		.aso_hit_type3_valid           (hit_type3_valid),                           //                 .valid
		.aso_hit_type3_ready           (hit_type3_ready),                           //                 .ready
		.aso_hit_type3_startofpacket   (hit_type3_startofpacket),                   //                 .startofpacket
		.aso_hit_type3_endofpacket     (hit_type3_endofpacket),                     //                 .endofpacket
		.asi_ctrl_datapath_data        (run_control_splitter_0_out4_data),          //    ctrl_datapath.data
		.asi_ctrl_datapath_valid       (run_control_splitter_0_out4_valid),         //                 .valid
		.asi_ctrl_datapath_ready       (run_control_splitter_0_out4_ready),         //                 .ready
		.asi_ctrl_xcvr_data            (run_ctrl_cdc_d2x_out_data),                 //        ctrl_xcvr.data
		.asi_ctrl_xcvr_valid           (run_ctrl_cdc_d2x_out_valid),                //                 .valid
		.asi_ctrl_xcvr_ready           (run_ctrl_cdc_d2x_out_ready),                //                 .ready
		.avs_csr_readdata              (feb_frame_assembly_csr_readdata),           //              csr.readdata
		.avs_csr_read                  (feb_frame_assembly_csr_read),               //                 .read
		.avs_csr_address               (feb_frame_assembly_csr_address),            //                 .address
		.avs_csr_waitrequest           (feb_frame_assembly_csr_waitrequest),        //                 .waitrequest
		.avs_csr_write                 (feb_frame_assembly_csr_write),              //                 .write
		.avs_csr_writedata             (feb_frame_assembly_csr_writedata),          //                 .writedata
		.i_rst_xcvr                    (~xcvr_reset_reset_n),                       //       xcvr_reset.reset
		.i_rst_datapath                (~datapath_reset_reset_n),                   //   datapath_reset.reset
		.i_clk_datapath                (datapath_clock_clk),                        //   datapath_clock.clk
		.i_clk_xcvr                    (xcvr_clock_clk),                            //       xcvr_clock.clk
		.aso_debug_ts_data             (frame_debug_ts_data),                       //         debug_ts.data
		.aso_debug_ts_valid            (frame_debug_ts_valid),                      //                 .valid
		.aso_debug_burst_valid         (frame_debug_burst_valid),                   //      debug_burst.valid
		.aso_debug_burst_data          (frame_debug_burst_data),                    //                 .data
		.aso_ts_delta_valid            (frame_ts_delta_valid),                      //         ts_delta.valid
		.aso_ts_delta_data             (frame_ts_delta_data),                       //                 .data
		.aso_debug_filllevel_valid     (frame_debug_filllevel_valid),               //  debug_filllevel.valid
		.aso_debug_filllevel_data      (frame_debug_filllevel_data),                //                 .data
		.aso_debug_loss8fill_valid     (frame_debug_loss8fill_valid),               //  debug_loss8fill.valid
		.aso_debug_loss8fill_data      (frame_debug_loss8fill_data),                //                 .data
		.aso_debug_delay8loss_valid    (frame_debug_delay8loss_valid),              // debug_delay8loss.valid
		.aso_debug_delay8loss_data     (frame_debug_delay8loss_data)                //                 .data
	);

	ring_buffer_cam #(
		.SEARCH_KEY_WIDTH    (8),
		.RING_BUFFER_N_ENTRY (512),
		.SIDE_DATA_BITS      (31),
		.INTERLEAVING_FACTOR (4),
		.INTERLEAVING_INDEX  (0),
		.N_PARTITIONS        (4),
		.ENCODER_LEAF_WIDTH  (16),
		.ENCODER_PIPE_STAGES (4),
		.DEBUG               (1),
		.IP_UID              (1380074317),
		.VERSION_MAJOR       (26),
		.VERSION_MINOR       (2),
		.VERSION_PATCH       (6),
		.BUILD               (422),
		.VERSION_DATE        (20260422),
		.VERSION_GIT         (267039347),
		.INSTANCE_ID         (0)
	) ring_buffer_cam_0 (
		.avs_csr_readdata            (ring_buffer_cam_0_csr_readdata),            //             csr.readdata
		.avs_csr_read                (ring_buffer_cam_0_csr_read),                //                .read
		.avs_csr_address             (ring_buffer_cam_0_csr_address),             //                .address
		.avs_csr_waitrequest         (ring_buffer_cam_0_csr_waitrequest),         //                .waitrequest
		.avs_csr_write               (ring_buffer_cam_0_csr_write),               //                .write
		.avs_csr_writedata           (ring_buffer_cam_0_csr_writedata),           //                .writedata
		.asi_hit_type1_channel       (data_splitter_0_out0_channel),              //       hit_type1.channel
		.asi_hit_type1_startofpacket (data_splitter_0_out0_startofpacket),        //                .startofpacket
		.asi_hit_type1_endofpacket   (data_splitter_0_out0_endofpacket),          //                .endofpacket
		.asi_hit_type1_empty         (data_splitter_0_out0_empty),                //                .empty
		.asi_hit_type1_data          (data_splitter_0_out0_data),                 //                .data
		.asi_hit_type1_valid         (data_splitter_0_out0_valid),                //                .valid
		.asi_hit_type1_ready         (data_splitter_0_out0_ready),                //                .ready
		.asi_hit_type1_error         (data_splitter_0_out0_error),                //                .error
		.aso_hit_type2_channel       (ring_buffer_cam_0_hit_type2_channel),       //       hit_type2.channel
		.aso_hit_type2_startofpacket (ring_buffer_cam_0_hit_type2_startofpacket), //                .startofpacket
		.aso_hit_type2_endofpacket   (ring_buffer_cam_0_hit_type2_endofpacket),   //                .endofpacket
		.aso_hit_type2_data          (ring_buffer_cam_0_hit_type2_data),          //                .data
		.aso_hit_type2_valid         (ring_buffer_cam_0_hit_type2_valid),         //                .valid
		.aso_hit_type2_ready         (ring_buffer_cam_0_hit_type2_ready),         //                .ready
		.aso_hit_type2_error         (ring_buffer_cam_0_hit_type2_error),         //                .error
		.i_clk                       (datapath_clock_clk),                        // clock_interface.clk
		.i_rst                       (rst_controller_reset_out_reset),            // reset_interface.reset
		.asi_ctrl_data               (run_control_splitter_0_out0_data),          //     run_control.data
		.asi_ctrl_valid              (run_control_splitter_0_out0_valid),         //                .valid
		.asi_ctrl_ready              (run_control_splitter_0_out0_ready),         //                .ready
		.aso_filllevel_data          (ring_buffer_cam_0_filllevel_data),          //       filllevel.data
		.aso_filllevel_valid         (ring_buffer_cam_0_filllevel_valid)          //                .valid
	);

	ring_buffer_cam #(
		.SEARCH_KEY_WIDTH    (8),
		.RING_BUFFER_N_ENTRY (512),
		.SIDE_DATA_BITS      (31),
		.INTERLEAVING_FACTOR (4),
		.INTERLEAVING_INDEX  (1),
		.N_PARTITIONS        (4),
		.ENCODER_LEAF_WIDTH  (16),
		.ENCODER_PIPE_STAGES (4),
		.DEBUG               (1),
		.IP_UID              (1380074317),
		.VERSION_MAJOR       (26),
		.VERSION_MINOR       (2),
		.VERSION_PATCH       (6),
		.BUILD               (422),
		.VERSION_DATE        (20260422),
		.VERSION_GIT         (267039347),
		.INSTANCE_ID         (0)
	) ring_buffer_cam_1 (
		.avs_csr_readdata            (ring_buffer_cam_1_csr_readdata),            //             csr.readdata
		.avs_csr_read                (ring_buffer_cam_1_csr_read),                //                .read
		.avs_csr_address             (ring_buffer_cam_1_csr_address),             //                .address
		.avs_csr_waitrequest         (ring_buffer_cam_1_csr_waitrequest),         //                .waitrequest
		.avs_csr_write               (ring_buffer_cam_1_csr_write),               //                .write
		.avs_csr_writedata           (ring_buffer_cam_1_csr_writedata),           //                .writedata
		.asi_hit_type1_channel       (data_splitter_0_out1_channel),              //       hit_type1.channel
		.asi_hit_type1_startofpacket (data_splitter_0_out1_startofpacket),        //                .startofpacket
		.asi_hit_type1_endofpacket   (data_splitter_0_out1_endofpacket),          //                .endofpacket
		.asi_hit_type1_empty         (data_splitter_0_out1_empty),                //                .empty
		.asi_hit_type1_data          (data_splitter_0_out1_data),                 //                .data
		.asi_hit_type1_valid         (data_splitter_0_out1_valid),                //                .valid
		.asi_hit_type1_ready         (data_splitter_0_out1_ready),                //                .ready
		.asi_hit_type1_error         (data_splitter_0_out1_error),                //                .error
		.aso_hit_type2_channel       (ring_buffer_cam_1_hit_type2_channel),       //       hit_type2.channel
		.aso_hit_type2_startofpacket (ring_buffer_cam_1_hit_type2_startofpacket), //                .startofpacket
		.aso_hit_type2_endofpacket   (ring_buffer_cam_1_hit_type2_endofpacket),   //                .endofpacket
		.aso_hit_type2_data          (ring_buffer_cam_1_hit_type2_data),          //                .data
		.aso_hit_type2_valid         (ring_buffer_cam_1_hit_type2_valid),         //                .valid
		.aso_hit_type2_ready         (ring_buffer_cam_1_hit_type2_ready),         //                .ready
		.aso_hit_type2_error         (ring_buffer_cam_1_hit_type2_error),         //                .error
		.i_clk                       (datapath_clock_clk),                        // clock_interface.clk
		.i_rst                       (rst_controller_reset_out_reset),            // reset_interface.reset
		.asi_ctrl_data               (run_control_splitter_0_out1_data),          //     run_control.data
		.asi_ctrl_valid              (run_control_splitter_0_out1_valid),         //                .valid
		.asi_ctrl_ready              (run_control_splitter_0_out1_ready),         //                .ready
		.aso_filllevel_data          (ring_buffer_cam_1_filllevel_data),          //       filllevel.data
		.aso_filllevel_valid         (ring_buffer_cam_1_filllevel_valid)          //                .valid
	);

	ring_buffer_cam #(
		.SEARCH_KEY_WIDTH    (8),
		.RING_BUFFER_N_ENTRY (512),
		.SIDE_DATA_BITS      (31),
		.INTERLEAVING_FACTOR (4),
		.INTERLEAVING_INDEX  (2),
		.N_PARTITIONS        (4),
		.ENCODER_LEAF_WIDTH  (16),
		.ENCODER_PIPE_STAGES (4),
		.DEBUG               (1),
		.IP_UID              (1380074317),
		.VERSION_MAJOR       (26),
		.VERSION_MINOR       (2),
		.VERSION_PATCH       (6),
		.BUILD               (422),
		.VERSION_DATE        (20260422),
		.VERSION_GIT         (267039347),
		.INSTANCE_ID         (0)
	) ring_buffer_cam_2 (
		.avs_csr_readdata            (ring_buffer_cam_2_csr_readdata),            //             csr.readdata
		.avs_csr_read                (ring_buffer_cam_2_csr_read),                //                .read
		.avs_csr_address             (ring_buffer_cam_2_csr_address),             //                .address
		.avs_csr_waitrequest         (ring_buffer_cam_2_csr_waitrequest),         //                .waitrequest
		.avs_csr_write               (ring_buffer_cam_2_csr_write),               //                .write
		.avs_csr_writedata           (ring_buffer_cam_2_csr_writedata),           //                .writedata
		.asi_hit_type1_channel       (data_splitter_0_out2_channel),              //       hit_type1.channel
		.asi_hit_type1_startofpacket (data_splitter_0_out2_startofpacket),        //                .startofpacket
		.asi_hit_type1_endofpacket   (data_splitter_0_out2_endofpacket),          //                .endofpacket
		.asi_hit_type1_empty         (data_splitter_0_out2_empty),                //                .empty
		.asi_hit_type1_data          (data_splitter_0_out2_data),                 //                .data
		.asi_hit_type1_valid         (data_splitter_0_out2_valid),                //                .valid
		.asi_hit_type1_ready         (data_splitter_0_out2_ready),                //                .ready
		.asi_hit_type1_error         (data_splitter_0_out2_error),                //                .error
		.aso_hit_type2_channel       (ring_buffer_cam_2_hit_type2_channel),       //       hit_type2.channel
		.aso_hit_type2_startofpacket (ring_buffer_cam_2_hit_type2_startofpacket), //                .startofpacket
		.aso_hit_type2_endofpacket   (ring_buffer_cam_2_hit_type2_endofpacket),   //                .endofpacket
		.aso_hit_type2_data          (ring_buffer_cam_2_hit_type2_data),          //                .data
		.aso_hit_type2_valid         (ring_buffer_cam_2_hit_type2_valid),         //                .valid
		.aso_hit_type2_ready         (ring_buffer_cam_2_hit_type2_ready),         //                .ready
		.aso_hit_type2_error         (ring_buffer_cam_2_hit_type2_error),         //                .error
		.i_clk                       (datapath_clock_clk),                        // clock_interface.clk
		.i_rst                       (rst_controller_reset_out_reset),            // reset_interface.reset
		.asi_ctrl_data               (run_control_splitter_0_out2_data),          //     run_control.data
		.asi_ctrl_valid              (run_control_splitter_0_out2_valid),         //                .valid
		.asi_ctrl_ready              (run_control_splitter_0_out2_ready),         //                .ready
		.aso_filllevel_data          (ring_buffer_cam_2_filllevel_data),          //       filllevel.data
		.aso_filllevel_valid         (ring_buffer_cam_2_filllevel_valid)          //                .valid
	);

	ring_buffer_cam #(
		.SEARCH_KEY_WIDTH    (8),
		.RING_BUFFER_N_ENTRY (512),
		.SIDE_DATA_BITS      (31),
		.INTERLEAVING_FACTOR (4),
		.INTERLEAVING_INDEX  (3),
		.N_PARTITIONS        (4),
		.ENCODER_LEAF_WIDTH  (16),
		.ENCODER_PIPE_STAGES (4),
		.DEBUG               (1),
		.IP_UID              (1380074317),
		.VERSION_MAJOR       (26),
		.VERSION_MINOR       (2),
		.VERSION_PATCH       (6),
		.BUILD               (422),
		.VERSION_DATE        (20260422),
		.VERSION_GIT         (267039347),
		.INSTANCE_ID         (0)
	) ring_buffer_cam_3 (
		.avs_csr_readdata            (ring_buffer_cam_3_csr_readdata),            //             csr.readdata
		.avs_csr_read                (ring_buffer_cam_3_csr_read),                //                .read
		.avs_csr_address             (ring_buffer_cam_3_csr_address),             //                .address
		.avs_csr_waitrequest         (ring_buffer_cam_3_csr_waitrequest),         //                .waitrequest
		.avs_csr_write               (ring_buffer_cam_3_csr_write),               //                .write
		.avs_csr_writedata           (ring_buffer_cam_3_csr_writedata),           //                .writedata
		.asi_hit_type1_channel       (data_splitter_0_out3_channel),              //       hit_type1.channel
		.asi_hit_type1_startofpacket (data_splitter_0_out3_startofpacket),        //                .startofpacket
		.asi_hit_type1_endofpacket   (data_splitter_0_out3_endofpacket),          //                .endofpacket
		.asi_hit_type1_empty         (data_splitter_0_out3_empty),                //                .empty
		.asi_hit_type1_data          (data_splitter_0_out3_data),                 //                .data
		.asi_hit_type1_valid         (data_splitter_0_out3_valid),                //                .valid
		.asi_hit_type1_ready         (data_splitter_0_out3_ready),                //                .ready
		.asi_hit_type1_error         (data_splitter_0_out3_error),                //                .error
		.aso_hit_type2_channel       (ring_buffer_cam_3_hit_type2_channel),       //       hit_type2.channel
		.aso_hit_type2_startofpacket (ring_buffer_cam_3_hit_type2_startofpacket), //                .startofpacket
		.aso_hit_type2_endofpacket   (ring_buffer_cam_3_hit_type2_endofpacket),   //                .endofpacket
		.aso_hit_type2_data          (ring_buffer_cam_3_hit_type2_data),          //                .data
		.aso_hit_type2_valid         (ring_buffer_cam_3_hit_type2_valid),         //                .valid
		.aso_hit_type2_ready         (ring_buffer_cam_3_hit_type2_ready),         //                .ready
		.aso_hit_type2_error         (ring_buffer_cam_3_hit_type2_error),         //                .error
		.i_clk                       (datapath_clock_clk),                        // clock_interface.clk
		.i_rst                       (rst_controller_reset_out_reset),            // reset_interface.reset
		.asi_ctrl_data               (run_control_splitter_0_out3_data),          //     run_control.data
		.asi_ctrl_valid              (run_control_splitter_0_out3_valid),         //                .valid
		.asi_ctrl_ready              (run_control_splitter_0_out3_ready),         //                .ready
		.aso_filllevel_data          (ring_buffer_cam_3_filllevel_data),          //       filllevel.data
		.aso_filllevel_valid         (ring_buffer_cam_3_filllevel_valid)          //                .valid
	);

	altera_avalon_st_splitter #(
		.NUMBER_OF_OUTPUTS (6),
		.QUALIFY_VALID_OUT (0),
		.USE_PACKETS       (0),
		.DATA_WIDTH        (9),
		.CHANNEL_WIDTH     (1),
		.ERROR_WIDTH       (1),
		.BITS_PER_SYMBOL   (9),
		.EMPTY_WIDTH       (1)
	) run_control_splitter_0 (
		.clk                 (datapath_clock_clk),                //   clk.clk
		.reset               (rst_controller_reset_out_reset),    // reset.reset
		.in0_ready           (run_control_signal_ready),          //    in.ready
		.in0_valid           (run_control_signal_valid),          //      .valid
		.in0_data            (run_control_signal_data),           //      .data
		.out0_ready          (run_control_splitter_0_out0_ready), //  out0.ready
		.out0_valid          (run_control_splitter_0_out0_valid), //      .valid
		.out0_data           (run_control_splitter_0_out0_data),  //      .data
		.out1_ready          (run_control_splitter_0_out1_ready), //  out1.ready
		.out1_valid          (run_control_splitter_0_out1_valid), //      .valid
		.out1_data           (run_control_splitter_0_out1_data),  //      .data
		.out2_ready          (run_control_splitter_0_out2_ready), //  out2.ready
		.out2_valid          (run_control_splitter_0_out2_valid), //      .valid
		.out2_data           (run_control_splitter_0_out2_data),  //      .data
		.out3_ready          (run_control_splitter_0_out3_ready), //  out3.ready
		.out3_valid          (run_control_splitter_0_out3_valid), //      .valid
		.out3_data           (run_control_splitter_0_out3_data),  //      .data
		.out4_ready          (run_control_splitter_0_out4_ready), //  out4.ready
		.out4_valid          (run_control_splitter_0_out4_valid), //      .valid
		.out4_data           (run_control_splitter_0_out4_data),  //      .data
		.out5_ready          (run_control_splitter_0_out5_ready), //  out5.ready
		.out5_valid          (run_control_splitter_0_out5_valid), //      .valid
		.out5_data           (run_control_splitter_0_out5_data),  //      .data
		.in0_startofpacket   (1'b0),                              // (terminated)
		.in0_endofpacket     (1'b0),                              // (terminated)
		.in0_empty           (1'b0),                              // (terminated)
		.in0_channel         (1'b0),                              // (terminated)
		.in0_error           (1'b0),                              // (terminated)
		.out0_startofpacket  (),                                  // (terminated)
		.out0_endofpacket    (),                                  // (terminated)
		.out0_empty          (),                                  // (terminated)
		.out0_channel        (),                                  // (terminated)
		.out0_error          (),                                  // (terminated)
		.out1_startofpacket  (),                                  // (terminated)
		.out1_endofpacket    (),                                  // (terminated)
		.out1_empty          (),                                  // (terminated)
		.out1_channel        (),                                  // (terminated)
		.out1_error          (),                                  // (terminated)
		.out2_startofpacket  (),                                  // (terminated)
		.out2_endofpacket    (),                                  // (terminated)
		.out2_empty          (),                                  // (terminated)
		.out2_channel        (),                                  // (terminated)
		.out2_error          (),                                  // (terminated)
		.out3_startofpacket  (),                                  // (terminated)
		.out3_endofpacket    (),                                  // (terminated)
		.out3_empty          (),                                  // (terminated)
		.out3_channel        (),                                  // (terminated)
		.out3_error          (),                                  // (terminated)
		.out4_startofpacket  (),                                  // (terminated)
		.out4_endofpacket    (),                                  // (terminated)
		.out4_empty          (),                                  // (terminated)
		.out4_channel        (),                                  // (terminated)
		.out4_error          (),                                  // (terminated)
		.out5_startofpacket  (),                                  // (terminated)
		.out5_endofpacket    (),                                  // (terminated)
		.out5_empty          (),                                  // (terminated)
		.out5_channel        (),                                  // (terminated)
		.out5_error          (),                                  // (terminated)
		.out6_ready          (1'b1),                              // (terminated)
		.out6_valid          (),                                  // (terminated)
		.out6_startofpacket  (),                                  // (terminated)
		.out6_endofpacket    (),                                  // (terminated)
		.out6_empty          (),                                  // (terminated)
		.out6_channel        (),                                  // (terminated)
		.out6_error          (),                                  // (terminated)
		.out6_data           (),                                  // (terminated)
		.out7_ready          (1'b1),                              // (terminated)
		.out7_valid          (),                                  // (terminated)
		.out7_startofpacket  (),                                  // (terminated)
		.out7_endofpacket    (),                                  // (terminated)
		.out7_empty          (),                                  // (terminated)
		.out7_channel        (),                                  // (terminated)
		.out7_error          (),                                  // (terminated)
		.out7_data           (),                                  // (terminated)
		.out8_ready          (1'b1),                              // (terminated)
		.out8_valid          (),                                  // (terminated)
		.out8_startofpacket  (),                                  // (terminated)
		.out8_endofpacket    (),                                  // (terminated)
		.out8_empty          (),                                  // (terminated)
		.out8_channel        (),                                  // (terminated)
		.out8_error          (),                                  // (terminated)
		.out8_data           (),                                  // (terminated)
		.out9_ready          (1'b1),                              // (terminated)
		.out9_valid          (),                                  // (terminated)
		.out9_startofpacket  (),                                  // (terminated)
		.out9_endofpacket    (),                                  // (terminated)
		.out9_empty          (),                                  // (terminated)
		.out9_channel        (),                                  // (terminated)
		.out9_error          (),                                  // (terminated)
		.out9_data           (),                                  // (terminated)
		.out10_ready         (1'b1),                              // (terminated)
		.out10_valid         (),                                  // (terminated)
		.out10_startofpacket (),                                  // (terminated)
		.out10_endofpacket   (),                                  // (terminated)
		.out10_empty         (),                                  // (terminated)
		.out10_channel       (),                                  // (terminated)
		.out10_error         (),                                  // (terminated)
		.out10_data          (),                                  // (terminated)
		.out11_ready         (1'b1),                              // (terminated)
		.out11_valid         (),                                  // (terminated)
		.out11_startofpacket (),                                  // (terminated)
		.out11_endofpacket   (),                                  // (terminated)
		.out11_empty         (),                                  // (terminated)
		.out11_channel       (),                                  // (terminated)
		.out11_error         (),                                  // (terminated)
		.out11_data          (),                                  // (terminated)
		.out12_ready         (1'b1),                              // (terminated)
		.out12_valid         (),                                  // (terminated)
		.out12_startofpacket (),                                  // (terminated)
		.out12_endofpacket   (),                                  // (terminated)
		.out12_empty         (),                                  // (terminated)
		.out12_channel       (),                                  // (terminated)
		.out12_error         (),                                  // (terminated)
		.out12_data          (),                                  // (terminated)
		.out13_ready         (1'b1),                              // (terminated)
		.out13_valid         (),                                  // (terminated)
		.out13_startofpacket (),                                  // (terminated)
		.out13_endofpacket   (),                                  // (terminated)
		.out13_empty         (),                                  // (terminated)
		.out13_channel       (),                                  // (terminated)
		.out13_error         (),                                  // (terminated)
		.out13_data          (),                                  // (terminated)
		.out14_ready         (1'b1),                              // (terminated)
		.out14_valid         (),                                  // (terminated)
		.out14_startofpacket (),                                  // (terminated)
		.out14_endofpacket   (),                                  // (terminated)
		.out14_empty         (),                                  // (terminated)
		.out14_channel       (),                                  // (terminated)
		.out14_error         (),                                  // (terminated)
		.out14_data          (),                                  // (terminated)
		.out15_ready         (1'b1),                              // (terminated)
		.out15_valid         (),                                  // (terminated)
		.out15_startofpacket (),                                  // (terminated)
		.out15_endofpacket   (),                                  // (terminated)
		.out15_empty         (),                                  // (terminated)
		.out15_channel       (),                                  // (terminated)
		.out15_error         (),                                  // (terminated)
		.out15_data          ()                                   // (terminated)
	);

	altera_avalon_dc_fifo #(
		.SYMBOLS_PER_BEAT   (1),
		.BITS_PER_SYMBOL    (9),
		.FIFO_DEPTH         (16),
		.CHANNEL_WIDTH      (0),
		.ERROR_WIDTH        (0),
		.USE_PACKETS        (0),
		.USE_IN_FILL_LEVEL  (0),
		.USE_OUT_FILL_LEVEL (0),
		.WR_SYNC_DEPTH      (3),
		.RD_SYNC_DEPTH      (3)
	) run_ctrl_cdc_d2x (
		.in_clk            (datapath_clock_clk),                   //        in_clk.clk
		.in_reset_n        (~rst_controller_reset_out_reset),      //  in_clk_reset.reset_n
		.out_clk           (xcvr_clock_clk),                       //       out_clk.clk
		.out_reset_n       (~rst_controller_001_reset_out_reset),  // out_clk_reset.reset_n
		.in_data           (run_control_splitter_0_out5_data),     //            in.data
		.in_valid          (run_control_splitter_0_out5_valid),    //              .valid
		.in_ready          (run_control_splitter_0_out5_ready),    //              .ready
		.out_data          (run_ctrl_cdc_d2x_out_data),            //           out.data
		.out_valid         (run_ctrl_cdc_d2x_out_valid),           //              .valid
		.out_ready         (run_ctrl_cdc_d2x_out_ready),           //              .ready
		.in_csr_address    (1'b0),                                 //   (terminated)
		.in_csr_read       (1'b0),                                 //   (terminated)
		.in_csr_write      (1'b0),                                 //   (terminated)
		.in_csr_readdata   (),                                     //   (terminated)
		.in_csr_writedata  (32'b00000000000000000000000000000000), //   (terminated)
		.out_csr_address   (1'b0),                                 //   (terminated)
		.out_csr_read      (1'b0),                                 //   (terminated)
		.out_csr_write     (1'b0),                                 //   (terminated)
		.out_csr_readdata  (),                                     //   (terminated)
		.out_csr_writedata (32'b00000000000000000000000000000000), //   (terminated)
		.in_startofpacket  (1'b0),                                 //   (terminated)
		.in_endofpacket    (1'b0),                                 //   (terminated)
		.out_startofpacket (),                                     //   (terminated)
		.out_endofpacket   (),                                     //   (terminated)
		.in_empty          (1'b0),                                 //   (terminated)
		.out_empty         (),                                     //   (terminated)
		.in_error          (1'b0),                                 //   (terminated)
		.out_error         (),                                     //   (terminated)
		.in_channel        (1'b0),                                 //   (terminated)
		.out_channel       (),                                     //   (terminated)
		.space_avail_data  ()                                      //   (terminated)
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (0),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller (
		.reset_in0      (~datapath_reset_reset_n),        // reset_in0.reset
		.clk            (datapath_clock_clk),             //       clk.clk
		.reset_out      (rst_controller_reset_out_reset), // reset_out.reset
		.reset_req      (),                               // (terminated)
		.reset_req_in0  (1'b0),                           // (terminated)
		.reset_in1      (1'b0),                           // (terminated)
		.reset_req_in1  (1'b0),                           // (terminated)
		.reset_in2      (1'b0),                           // (terminated)
		.reset_req_in2  (1'b0),                           // (terminated)
		.reset_in3      (1'b0),                           // (terminated)
		.reset_req_in3  (1'b0),                           // (terminated)
		.reset_in4      (1'b0),                           // (terminated)
		.reset_req_in4  (1'b0),                           // (terminated)
		.reset_in5      (1'b0),                           // (terminated)
		.reset_req_in5  (1'b0),                           // (terminated)
		.reset_in6      (1'b0),                           // (terminated)
		.reset_req_in6  (1'b0),                           // (terminated)
		.reset_in7      (1'b0),                           // (terminated)
		.reset_req_in7  (1'b0),                           // (terminated)
		.reset_in8      (1'b0),                           // (terminated)
		.reset_req_in8  (1'b0),                           // (terminated)
		.reset_in9      (1'b0),                           // (terminated)
		.reset_req_in9  (1'b0),                           // (terminated)
		.reset_in10     (1'b0),                           // (terminated)
		.reset_req_in10 (1'b0),                           // (terminated)
		.reset_in11     (1'b0),                           // (terminated)
		.reset_req_in11 (1'b0),                           // (terminated)
		.reset_in12     (1'b0),                           // (terminated)
		.reset_req_in12 (1'b0),                           // (terminated)
		.reset_in13     (1'b0),                           // (terminated)
		.reset_req_in13 (1'b0),                           // (terminated)
		.reset_in14     (1'b0),                           // (terminated)
		.reset_req_in14 (1'b0),                           // (terminated)
		.reset_in15     (1'b0),                           // (terminated)
		.reset_req_in15 (1'b0)                            // (terminated)
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (0),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller_001 (
		.reset_in0      (~xcvr_reset_reset_n),                // reset_in0.reset
		.clk            (xcvr_clock_clk),                     //       clk.clk
		.reset_out      (rst_controller_001_reset_out_reset), // reset_out.reset
		.reset_req      (),                                   // (terminated)
		.reset_req_in0  (1'b0),                               // (terminated)
		.reset_in1      (1'b0),                               // (terminated)
		.reset_req_in1  (1'b0),                               // (terminated)
		.reset_in2      (1'b0),                               // (terminated)
		.reset_req_in2  (1'b0),                               // (terminated)
		.reset_in3      (1'b0),                               // (terminated)
		.reset_req_in3  (1'b0),                               // (terminated)
		.reset_in4      (1'b0),                               // (terminated)
		.reset_req_in4  (1'b0),                               // (terminated)
		.reset_in5      (1'b0),                               // (terminated)
		.reset_req_in5  (1'b0),                               // (terminated)
		.reset_in6      (1'b0),                               // (terminated)
		.reset_req_in6  (1'b0),                               // (terminated)
		.reset_in7      (1'b0),                               // (terminated)
		.reset_req_in7  (1'b0),                               // (terminated)
		.reset_in8      (1'b0),                               // (terminated)
		.reset_req_in8  (1'b0),                               // (terminated)
		.reset_in9      (1'b0),                               // (terminated)
		.reset_req_in9  (1'b0),                               // (terminated)
		.reset_in10     (1'b0),                               // (terminated)
		.reset_req_in10 (1'b0),                               // (terminated)
		.reset_in11     (1'b0),                               // (terminated)
		.reset_req_in11 (1'b0),                               // (terminated)
		.reset_in12     (1'b0),                               // (terminated)
		.reset_req_in12 (1'b0),                               // (terminated)
		.reset_in13     (1'b0),                               // (terminated)
		.reset_req_in13 (1'b0),                               // (terminated)
		.reset_in14     (1'b0),                               // (terminated)
		.reset_req_in14 (1'b0),                               // (terminated)
		.reset_in15     (1'b0),                               // (terminated)
		.reset_req_in15 (1'b0)                                // (terminated)
	);

endmodule
