// scifi_datapath_system_v3_pipe_mutrig_datapath_subsystem_6.v

// Generated using ACDS version 18.1 625

`timescale 1 ps / 1 ps
module scifi_datapath_system_v3_pipe_mutrig_datapath_subsystem_6 (
		input  wire [1:0]  backpressure_fifo_csr_address,   // backpressure_fifo_csr.address
		input  wire        backpressure_fifo_csr_read,      //                      .read
		input  wire        backpressure_fifo_csr_write,     //                      .write
		output wire [31:0] backpressure_fifo_csr_readdata,  //                      .readdata
		input  wire [31:0] backpressure_fifo_csr_writedata, //                      .writedata
		input  wire        clk_clk,                         //                   clk.clk
		input  wire        csr_read,                        //                   csr.read
		output wire [31:0] csr_readdata,                    //                      .readdata
		output wire        csr_waitrequest,                 //                      .waitrequest
		input  wire        csr_write,                       //                      .write
		input  wire [31:0] csr_writedata,                   //                      .writedata
		input  wire [1:0]  csr_address,                     //                      .address
		input  wire [8:0]  decoded_din_data,                //           decoded_din.data
		input  wire        decoded_din_valid,               //                      .valid
		input  wire [2:0]  decoded_din_error,               //                      .error
		input  wire [3:0]  decoded_din_channel,             //                      .channel
		output wire [41:0] headerinfo_data,                 //            headerinfo.data
		output wire        headerinfo_valid,                //                      .valid
		output wire [3:0]  headerinfo_channel,              //                      .channel
		output wire [44:0] hit_type0_out_data,              //         hit_type0_out.data
		output wire        hit_type0_out_valid,             //                      .valid
		input  wire        hit_type0_out_ready,             //                      .ready
		output wire        hit_type0_out_startofpacket,     //                      .startofpacket
		output wire        hit_type0_out_endofpacket,       //                      .endofpacket
		output wire [2:0]  hit_type0_out_error,             //                      .error
		output wire [3:0]  hit_type0_out_channel,           //                      .channel
		input  wire        reset_reset_n,                   //                 reset.reset_n
		input  wire [8:0]  run_ctrl_data,                   //              run_ctrl.data
		input  wire        run_ctrl_valid,                  //                      .valid
		output wire        run_ctrl_ready                   //                      .ready
	);

	wire         mutrig_frame_deassembly_0_hit_type0_valid;         // mutrig_frame_deassembly_0:aso_hit_type0_valid -> avalon_st_adapter:in_0_valid
	wire  [44:0] mutrig_frame_deassembly_0_hit_type0_data;          // mutrig_frame_deassembly_0:aso_hit_type0_data -> avalon_st_adapter:in_0_data
	wire   [3:0] mutrig_frame_deassembly_0_hit_type0_channel;       // mutrig_frame_deassembly_0:aso_hit_type0_channel -> avalon_st_adapter:in_0_channel
	wire         mutrig_frame_deassembly_0_hit_type0_startofpacket; // mutrig_frame_deassembly_0:aso_hit_type0_startofpacket -> avalon_st_adapter:in_0_startofpacket
	wire         mutrig_frame_deassembly_0_hit_type0_endofpacket;   // mutrig_frame_deassembly_0:aso_hit_type0_endofpacket -> avalon_st_adapter:in_0_endofpacket
	wire   [2:0] mutrig_frame_deassembly_0_hit_type0_error;         // mutrig_frame_deassembly_0:aso_hit_type0_error -> avalon_st_adapter:in_0_error
	wire         avalon_st_adapter_out_0_valid;                     // avalon_st_adapter:out_0_valid -> backpressure_fifo:in_valid
	wire  [44:0] avalon_st_adapter_out_0_data;                      // avalon_st_adapter:out_0_data -> backpressure_fifo:in_data
	wire         avalon_st_adapter_out_0_ready;                     // backpressure_fifo:in_ready -> avalon_st_adapter:out_0_ready
	wire   [3:0] avalon_st_adapter_out_0_channel;                   // avalon_st_adapter:out_0_channel -> backpressure_fifo:in_channel
	wire         avalon_st_adapter_out_0_startofpacket;             // avalon_st_adapter:out_0_startofpacket -> backpressure_fifo:in_startofpacket
	wire         avalon_st_adapter_out_0_endofpacket;               // avalon_st_adapter:out_0_endofpacket -> backpressure_fifo:in_endofpacket
	wire   [2:0] avalon_st_adapter_out_0_error;                     // avalon_st_adapter:out_0_error -> backpressure_fifo:in_error
	wire         rst_controller_reset_out_reset;                    // rst_controller:reset_out -> mutrig_frame_deassembly_0:i_rst

	altera_avalon_sc_fifo #(
		.SYMBOLS_PER_BEAT    (1),
		.BITS_PER_SYMBOL     (45),
		.FIFO_DEPTH          (128),
		.CHANNEL_WIDTH       (4),
		.ERROR_WIDTH         (3),
		.USE_PACKETS         (1),
		.USE_FILL_LEVEL      (1),
		.EMPTY_LATENCY       (3),
		.USE_MEMORY_BLOCKS   (1),
		.USE_STORE_FORWARD   (0),
		.USE_ALMOST_FULL_IF  (0),
		.USE_ALMOST_EMPTY_IF (1)
	) backpressure_fifo (
		.clk               (clk_clk),                               //          clk.clk
		.reset             (~reset_reset_n),                        //    clk_reset.reset
		.csr_address       (backpressure_fifo_csr_address),         //          csr.address
		.csr_read          (backpressure_fifo_csr_read),            //             .read
		.csr_write         (backpressure_fifo_csr_write),           //             .write
		.csr_readdata      (backpressure_fifo_csr_readdata),        //             .readdata
		.csr_writedata     (backpressure_fifo_csr_writedata),       //             .writedata
		.almost_empty_data (),                                      // almost_empty.data
		.in_data           (avalon_st_adapter_out_0_data),          //           in.data
		.in_valid          (avalon_st_adapter_out_0_valid),         //             .valid
		.in_ready          (avalon_st_adapter_out_0_ready),         //             .ready
		.in_startofpacket  (avalon_st_adapter_out_0_startofpacket), //             .startofpacket
		.in_endofpacket    (avalon_st_adapter_out_0_endofpacket),   //             .endofpacket
		.in_error          (avalon_st_adapter_out_0_error),         //             .error
		.in_channel        (avalon_st_adapter_out_0_channel),       //             .channel
		.out_data          (hit_type0_out_data),                    //          out.data
		.out_valid         (hit_type0_out_valid),                   //             .valid
		.out_ready         (hit_type0_out_ready),                   //             .ready
		.out_startofpacket (hit_type0_out_startofpacket),           //             .startofpacket
		.out_endofpacket   (hit_type0_out_endofpacket),             //             .endofpacket
		.out_error         (hit_type0_out_error),                   //             .error
		.out_channel       (hit_type0_out_channel),                 //             .channel
		.almost_full_data  (),                                      //  (terminated)
		.in_empty          (1'b0),                                  //  (terminated)
		.out_empty         ()                                       //  (terminated)
	);

	frame_rcv_ip #(
		.CHANNEL_WIDTH  (4),
		.CSR_ADDR_WIDTH (2),
		.MODE_HALT      (0),
		.DEBUG_LV       (0)
	) mutrig_frame_deassembly_0 (
		.asi_rx8b1k_data             (decoded_din_data),                                  //     rx8b1k.data
		.asi_rx8b1k_valid            (decoded_din_valid),                                 //           .valid
		.asi_rx8b1k_error            (decoded_din_error),                                 //           .error
		.asi_rx8b1k_channel          (decoded_din_channel),                               //           .channel
		.aso_hit_type0_startofpacket (mutrig_frame_deassembly_0_hit_type0_startofpacket), //  hit_type0.startofpacket
		.aso_hit_type0_endofpacket   (mutrig_frame_deassembly_0_hit_type0_endofpacket),   //           .endofpacket
		.aso_hit_type0_endofrun      (),                                                  //           .endofrun
		.aso_hit_type0_error         (mutrig_frame_deassembly_0_hit_type0_error),         //           .error
		.aso_hit_type0_data          (mutrig_frame_deassembly_0_hit_type0_data),          //           .data
		.aso_hit_type0_valid         (mutrig_frame_deassembly_0_hit_type0_valid),         //           .valid
		.aso_hit_type0_channel       (mutrig_frame_deassembly_0_hit_type0_channel),       //           .channel
		.aso_headerinfo_data         (headerinfo_data),                                   // headerinfo.data
		.aso_headerinfo_valid        (headerinfo_valid),                                  //           .valid
		.aso_headerinfo_channel      (headerinfo_channel),                                //           .channel
		.avs_csr_read                (csr_read),                                          //        csr.read
		.avs_csr_readdata            (csr_readdata),                                      //           .readdata
		.avs_csr_waitrequest         (csr_waitrequest),                                   //           .waitrequest
		.avs_csr_write               (csr_write),                                         //           .write
		.avs_csr_writedata           (csr_writedata),                                     //           .writedata
		.avs_csr_address             (csr_address),                                       //           .address
		.asi_ctrl_data               (run_ctrl_data),                                     //       ctrl.data
		.asi_ctrl_valid              (run_ctrl_valid),                                    //           .valid
		.asi_ctrl_ready              (run_ctrl_ready),                                    //           .ready
		.i_clk                       (clk_clk),                                           // clock_sink.clk
		.i_rst                       (rst_controller_reset_out_reset)                     // reset_sink.reset
	);

	scifi_datapath_system_v3_pipe_mutrig_datapath_subsystem_0_avalon_st_adapter #(
		.inBitsPerSymbol (45),
		.inUsePackets    (1),
		.inDataWidth     (45),
		.inChannelWidth  (4),
		.inErrorWidth    (3),
		.inUseEmptyPort  (0),
		.inUseValid      (1),
		.inUseReady      (0),
		.inReadyLatency  (0),
		.outDataWidth    (45),
		.outChannelWidth (4),
		.outErrorWidth   (3),
		.outUseEmptyPort (0),
		.outUseValid     (1),
		.outUseReady     (1),
		.outReadyLatency (0)
	) avalon_st_adapter (
		.in_clk_0_clk        (clk_clk),                                           // in_clk_0.clk
		.in_rst_0_reset      (~reset_reset_n),                                    // in_rst_0.reset
		.in_0_data           (mutrig_frame_deassembly_0_hit_type0_data),          //     in_0.data
		.in_0_valid          (mutrig_frame_deassembly_0_hit_type0_valid),         //         .valid
		.in_0_startofpacket  (mutrig_frame_deassembly_0_hit_type0_startofpacket), //         .startofpacket
		.in_0_endofpacket    (mutrig_frame_deassembly_0_hit_type0_endofpacket),   //         .endofpacket
		.in_0_error          (mutrig_frame_deassembly_0_hit_type0_error),         //         .error
		.in_0_channel        (mutrig_frame_deassembly_0_hit_type0_channel),       //         .channel
		.out_0_data          (avalon_st_adapter_out_0_data),                      //    out_0.data
		.out_0_valid         (avalon_st_adapter_out_0_valid),                     //         .valid
		.out_0_ready         (avalon_st_adapter_out_0_ready),                     //         .ready
		.out_0_startofpacket (avalon_st_adapter_out_0_startofpacket),             //         .startofpacket
		.out_0_endofpacket   (avalon_st_adapter_out_0_endofpacket),               //         .endofpacket
		.out_0_error         (avalon_st_adapter_out_0_error),                     //         .error
		.out_0_channel       (avalon_st_adapter_out_0_channel)                    //         .channel
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("both"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (0),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller (
		.reset_in0      (~reset_reset_n),                 // reset_in0.reset
		.clk            (clk_clk),                        //       clk.clk
		.reset_out      (rst_controller_reset_out_reset), // reset_out.reset
		.reset_req      (),                               // (terminated)
		.reset_req_in0  (1'b0),                           // (terminated)
		.reset_in1      (1'b0),                           // (terminated)
		.reset_req_in1  (1'b0),                           // (terminated)
		.reset_in2      (1'b0),                           // (terminated)
		.reset_req_in2  (1'b0),                           // (terminated)
		.reset_in3      (1'b0),                           // (terminated)
		.reset_req_in3  (1'b0),                           // (terminated)
		.reset_in4      (1'b0),                           // (terminated)
		.reset_req_in4  (1'b0),                           // (terminated)
		.reset_in5      (1'b0),                           // (terminated)
		.reset_req_in5  (1'b0),                           // (terminated)
		.reset_in6      (1'b0),                           // (terminated)
		.reset_req_in6  (1'b0),                           // (terminated)
		.reset_in7      (1'b0),                           // (terminated)
		.reset_req_in7  (1'b0),                           // (terminated)
		.reset_in8      (1'b0),                           // (terminated)
		.reset_req_in8  (1'b0),                           // (terminated)
		.reset_in9      (1'b0),                           // (terminated)
		.reset_req_in9  (1'b0),                           // (terminated)
		.reset_in10     (1'b0),                           // (terminated)
		.reset_req_in10 (1'b0),                           // (terminated)
		.reset_in11     (1'b0),                           // (terminated)
		.reset_req_in11 (1'b0),                           // (terminated)
		.reset_in12     (1'b0),                           // (terminated)
		.reset_req_in12 (1'b0),                           // (terminated)
		.reset_in13     (1'b0),                           // (terminated)
		.reset_req_in13 (1'b0),                           // (terminated)
		.reset_in14     (1'b0),                           // (terminated)
		.reset_req_in14 (1'b0),                           // (terminated)
		.reset_in15     (1'b0),                           // (terminated)
		.reset_req_in15 (1'b0)                            // (terminated)
	);

endmodule
