-- mutrig_datapath_system_v3.vhd

-- Generated using ACDS version 18.1 625

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity mutrig_datapath_system_v3 is
	port (
		backpressure_fifo_csr_address   : in  std_logic_vector(1 downto 0)  := (others => '0'); -- backpressure_fifo_csr.address
		backpressure_fifo_csr_read      : in  std_logic                     := '0';             --                      .read
		backpressure_fifo_csr_write     : in  std_logic                     := '0';             --                      .write
		backpressure_fifo_csr_readdata  : out std_logic_vector(31 downto 0);                    --                      .readdata
		backpressure_fifo_csr_writedata : in  std_logic_vector(31 downto 0) := (others => '0'); --                      .writedata
		clk_clk                         : in  std_logic                     := '0';             --                   clk.clk
		csr_read                        : in  std_logic                     := '0';             --                   csr.read
		csr_readdata                    : out std_logic_vector(31 downto 0);                    --                      .readdata
		csr_waitrequest                 : out std_logic;                                        --                      .waitrequest
		csr_write                       : in  std_logic                     := '0';             --                      .write
		csr_writedata                   : in  std_logic_vector(31 downto 0) := (others => '0'); --                      .writedata
		csr_address                     : in  std_logic_vector(1 downto 0)  := (others => '0'); --                      .address
		decoded_din_data                : in  std_logic_vector(8 downto 0)  := (others => '0'); --           decoded_din.data
		decoded_din_valid               : in  std_logic                     := '0';             --                      .valid
		decoded_din_error               : in  std_logic_vector(2 downto 0)  := (others => '0'); --                      .error
		decoded_din_channel             : in  std_logic_vector(3 downto 0)  := (others => '0'); --                      .channel
		headerinfo_data                 : out std_logic_vector(41 downto 0);                    --            headerinfo.data
		headerinfo_valid                : out std_logic;                                        --                      .valid
		headerinfo_channel              : out std_logic_vector(3 downto 0);                     --                      .channel
		hit_type0_out_data              : out std_logic_vector(44 downto 0);                    --         hit_type0_out.data
		hit_type0_out_valid             : out std_logic;                                        --                      .valid
		hit_type0_out_ready             : in  std_logic                     := '0';             --                      .ready
		hit_type0_out_startofpacket     : out std_logic;                                        --                      .startofpacket
		hit_type0_out_endofpacket       : out std_logic;                                        --                      .endofpacket
		hit_type0_out_error             : out std_logic_vector(2 downto 0);                     --                      .error
		hit_type0_out_channel           : out std_logic_vector(3 downto 0);                     --                      .channel
		reset_reset_n                   : in  std_logic                     := '0';             --                 reset.reset_n
		run_ctrl_data                   : in  std_logic_vector(8 downto 0)  := (others => '0'); --              run_ctrl.data
		run_ctrl_valid                  : in  std_logic                     := '0';             --                      .valid
		run_ctrl_ready                  : out std_logic                                         --                      .ready
	);
end entity mutrig_datapath_system_v3;

architecture rtl of mutrig_datapath_system_v3 is
	component altera_avalon_sc_fifo is
		generic (
			SYMBOLS_PER_BEAT    : integer := 1;
			BITS_PER_SYMBOL     : integer := 8;
			FIFO_DEPTH          : integer := 16;
			CHANNEL_WIDTH       : integer := 0;
			ERROR_WIDTH         : integer := 0;
			USE_PACKETS         : integer := 0;
			USE_FILL_LEVEL      : integer := 0;
			EMPTY_LATENCY       : integer := 3;
			USE_MEMORY_BLOCKS   : integer := 1;
			USE_STORE_FORWARD   : integer := 0;
			USE_ALMOST_FULL_IF  : integer := 0;
			USE_ALMOST_EMPTY_IF : integer := 0
		);
		port (
			clk               : in  std_logic                     := 'X';             -- clk
			reset             : in  std_logic                     := 'X';             -- reset
			csr_address       : in  std_logic_vector(1 downto 0)  := (others => 'X'); -- address
			csr_read          : in  std_logic                     := 'X';             -- read
			csr_write         : in  std_logic                     := 'X';             -- write
			csr_readdata      : out std_logic_vector(31 downto 0);                    -- readdata
			csr_writedata     : in  std_logic_vector(31 downto 0) := (others => 'X'); -- writedata
			almost_empty_data : out std_logic;                                        -- data
			in_data           : in  std_logic_vector(44 downto 0) := (others => 'X'); -- data
			in_valid          : in  std_logic                     := 'X';             -- valid
			in_ready          : out std_logic;                                        -- ready
			in_startofpacket  : in  std_logic                     := 'X';             -- startofpacket
			in_endofpacket    : in  std_logic                     := 'X';             -- endofpacket
			in_error          : in  std_logic_vector(2 downto 0)  := (others => 'X'); -- error
			in_channel        : in  std_logic_vector(3 downto 0)  := (others => 'X'); -- channel
			out_data          : out std_logic_vector(44 downto 0);                    -- data
			out_valid         : out std_logic;                                        -- valid
			out_ready         : in  std_logic                     := 'X';             -- ready
			out_startofpacket : out std_logic;                                        -- startofpacket
			out_endofpacket   : out std_logic;                                        -- endofpacket
			out_error         : out std_logic_vector(2 downto 0);                     -- error
			out_channel       : out std_logic_vector(3 downto 0);                     -- channel
			almost_full_data  : out std_logic;                                        -- data
			in_empty          : in  std_logic_vector(0 downto 0)  := (others => 'X'); -- empty
			out_empty         : out std_logic_vector(0 downto 0)                      -- empty
		);
	end component altera_avalon_sc_fifo;

	component frame_rcv_ip is
		generic (
			CHANNEL_WIDTH  : natural := 4;
			CSR_ADDR_WIDTH : natural := 2;
			MODE_HALT      : natural := 0;
			DEBUG_LV       : natural := 0
		);
		port (
			asi_rx8b1k_data             : in  std_logic_vector(8 downto 0)  := (others => 'X'); -- data
			asi_rx8b1k_valid            : in  std_logic                     := 'X';             -- valid
			asi_rx8b1k_error            : in  std_logic_vector(2 downto 0)  := (others => 'X'); -- error
			asi_rx8b1k_channel          : in  std_logic_vector(3 downto 0)  := (others => 'X'); -- channel
			aso_hit_type0_startofpacket : out std_logic;                                        -- startofpacket
			aso_hit_type0_endofpacket   : out std_logic;                                        -- endofpacket
			aso_hit_type0_endofrun      : out std_logic;                                        -- endofrun
			aso_hit_type0_error         : out std_logic_vector(2 downto 0);                     -- error
			aso_hit_type0_data          : out std_logic_vector(44 downto 0);                    -- data
			aso_hit_type0_valid         : out std_logic;                                        -- valid
			aso_hit_type0_channel       : out std_logic_vector(3 downto 0);                     -- channel
			aso_headerinfo_data         : out std_logic_vector(41 downto 0);                    -- data
			aso_headerinfo_valid        : out std_logic;                                        -- valid
			aso_headerinfo_channel      : out std_logic_vector(3 downto 0);                     -- channel
			avs_csr_read                : in  std_logic                     := 'X';             -- read
			avs_csr_readdata            : out std_logic_vector(31 downto 0);                    -- readdata
			avs_csr_waitrequest         : out std_logic;                                        -- waitrequest
			avs_csr_write               : in  std_logic                     := 'X';             -- write
			avs_csr_writedata           : in  std_logic_vector(31 downto 0) := (others => 'X'); -- writedata
			avs_csr_address             : in  std_logic_vector(1 downto 0)  := (others => 'X'); -- address
			asi_ctrl_data               : in  std_logic_vector(8 downto 0)  := (others => 'X'); -- data
			asi_ctrl_valid              : in  std_logic                     := 'X';             -- valid
			asi_ctrl_ready              : out std_logic;                                        -- ready
			i_clk                       : in  std_logic                     := 'X';             -- clk
			i_rst                       : in  std_logic                     := 'X'              -- reset
		);
	end component frame_rcv_ip;

	component mutrig_datapath_system_v3_avalon_st_adapter is
		generic (
			inBitsPerSymbol : integer := 8;
			inUsePackets    : integer := 0;
			inDataWidth     : integer := 8;
			inChannelWidth  : integer := 3;
			inErrorWidth    : integer := 2;
			inUseEmptyPort  : integer := 0;
			inUseValid      : integer := 1;
			inUseReady      : integer := 1;
			inReadyLatency  : integer := 0;
			outDataWidth    : integer := 32;
			outChannelWidth : integer := 3;
			outErrorWidth   : integer := 2;
			outUseEmptyPort : integer := 0;
			outUseValid     : integer := 1;
			outUseReady     : integer := 1;
			outReadyLatency : integer := 0
		);
		port (
			in_clk_0_clk        : in  std_logic                     := 'X';             -- clk
			in_rst_0_reset      : in  std_logic                     := 'X';             -- reset
			in_0_data           : in  std_logic_vector(44 downto 0) := (others => 'X'); -- data
			in_0_valid          : in  std_logic                     := 'X';             -- valid
			in_0_startofpacket  : in  std_logic                     := 'X';             -- startofpacket
			in_0_endofpacket    : in  std_logic                     := 'X';             -- endofpacket
			in_0_error          : in  std_logic_vector(2 downto 0)  := (others => 'X'); -- error
			in_0_channel        : in  std_logic_vector(3 downto 0)  := (others => 'X'); -- channel
			out_0_data          : out std_logic_vector(44 downto 0);                    -- data
			out_0_valid         : out std_logic;                                        -- valid
			out_0_ready         : in  std_logic                     := 'X';             -- ready
			out_0_startofpacket : out std_logic;                                        -- startofpacket
			out_0_endofpacket   : out std_logic;                                        -- endofpacket
			out_0_error         : out std_logic_vector(2 downto 0);                     -- error
			out_0_channel       : out std_logic_vector(3 downto 0)                      -- channel
		);
	end component mutrig_datapath_system_v3_avalon_st_adapter;

	component altera_reset_controller is
		generic (
			NUM_RESET_INPUTS          : integer := 6;
			OUTPUT_RESET_SYNC_EDGES   : string  := "deassert";
			SYNC_DEPTH                : integer := 2;
			RESET_REQUEST_PRESENT     : integer := 0;
			RESET_REQ_WAIT_TIME       : integer := 1;
			MIN_RST_ASSERTION_TIME    : integer := 3;
			RESET_REQ_EARLY_DSRT_TIME : integer := 1;
			USE_RESET_REQUEST_IN0     : integer := 0;
			USE_RESET_REQUEST_IN1     : integer := 0;
			USE_RESET_REQUEST_IN2     : integer := 0;
			USE_RESET_REQUEST_IN3     : integer := 0;
			USE_RESET_REQUEST_IN4     : integer := 0;
			USE_RESET_REQUEST_IN5     : integer := 0;
			USE_RESET_REQUEST_IN6     : integer := 0;
			USE_RESET_REQUEST_IN7     : integer := 0;
			USE_RESET_REQUEST_IN8     : integer := 0;
			USE_RESET_REQUEST_IN9     : integer := 0;
			USE_RESET_REQUEST_IN10    : integer := 0;
			USE_RESET_REQUEST_IN11    : integer := 0;
			USE_RESET_REQUEST_IN12    : integer := 0;
			USE_RESET_REQUEST_IN13    : integer := 0;
			USE_RESET_REQUEST_IN14    : integer := 0;
			USE_RESET_REQUEST_IN15    : integer := 0;
			ADAPT_RESET_REQUEST       : integer := 0
		);
		port (
			reset_in0      : in  std_logic := 'X'; -- reset
			clk            : in  std_logic := 'X'; -- clk
			reset_out      : out std_logic;        -- reset
			reset_req      : out std_logic;        -- reset_req
			reset_req_in0  : in  std_logic := 'X'; -- reset_req
			reset_in1      : in  std_logic := 'X'; -- reset
			reset_req_in1  : in  std_logic := 'X'; -- reset_req
			reset_in2      : in  std_logic := 'X'; -- reset
			reset_req_in2  : in  std_logic := 'X'; -- reset_req
			reset_in3      : in  std_logic := 'X'; -- reset
			reset_req_in3  : in  std_logic := 'X'; -- reset_req
			reset_in4      : in  std_logic := 'X'; -- reset
			reset_req_in4  : in  std_logic := 'X'; -- reset_req
			reset_in5      : in  std_logic := 'X'; -- reset
			reset_req_in5  : in  std_logic := 'X'; -- reset_req
			reset_in6      : in  std_logic := 'X'; -- reset
			reset_req_in6  : in  std_logic := 'X'; -- reset_req
			reset_in7      : in  std_logic := 'X'; -- reset
			reset_req_in7  : in  std_logic := 'X'; -- reset_req
			reset_in8      : in  std_logic := 'X'; -- reset
			reset_req_in8  : in  std_logic := 'X'; -- reset_req
			reset_in9      : in  std_logic := 'X'; -- reset
			reset_req_in9  : in  std_logic := 'X'; -- reset_req
			reset_in10     : in  std_logic := 'X'; -- reset
			reset_req_in10 : in  std_logic := 'X'; -- reset_req
			reset_in11     : in  std_logic := 'X'; -- reset
			reset_req_in11 : in  std_logic := 'X'; -- reset_req
			reset_in12     : in  std_logic := 'X'; -- reset
			reset_req_in12 : in  std_logic := 'X'; -- reset_req
			reset_in13     : in  std_logic := 'X'; -- reset
			reset_req_in13 : in  std_logic := 'X'; -- reset_req
			reset_in14     : in  std_logic := 'X'; -- reset
			reset_req_in14 : in  std_logic := 'X'; -- reset_req
			reset_in15     : in  std_logic := 'X'; -- reset
			reset_req_in15 : in  std_logic := 'X'  -- reset_req
		);
	end component altera_reset_controller;

	signal mutrig_frame_deassembly_0_hit_type0_valid         : std_logic;                     -- mutrig_frame_deassembly_0:aso_hit_type0_valid -> avalon_st_adapter:in_0_valid
	signal mutrig_frame_deassembly_0_hit_type0_data          : std_logic_vector(44 downto 0); -- mutrig_frame_deassembly_0:aso_hit_type0_data -> avalon_st_adapter:in_0_data
	signal mutrig_frame_deassembly_0_hit_type0_channel       : std_logic_vector(3 downto 0);  -- mutrig_frame_deassembly_0:aso_hit_type0_channel -> avalon_st_adapter:in_0_channel
	signal mutrig_frame_deassembly_0_hit_type0_startofpacket : std_logic;                     -- mutrig_frame_deassembly_0:aso_hit_type0_startofpacket -> avalon_st_adapter:in_0_startofpacket
	signal mutrig_frame_deassembly_0_hit_type0_endofpacket   : std_logic;                     -- mutrig_frame_deassembly_0:aso_hit_type0_endofpacket -> avalon_st_adapter:in_0_endofpacket
	signal mutrig_frame_deassembly_0_hit_type0_error         : std_logic_vector(2 downto 0);  -- mutrig_frame_deassembly_0:aso_hit_type0_error -> avalon_st_adapter:in_0_error
	signal avalon_st_adapter_out_0_valid                     : std_logic;                     -- avalon_st_adapter:out_0_valid -> backpressure_fifo:in_valid
	signal avalon_st_adapter_out_0_data                      : std_logic_vector(44 downto 0); -- avalon_st_adapter:out_0_data -> backpressure_fifo:in_data
	signal avalon_st_adapter_out_0_ready                     : std_logic;                     -- backpressure_fifo:in_ready -> avalon_st_adapter:out_0_ready
	signal avalon_st_adapter_out_0_channel                   : std_logic_vector(3 downto 0);  -- avalon_st_adapter:out_0_channel -> backpressure_fifo:in_channel
	signal avalon_st_adapter_out_0_startofpacket             : std_logic;                     -- avalon_st_adapter:out_0_startofpacket -> backpressure_fifo:in_startofpacket
	signal avalon_st_adapter_out_0_endofpacket               : std_logic;                     -- avalon_st_adapter:out_0_endofpacket -> backpressure_fifo:in_endofpacket
	signal avalon_st_adapter_out_0_error                     : std_logic_vector(2 downto 0);  -- avalon_st_adapter:out_0_error -> backpressure_fifo:in_error
	signal rst_controller_reset_out_reset                    : std_logic;                     -- rst_controller:reset_out -> mutrig_frame_deassembly_0:i_rst
	signal reset_reset_n_ports_inv                           : std_logic;                     -- reset_reset_n:inv -> [avalon_st_adapter:in_rst_0_reset, backpressure_fifo:reset, rst_controller:reset_in0]

begin

	backpressure_fifo : component altera_avalon_sc_fifo
		generic map (
			SYMBOLS_PER_BEAT    => 1,
			BITS_PER_SYMBOL     => 45,
			FIFO_DEPTH          => 128,
			CHANNEL_WIDTH       => 4,
			ERROR_WIDTH         => 3,
			USE_PACKETS         => 1,
			USE_FILL_LEVEL      => 1,
			EMPTY_LATENCY       => 3,
			USE_MEMORY_BLOCKS   => 1,
			USE_STORE_FORWARD   => 0,
			USE_ALMOST_FULL_IF  => 0,
			USE_ALMOST_EMPTY_IF => 1
		)
		port map (
			clk               => clk_clk,                               --          clk.clk
			reset             => reset_reset_n_ports_inv,               --    clk_reset.reset
			csr_address       => backpressure_fifo_csr_address,         --          csr.address
			csr_read          => backpressure_fifo_csr_read,            --             .read
			csr_write         => backpressure_fifo_csr_write,           --             .write
			csr_readdata      => backpressure_fifo_csr_readdata,        --             .readdata
			csr_writedata     => backpressure_fifo_csr_writedata,       --             .writedata
			almost_empty_data => open,                                  -- almost_empty.data
			in_data           => avalon_st_adapter_out_0_data,          --           in.data
			in_valid          => avalon_st_adapter_out_0_valid,         --             .valid
			in_ready          => avalon_st_adapter_out_0_ready,         --             .ready
			in_startofpacket  => avalon_st_adapter_out_0_startofpacket, --             .startofpacket
			in_endofpacket    => avalon_st_adapter_out_0_endofpacket,   --             .endofpacket
			in_error          => avalon_st_adapter_out_0_error,         --             .error
			in_channel        => avalon_st_adapter_out_0_channel,       --             .channel
			out_data          => hit_type0_out_data,                    --          out.data
			out_valid         => hit_type0_out_valid,                   --             .valid
			out_ready         => hit_type0_out_ready,                   --             .ready
			out_startofpacket => hit_type0_out_startofpacket,           --             .startofpacket
			out_endofpacket   => hit_type0_out_endofpacket,             --             .endofpacket
			out_error         => hit_type0_out_error,                   --             .error
			out_channel       => hit_type0_out_channel,                 --             .channel
			almost_full_data  => open,                                  --  (terminated)
			in_empty          => "0",                                   --  (terminated)
			out_empty         => open                                   --  (terminated)
		);

	mutrig_frame_deassembly_0 : component frame_rcv_ip
		generic map (
			CHANNEL_WIDTH  => 4,
			CSR_ADDR_WIDTH => 2,
			MODE_HALT      => 0,
			DEBUG_LV       => 0
		)
		port map (
			asi_rx8b1k_data             => decoded_din_data,                                  --     rx8b1k.data
			asi_rx8b1k_valid            => decoded_din_valid,                                 --           .valid
			asi_rx8b1k_error            => decoded_din_error,                                 --           .error
			asi_rx8b1k_channel          => decoded_din_channel,                               --           .channel
			aso_hit_type0_startofpacket => mutrig_frame_deassembly_0_hit_type0_startofpacket, --  hit_type0.startofpacket
			aso_hit_type0_endofpacket   => mutrig_frame_deassembly_0_hit_type0_endofpacket,   --           .endofpacket
			aso_hit_type0_endofrun      => open,                                              --           .endofrun
			aso_hit_type0_error         => mutrig_frame_deassembly_0_hit_type0_error,         --           .error
			aso_hit_type0_data          => mutrig_frame_deassembly_0_hit_type0_data,          --           .data
			aso_hit_type0_valid         => mutrig_frame_deassembly_0_hit_type0_valid,         --           .valid
			aso_hit_type0_channel       => mutrig_frame_deassembly_0_hit_type0_channel,       --           .channel
			aso_headerinfo_data         => headerinfo_data,                                   -- headerinfo.data
			aso_headerinfo_valid        => headerinfo_valid,                                  --           .valid
			aso_headerinfo_channel      => headerinfo_channel,                                --           .channel
			avs_csr_read                => csr_read,                                          --        csr.read
			avs_csr_readdata            => csr_readdata,                                      --           .readdata
			avs_csr_waitrequest         => csr_waitrequest,                                   --           .waitrequest
			avs_csr_write               => csr_write,                                         --           .write
			avs_csr_writedata           => csr_writedata,                                     --           .writedata
			avs_csr_address             => csr_address,                                       --           .address
			asi_ctrl_data               => run_ctrl_data,                                     --       ctrl.data
			asi_ctrl_valid              => run_ctrl_valid,                                    --           .valid
			asi_ctrl_ready              => run_ctrl_ready,                                    --           .ready
			i_clk                       => clk_clk,                                           -- clock_sink.clk
			i_rst                       => rst_controller_reset_out_reset                     -- reset_sink.reset
		);

	avalon_st_adapter : component mutrig_datapath_system_v3_avalon_st_adapter
		generic map (
			inBitsPerSymbol => 45,
			inUsePackets    => 1,
			inDataWidth     => 45,
			inChannelWidth  => 4,
			inErrorWidth    => 3,
			inUseEmptyPort  => 0,
			inUseValid      => 1,
			inUseReady      => 0,
			inReadyLatency  => 0,
			outDataWidth    => 45,
			outChannelWidth => 4,
			outErrorWidth   => 3,
			outUseEmptyPort => 0,
			outUseValid     => 1,
			outUseReady     => 1,
			outReadyLatency => 0
		)
		port map (
			in_clk_0_clk        => clk_clk,                                           -- in_clk_0.clk
			in_rst_0_reset      => reset_reset_n_ports_inv,                           -- in_rst_0.reset
			in_0_data           => mutrig_frame_deassembly_0_hit_type0_data,          --     in_0.data
			in_0_valid          => mutrig_frame_deassembly_0_hit_type0_valid,         --         .valid
			in_0_startofpacket  => mutrig_frame_deassembly_0_hit_type0_startofpacket, --         .startofpacket
			in_0_endofpacket    => mutrig_frame_deassembly_0_hit_type0_endofpacket,   --         .endofpacket
			in_0_error          => mutrig_frame_deassembly_0_hit_type0_error,         --         .error
			in_0_channel        => mutrig_frame_deassembly_0_hit_type0_channel,       --         .channel
			out_0_data          => avalon_st_adapter_out_0_data,                      --    out_0.data
			out_0_valid         => avalon_st_adapter_out_0_valid,                     --         .valid
			out_0_ready         => avalon_st_adapter_out_0_ready,                     --         .ready
			out_0_startofpacket => avalon_st_adapter_out_0_startofpacket,             --         .startofpacket
			out_0_endofpacket   => avalon_st_adapter_out_0_endofpacket,               --         .endofpacket
			out_0_error         => avalon_st_adapter_out_0_error,                     --         .error
			out_0_channel       => avalon_st_adapter_out_0_channel                    --         .channel
		);

	rst_controller : component altera_reset_controller
		generic map (
			NUM_RESET_INPUTS          => 1,
			OUTPUT_RESET_SYNC_EDGES   => "both",
			SYNC_DEPTH                => 2,
			RESET_REQUEST_PRESENT     => 0,
			RESET_REQ_WAIT_TIME       => 1,
			MIN_RST_ASSERTION_TIME    => 3,
			RESET_REQ_EARLY_DSRT_TIME => 1,
			USE_RESET_REQUEST_IN0     => 0,
			USE_RESET_REQUEST_IN1     => 0,
			USE_RESET_REQUEST_IN2     => 0,
			USE_RESET_REQUEST_IN3     => 0,
			USE_RESET_REQUEST_IN4     => 0,
			USE_RESET_REQUEST_IN5     => 0,
			USE_RESET_REQUEST_IN6     => 0,
			USE_RESET_REQUEST_IN7     => 0,
			USE_RESET_REQUEST_IN8     => 0,
			USE_RESET_REQUEST_IN9     => 0,
			USE_RESET_REQUEST_IN10    => 0,
			USE_RESET_REQUEST_IN11    => 0,
			USE_RESET_REQUEST_IN12    => 0,
			USE_RESET_REQUEST_IN13    => 0,
			USE_RESET_REQUEST_IN14    => 0,
			USE_RESET_REQUEST_IN15    => 0,
			ADAPT_RESET_REQUEST       => 0
		)
		port map (
			reset_in0      => reset_reset_n_ports_inv,        -- reset_in0.reset
			clk            => clk_clk,                        --       clk.clk
			reset_out      => rst_controller_reset_out_reset, -- reset_out.reset
			reset_req      => open,                           -- (terminated)
			reset_req_in0  => '0',                            -- (terminated)
			reset_in1      => '0',                            -- (terminated)
			reset_req_in1  => '0',                            -- (terminated)
			reset_in2      => '0',                            -- (terminated)
			reset_req_in2  => '0',                            -- (terminated)
			reset_in3      => '0',                            -- (terminated)
			reset_req_in3  => '0',                            -- (terminated)
			reset_in4      => '0',                            -- (terminated)
			reset_req_in4  => '0',                            -- (terminated)
			reset_in5      => '0',                            -- (terminated)
			reset_req_in5  => '0',                            -- (terminated)
			reset_in6      => '0',                            -- (terminated)
			reset_req_in6  => '0',                            -- (terminated)
			reset_in7      => '0',                            -- (terminated)
			reset_req_in7  => '0',                            -- (terminated)
			reset_in8      => '0',                            -- (terminated)
			reset_req_in8  => '0',                            -- (terminated)
			reset_in9      => '0',                            -- (terminated)
			reset_req_in9  => '0',                            -- (terminated)
			reset_in10     => '0',                            -- (terminated)
			reset_req_in10 => '0',                            -- (terminated)
			reset_in11     => '0',                            -- (terminated)
			reset_req_in11 => '0',                            -- (terminated)
			reset_in12     => '0',                            -- (terminated)
			reset_req_in12 => '0',                            -- (terminated)
			reset_in13     => '0',                            -- (terminated)
			reset_req_in13 => '0',                            -- (terminated)
			reset_in14     => '0',                            -- (terminated)
			reset_req_in14 => '0',                            -- (terminated)
			reset_in15     => '0',                            -- (terminated)
			reset_req_in15 => '0'                             -- (terminated)
		);

	reset_reset_n_ports_inv <= not reset_reset_n;

end architecture rtl; -- of mutrig_datapath_system_v3
