`ifndef FE_SCIFI_INT_FORMAL_DEFS_SVH
`define FE_SCIFI_INT_FORMAL_DEFS_SVH

`define FORMAL_READY_STALL_MAX 4
`define FORMAL_CMD_LAT_MAX     8
`define FORMAL_ACK_LAT_MAX     8
`define FORMAL_DEADLOCK_BOUND  8
`define FORMAL_RR_STARVATION_BOUND 30
`define FORMAL_PROOF_DEPTH    32
`define FORMAL_COVER_DEPTH    32

`endif
