-- scifi_datapath_system_v3_histogram_statistics_1.vhd

-- Generated using ACDS version 18.1 625

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity scifi_datapath_system_v3_histogram_statistics_1 is
	generic (
		N_BINS                    : natural := 256;
		MAX_COUNT_BITS            : natural := 32;
		DEF_LEFT_BOUND            : integer := -1000;
		DEF_BIN_WIDTH             : natural := 16;
		UPDATE_KEY_BIT_HI         : natural := 29;
		UPDATE_KEY_BIT_LO         : natural := 17;
		UPDATE_KEY_REPRESENTATION : string  := "SIGNED";
		FILTER_KEY_BIT_HI         : natural := 38;
		FILTER_KEY_BIT_LO         : natural := 35;
		SAR_TICK_WIDTH            : natural := 16;
		SAR_KEY_WIDTH             : natural := 16;
		N_PORTS                   : natural := 1;
		CHANNELS_PER_PORT         : natural := 32;
		COAL_QUEUE_DEPTH          : natural := 256;
		AVST_DATA_WIDTH           : natural := 39;
		AVST_CHANNEL_WIDTH        : natural := 4;
		ENABLE_PINGPONG           : boolean := true;
		DEF_INTERVAL_CLOCKS       : natural := 125000000;
		SNOOP_EN                  : boolean := false;
		ENABLE_PACKET             : boolean := false;
		AVS_ADDR_WIDTH            : natural := 8;
		N_DEBUG_INTERFACE         : natural := 6;
		DEBUG                     : natural := 0;
		VERSION_MAJOR             : natural := 26;
		VERSION_MINOR             : natural := 0;
		VERSION_PATCH             : natural := 0;
		BUILD                     : natural := 0;
		IP_UID                    : natural := 1212765012;
		VERSION_DATE              : natural := 20260416;
		VERSION_GIT               : natural := 72231161;
		INSTANCE_ID               : natural := 0
	);
	port (
		i_clk                           : in  std_logic                     := '0';             --          clock.clk
		i_rst                           : in  std_logic                     := '0';             --          reset.reset
		i_interval_reset                : in  std_logic                     := '0';             -- interval_reset.reset
		avs_hist_bin_address            : in  std_logic_vector(7 downto 0)  := (others => '0'); --       hist_bin.address
		avs_hist_bin_read               : in  std_logic                     := '0';             --               .read
		avs_hist_bin_write              : in  std_logic                     := '0';             --               .write
		avs_hist_bin_writedata          : in  std_logic_vector(31 downto 0) := (others => '0'); --               .writedata
		avs_hist_bin_readdata           : out std_logic_vector(31 downto 0);                    --               .readdata
		avs_hist_bin_readdatavalid      : out std_logic;                                        --               .readdatavalid
		avs_hist_bin_waitrequest        : out std_logic;                                        --               .waitrequest
		avs_hist_bin_burstcount         : in  std_logic_vector(8 downto 0)  := (others => '0'); --               .burstcount
		avs_hist_bin_response           : out std_logic_vector(1 downto 0);                     --               .response
		avs_hist_bin_writeresponsevalid : out std_logic;                                        --               .writeresponsevalid
		avs_csr_address                 : in  std_logic_vector(4 downto 0)  := (others => '0'); --            csr.address
		avs_csr_read                    : in  std_logic                     := '0';             --               .read
		avs_csr_write                   : in  std_logic                     := '0';             --               .write
		avs_csr_writedata               : in  std_logic_vector(31 downto 0) := (others => '0'); --               .writedata
		avs_csr_readdata                : out std_logic_vector(31 downto 0);                    --               .readdata
		avs_csr_waitrequest             : out std_logic;                                        --               .waitrequest
		asi_ctrl_data                   : in  std_logic_vector(8 downto 0)  := (others => '0'); --           ctrl.data
		asi_ctrl_valid                  : in  std_logic                     := '0';             --               .valid
		asi_ctrl_ready                  : out std_logic;                                        --               .ready
		asi_hist_fill_in_valid          : in  std_logic                     := '0';             --   hist_fill_in.valid
		asi_hist_fill_in_ready          : out std_logic;                                        --               .ready
		asi_hist_fill_in_data           : in  std_logic_vector(38 downto 0) := (others => '0'); --               .data
		asi_hist_fill_in_startofpacket  : in  std_logic                     := '0';             --               .startofpacket
		asi_hist_fill_in_endofpacket    : in  std_logic                     := '0';             --               .endofpacket
		asi_hist_fill_in_channel        : in  std_logic_vector(3 downto 0)  := (others => '0'); --               .channel
		aso_hist_fill_out_valid         : out std_logic;                                        --       fill_out.valid
		aso_hist_fill_out_ready         : in  std_logic                     := '0';             --               .ready
		aso_hist_fill_out_data          : out std_logic_vector(38 downto 0);                    --               .data
		aso_hist_fill_out_startofpacket : out std_logic;                                        --               .startofpacket
		aso_hist_fill_out_endofpacket   : out std_logic;                                        --               .endofpacket
		aso_hist_fill_out_channel       : out std_logic_vector(3 downto 0);                     --               .channel
		asi_debug_1_valid               : in  std_logic                     := '0';             --        debug_1.valid
		asi_debug_1_data                : in  std_logic_vector(15 downto 0) := (others => '0'); --               .data
		asi_debug_2_valid               : in  std_logic                     := '0';             --        debug_2.valid
		asi_debug_2_data                : in  std_logic_vector(15 downto 0) := (others => '0'); --               .data
		asi_debug_3_valid               : in  std_logic                     := '0';             --        debug_3.valid
		asi_debug_3_data                : in  std_logic_vector(15 downto 0) := (others => '0'); --               .data
		asi_debug_4_valid               : in  std_logic                     := '0';             --        debug_4.valid
		asi_debug_4_data                : in  std_logic_vector(15 downto 0) := (others => '0'); --               .data
		asi_debug_5_valid               : in  std_logic                     := '0';             --        debug_5.valid
		asi_debug_5_data                : in  std_logic_vector(15 downto 0) := (others => '0'); --               .data
		asi_debug_6_valid               : in  std_logic                     := '0';             --        debug_6.valid
		asi_debug_6_data                : in  std_logic_vector(15 downto 0) := (others => '0'); --               .data
		asi_fill_in_1_channel           : in  std_logic_vector(3 downto 0)  := (others => '0');
		asi_fill_in_1_data              : in  std_logic_vector(38 downto 0) := (others => '0');
		asi_fill_in_1_endofpacket       : in  std_logic                     := '0';
		asi_fill_in_1_ready             : out std_logic;
		asi_fill_in_1_startofpacket     : in  std_logic                     := '0';
		asi_fill_in_1_valid             : in  std_logic                     := '0';
		asi_fill_in_2_channel           : in  std_logic_vector(3 downto 0)  := (others => '0');
		asi_fill_in_2_data              : in  std_logic_vector(38 downto 0) := (others => '0');
		asi_fill_in_2_endofpacket       : in  std_logic                     := '0';
		asi_fill_in_2_ready             : out std_logic;
		asi_fill_in_2_startofpacket     : in  std_logic                     := '0';
		asi_fill_in_2_valid             : in  std_logic                     := '0';
		asi_fill_in_3_channel           : in  std_logic_vector(3 downto 0)  := (others => '0');
		asi_fill_in_3_data              : in  std_logic_vector(38 downto 0) := (others => '0');
		asi_fill_in_3_endofpacket       : in  std_logic                     := '0';
		asi_fill_in_3_ready             : out std_logic;
		asi_fill_in_3_startofpacket     : in  std_logic                     := '0';
		asi_fill_in_3_valid             : in  std_logic                     := '0';
		asi_fill_in_4_channel           : in  std_logic_vector(3 downto 0)  := (others => '0');
		asi_fill_in_4_data              : in  std_logic_vector(38 downto 0) := (others => '0');
		asi_fill_in_4_endofpacket       : in  std_logic                     := '0';
		asi_fill_in_4_ready             : out std_logic;
		asi_fill_in_4_startofpacket     : in  std_logic                     := '0';
		asi_fill_in_4_valid             : in  std_logic                     := '0';
		asi_fill_in_5_channel           : in  std_logic_vector(3 downto 0)  := (others => '0');
		asi_fill_in_5_data              : in  std_logic_vector(38 downto 0) := (others => '0');
		asi_fill_in_5_endofpacket       : in  std_logic                     := '0';
		asi_fill_in_5_ready             : out std_logic;
		asi_fill_in_5_startofpacket     : in  std_logic                     := '0';
		asi_fill_in_5_valid             : in  std_logic                     := '0';
		asi_fill_in_6_channel           : in  std_logic_vector(3 downto 0)  := (others => '0');
		asi_fill_in_6_data              : in  std_logic_vector(38 downto 0) := (others => '0');
		asi_fill_in_6_endofpacket       : in  std_logic                     := '0';
		asi_fill_in_6_ready             : out std_logic;
		asi_fill_in_6_startofpacket     : in  std_logic                     := '0';
		asi_fill_in_6_valid             : in  std_logic                     := '0';
		asi_fill_in_7_channel           : in  std_logic_vector(3 downto 0)  := (others => '0');
		asi_fill_in_7_data              : in  std_logic_vector(38 downto 0) := (others => '0');
		asi_fill_in_7_endofpacket       : in  std_logic                     := '0';
		asi_fill_in_7_ready             : out std_logic;
		asi_fill_in_7_startofpacket     : in  std_logic                     := '0';
		asi_fill_in_7_valid             : in  std_logic                     := '0'
	);
end entity scifi_datapath_system_v3_histogram_statistics_1;

architecture rtl of scifi_datapath_system_v3_histogram_statistics_1 is
	component histogram_statistics_v2 is
		generic (
			N_BINS                    : natural := 256;
			MAX_COUNT_BITS            : natural := 32;
			DEF_LEFT_BOUND            : integer := -1000;
			DEF_BIN_WIDTH             : natural := 16;
			UPDATE_KEY_BIT_HI         : natural := 29;
			UPDATE_KEY_BIT_LO         : natural := 17;
			UPDATE_KEY_REPRESENTATION : string  := "UNSIGNED";
			FILTER_KEY_BIT_HI         : natural := 38;
			FILTER_KEY_BIT_LO         : natural := 35;
			SAR_TICK_WIDTH            : natural := 32;
			SAR_KEY_WIDTH             : natural := 16;
			N_PORTS                   : natural := 8;
			CHANNELS_PER_PORT         : natural := 32;
			COAL_QUEUE_DEPTH          : natural := 256;
			AVST_DATA_WIDTH           : natural := 39;
			AVST_CHANNEL_WIDTH        : natural := 4;
			ENABLE_PINGPONG           : boolean := true;
			DEF_INTERVAL_CLOCKS       : natural := 125000000;
			SNOOP_EN                  : boolean := true;
			ENABLE_PACKET             : boolean := true;
			AVS_ADDR_WIDTH            : natural := 8;
			N_DEBUG_INTERFACE         : natural := 6;
			DEBUG                     : natural := 0;
			VERSION_MAJOR             : natural := 26;
			VERSION_MINOR             : natural := 1;
			VERSION_PATCH             : natural := 1;
			BUILD                     : natural := 416;
			IP_UID                    : natural := 1212765012;
			VERSION_DATE              : natural := 20260416;
			VERSION_GIT               : natural := 72231161;
			INSTANCE_ID               : natural := 0
		);
		port (
			i_clk                           : in  std_logic                     := 'X';             -- clk
			i_rst                           : in  std_logic                     := 'X';             -- reset
			i_interval_reset                : in  std_logic                     := 'X';             -- reset
			avs_hist_bin_address            : in  std_logic_vector(7 downto 0)  := (others => 'X'); -- address
			avs_hist_bin_read               : in  std_logic                     := 'X';             -- read
			avs_hist_bin_write              : in  std_logic                     := 'X';             -- write
			avs_hist_bin_writedata          : in  std_logic_vector(31 downto 0) := (others => 'X'); -- writedata
			avs_hist_bin_readdata           : out std_logic_vector(31 downto 0);                    -- readdata
			avs_hist_bin_readdatavalid      : out std_logic;                                        -- readdatavalid
			avs_hist_bin_waitrequest        : out std_logic;                                        -- waitrequest
			avs_hist_bin_burstcount         : in  std_logic_vector(8 downto 0)  := (others => 'X'); -- burstcount
			avs_hist_bin_response           : out std_logic_vector(1 downto 0);                     -- response
			avs_hist_bin_writeresponsevalid : out std_logic;                                        -- writeresponsevalid
			avs_csr_address                 : in  std_logic_vector(4 downto 0)  := (others => 'X'); -- address
			avs_csr_read                    : in  std_logic                     := 'X';             -- read
			avs_csr_write                   : in  std_logic                     := 'X';             -- write
			avs_csr_writedata               : in  std_logic_vector(31 downto 0) := (others => 'X'); -- writedata
			avs_csr_readdata                : out std_logic_vector(31 downto 0);                    -- readdata
			avs_csr_waitrequest             : out std_logic;                                        -- waitrequest
			asi_ctrl_data                   : in  std_logic_vector(8 downto 0)  := (others => 'X'); -- data
			asi_ctrl_valid                  : in  std_logic                     := 'X';             -- valid
			asi_ctrl_ready                  : out std_logic;                                        -- ready
			asi_hist_fill_in_valid          : in  std_logic                     := 'X';             -- valid
			asi_hist_fill_in_ready          : out std_logic;                                        -- ready
			asi_hist_fill_in_data           : in  std_logic_vector(38 downto 0) := (others => 'X'); -- data
			asi_hist_fill_in_startofpacket  : in  std_logic                     := 'X';             -- startofpacket
			asi_hist_fill_in_endofpacket    : in  std_logic                     := 'X';             -- endofpacket
			asi_hist_fill_in_channel        : in  std_logic_vector(3 downto 0)  := (others => 'X'); -- channel
			aso_hist_fill_out_valid         : out std_logic;                                        -- valid
			aso_hist_fill_out_ready         : in  std_logic                     := 'X';             -- ready
			aso_hist_fill_out_data          : out std_logic_vector(38 downto 0);                    -- data
			aso_hist_fill_out_startofpacket : out std_logic;                                        -- startofpacket
			aso_hist_fill_out_endofpacket   : out std_logic;                                        -- endofpacket
			aso_hist_fill_out_channel       : out std_logic_vector(3 downto 0);                     -- channel
			asi_debug_1_valid               : in  std_logic                     := 'X';             -- valid
			asi_debug_1_data                : in  std_logic_vector(15 downto 0) := (others => 'X'); -- data
			asi_debug_2_valid               : in  std_logic                     := 'X';             -- valid
			asi_debug_2_data                : in  std_logic_vector(15 downto 0) := (others => 'X'); -- data
			asi_debug_3_valid               : in  std_logic                     := 'X';             -- valid
			asi_debug_3_data                : in  std_logic_vector(15 downto 0) := (others => 'X'); -- data
			asi_debug_4_valid               : in  std_logic                     := 'X';             -- valid
			asi_debug_4_data                : in  std_logic_vector(15 downto 0) := (others => 'X'); -- data
			asi_debug_5_valid               : in  std_logic                     := 'X';             -- valid
			asi_debug_5_data                : in  std_logic_vector(15 downto 0) := (others => 'X'); -- data
			asi_debug_6_valid               : in  std_logic                     := 'X';             -- valid
			asi_debug_6_data                : in  std_logic_vector(15 downto 0) := (others => 'X'); -- data
			asi_fill_in_1_valid             : in  std_logic                     := 'X';             -- valid
			asi_fill_in_1_ready             : out std_logic;                                        -- ready
			asi_fill_in_1_data              : in  std_logic_vector(38 downto 0) := (others => 'X'); -- data
			asi_fill_in_1_startofpacket     : in  std_logic                     := 'X';             -- startofpacket
			asi_fill_in_1_endofpacket       : in  std_logic                     := 'X';             -- endofpacket
			asi_fill_in_1_channel           : in  std_logic_vector(3 downto 0)  := (others => 'X'); -- channel
			asi_fill_in_2_valid             : in  std_logic                     := 'X';             -- valid
			asi_fill_in_2_ready             : out std_logic;                                        -- ready
			asi_fill_in_2_data              : in  std_logic_vector(38 downto 0) := (others => 'X'); -- data
			asi_fill_in_2_startofpacket     : in  std_logic                     := 'X';             -- startofpacket
			asi_fill_in_2_endofpacket       : in  std_logic                     := 'X';             -- endofpacket
			asi_fill_in_2_channel           : in  std_logic_vector(3 downto 0)  := (others => 'X'); -- channel
			asi_fill_in_3_valid             : in  std_logic                     := 'X';             -- valid
			asi_fill_in_3_ready             : out std_logic;                                        -- ready
			asi_fill_in_3_data              : in  std_logic_vector(38 downto 0) := (others => 'X'); -- data
			asi_fill_in_3_startofpacket     : in  std_logic                     := 'X';             -- startofpacket
			asi_fill_in_3_endofpacket       : in  std_logic                     := 'X';             -- endofpacket
			asi_fill_in_3_channel           : in  std_logic_vector(3 downto 0)  := (others => 'X'); -- channel
			asi_fill_in_4_valid             : in  std_logic                     := 'X';             -- valid
			asi_fill_in_4_ready             : out std_logic;                                        -- ready
			asi_fill_in_4_data              : in  std_logic_vector(38 downto 0) := (others => 'X'); -- data
			asi_fill_in_4_startofpacket     : in  std_logic                     := 'X';             -- startofpacket
			asi_fill_in_4_endofpacket       : in  std_logic                     := 'X';             -- endofpacket
			asi_fill_in_4_channel           : in  std_logic_vector(3 downto 0)  := (others => 'X'); -- channel
			asi_fill_in_5_valid             : in  std_logic                     := 'X';             -- valid
			asi_fill_in_5_ready             : out std_logic;                                        -- ready
			asi_fill_in_5_data              : in  std_logic_vector(38 downto 0) := (others => 'X'); -- data
			asi_fill_in_5_startofpacket     : in  std_logic                     := 'X';             -- startofpacket
			asi_fill_in_5_endofpacket       : in  std_logic                     := 'X';             -- endofpacket
			asi_fill_in_5_channel           : in  std_logic_vector(3 downto 0)  := (others => 'X'); -- channel
			asi_fill_in_6_valid             : in  std_logic                     := 'X';             -- valid
			asi_fill_in_6_ready             : out std_logic;                                        -- ready
			asi_fill_in_6_data              : in  std_logic_vector(38 downto 0) := (others => 'X'); -- data
			asi_fill_in_6_startofpacket     : in  std_logic                     := 'X';             -- startofpacket
			asi_fill_in_6_endofpacket       : in  std_logic                     := 'X';             -- endofpacket
			asi_fill_in_6_channel           : in  std_logic_vector(3 downto 0)  := (others => 'X'); -- channel
			asi_fill_in_7_valid             : in  std_logic                     := 'X';             -- valid
			asi_fill_in_7_ready             : out std_logic;                                        -- ready
			asi_fill_in_7_data              : in  std_logic_vector(38 downto 0) := (others => 'X'); -- data
			asi_fill_in_7_startofpacket     : in  std_logic                     := 'X';             -- startofpacket
			asi_fill_in_7_endofpacket       : in  std_logic                     := 'X';             -- endofpacket
			asi_fill_in_7_channel           : in  std_logic_vector(3 downto 0)  := (others => 'X')  -- channel
		);
	end component histogram_statistics_v2;

begin

	n_bins_check : if N_BINS /= 256 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	max_count_bits_check : if MAX_COUNT_BITS /= 32 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	def_left_bound_check : if DEF_LEFT_BOUND /= -1000 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	def_bin_width_check : if DEF_BIN_WIDTH /= 16 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	update_key_bit_hi_check : if UPDATE_KEY_BIT_HI /= 29 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	update_key_bit_lo_check : if UPDATE_KEY_BIT_LO /= 17 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	update_key_representation_check : if UPDATE_KEY_REPRESENTATION /= "SIGNED" generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	filter_key_bit_hi_check : if FILTER_KEY_BIT_HI /= 38 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	filter_key_bit_lo_check : if FILTER_KEY_BIT_LO /= 35 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	sar_tick_width_check : if SAR_TICK_WIDTH /= 16 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	sar_key_width_check : if SAR_KEY_WIDTH /= 16 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	n_ports_check : if N_PORTS /= 1 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	channels_per_port_check : if CHANNELS_PER_PORT /= 32 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	coal_queue_depth_check : if COAL_QUEUE_DEPTH /= 256 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	avst_data_width_check : if AVST_DATA_WIDTH /= 39 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	avst_channel_width_check : if AVST_CHANNEL_WIDTH /= 4 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	enable_pingpong_check : if ENABLE_PINGPONG /= true generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	def_interval_clocks_check : if DEF_INTERVAL_CLOCKS /= 125000000 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	snoop_en_check : if SNOOP_EN /= false generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	enable_packet_check : if ENABLE_PACKET /= false generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	avs_addr_width_check : if AVS_ADDR_WIDTH /= 8 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	n_debug_interface_check : if N_DEBUG_INTERFACE /= 6 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	debug_check : if DEBUG /= 0 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	version_major_check : if VERSION_MAJOR /= 26 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	version_minor_check : if VERSION_MINOR /= 0 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	version_patch_check : if VERSION_PATCH /= 0 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	build_check : if BUILD /= 0 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	ip_uid_check : if IP_UID /= 1212765012 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	version_date_check : if VERSION_DATE /= 20260416 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	version_git_check : if VERSION_GIT /= 72231161 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	instance_id_check : if INSTANCE_ID /= 0 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	histogram_statistics_1 : component histogram_statistics_v2
		generic map (
			N_BINS                    => 256,
			MAX_COUNT_BITS            => 32,
			DEF_LEFT_BOUND            => -1000,
			DEF_BIN_WIDTH             => 16,
			UPDATE_KEY_BIT_HI         => 29,
			UPDATE_KEY_BIT_LO         => 17,
			UPDATE_KEY_REPRESENTATION => "SIGNED",
			FILTER_KEY_BIT_HI         => 38,
			FILTER_KEY_BIT_LO         => 35,
			SAR_TICK_WIDTH            => 16,
			SAR_KEY_WIDTH             => 16,
			N_PORTS                   => 1,
			CHANNELS_PER_PORT         => 32,
			COAL_QUEUE_DEPTH          => 256,
			AVST_DATA_WIDTH           => 39,
			AVST_CHANNEL_WIDTH        => 4,
			ENABLE_PINGPONG           => true,
			DEF_INTERVAL_CLOCKS       => 125000000,
			SNOOP_EN                  => false,
			ENABLE_PACKET             => false,
			AVS_ADDR_WIDTH            => 8,
			N_DEBUG_INTERFACE         => 6,
			DEBUG                     => 0,
			VERSION_MAJOR             => 26,
			VERSION_MINOR             => 0,
			VERSION_PATCH             => 0,
			BUILD                     => 0,
			IP_UID                    => 1212765012,
			VERSION_DATE              => 20260416,
			VERSION_GIT               => 72231161,
			INSTANCE_ID               => 0
		)
		port map (
			i_clk                           => i_clk,                                     --          clock.clk
			i_rst                           => i_rst,                                     --          reset.reset
			i_interval_reset                => i_interval_reset,                          -- interval_reset.reset
			avs_hist_bin_address            => avs_hist_bin_address,                      --       hist_bin.address
			avs_hist_bin_read               => avs_hist_bin_read,                         --               .read
			avs_hist_bin_write              => avs_hist_bin_write,                        --               .write
			avs_hist_bin_writedata          => avs_hist_bin_writedata,                    --               .writedata
			avs_hist_bin_readdata           => avs_hist_bin_readdata,                     --               .readdata
			avs_hist_bin_readdatavalid      => avs_hist_bin_readdatavalid,                --               .readdatavalid
			avs_hist_bin_waitrequest        => avs_hist_bin_waitrequest,                  --               .waitrequest
			avs_hist_bin_burstcount         => avs_hist_bin_burstcount,                   --               .burstcount
			avs_hist_bin_response           => avs_hist_bin_response,                     --               .response
			avs_hist_bin_writeresponsevalid => avs_hist_bin_writeresponsevalid,           --               .writeresponsevalid
			avs_csr_address                 => avs_csr_address,                           --            csr.address
			avs_csr_read                    => avs_csr_read,                              --               .read
			avs_csr_write                   => avs_csr_write,                             --               .write
			avs_csr_writedata               => avs_csr_writedata,                         --               .writedata
			avs_csr_readdata                => avs_csr_readdata,                          --               .readdata
			avs_csr_waitrequest             => avs_csr_waitrequest,                       --               .waitrequest
			asi_ctrl_data                   => asi_ctrl_data,                             --           ctrl.data
			asi_ctrl_valid                  => asi_ctrl_valid,                            --               .valid
			asi_ctrl_ready                  => asi_ctrl_ready,                            --               .ready
			asi_hist_fill_in_valid          => asi_hist_fill_in_valid,                    --   hist_fill_in.valid
			asi_hist_fill_in_ready          => asi_hist_fill_in_ready,                    --               .ready
			asi_hist_fill_in_data           => asi_hist_fill_in_data,                     --               .data
			asi_hist_fill_in_startofpacket  => asi_hist_fill_in_startofpacket,            --               .startofpacket
			asi_hist_fill_in_endofpacket    => asi_hist_fill_in_endofpacket,              --               .endofpacket
			asi_hist_fill_in_channel        => asi_hist_fill_in_channel,                  --               .channel
			aso_hist_fill_out_valid         => aso_hist_fill_out_valid,                   --       fill_out.valid
			aso_hist_fill_out_ready         => aso_hist_fill_out_ready,                   --               .ready
			aso_hist_fill_out_data          => aso_hist_fill_out_data,                    --               .data
			aso_hist_fill_out_startofpacket => aso_hist_fill_out_startofpacket,           --               .startofpacket
			aso_hist_fill_out_endofpacket   => aso_hist_fill_out_endofpacket,             --               .endofpacket
			aso_hist_fill_out_channel       => aso_hist_fill_out_channel,                 --               .channel
			asi_debug_1_valid               => asi_debug_1_valid,                         --        debug_1.valid
			asi_debug_1_data                => asi_debug_1_data,                          --               .data
			asi_debug_2_valid               => asi_debug_2_valid,                         --        debug_2.valid
			asi_debug_2_data                => asi_debug_2_data,                          --               .data
			asi_debug_3_valid               => asi_debug_3_valid,                         --        debug_3.valid
			asi_debug_3_data                => asi_debug_3_data,                          --               .data
			asi_debug_4_valid               => asi_debug_4_valid,                         --        debug_4.valid
			asi_debug_4_data                => asi_debug_4_data,                          --               .data
			asi_debug_5_valid               => asi_debug_5_valid,                         --        debug_5.valid
			asi_debug_5_data                => asi_debug_5_data,                          --               .data
			asi_debug_6_valid               => asi_debug_6_valid,                         --        debug_6.valid
			asi_debug_6_data                => asi_debug_6_data,                          --               .data
			asi_fill_in_1_valid             => '0',                                       --    (terminated)
			asi_fill_in_1_ready             => open,                                      --    (terminated)
			asi_fill_in_1_data              => "000000000000000000000000000000000000000", --    (terminated)
			asi_fill_in_1_startofpacket     => '0',                                       --    (terminated)
			asi_fill_in_1_endofpacket       => '0',                                       --    (terminated)
			asi_fill_in_1_channel           => "0000",                                    --    (terminated)
			asi_fill_in_2_valid             => '0',                                       --    (terminated)
			asi_fill_in_2_ready             => open,                                      --    (terminated)
			asi_fill_in_2_data              => "000000000000000000000000000000000000000", --    (terminated)
			asi_fill_in_2_startofpacket     => '0',                                       --    (terminated)
			asi_fill_in_2_endofpacket       => '0',                                       --    (terminated)
			asi_fill_in_2_channel           => "0000",                                    --    (terminated)
			asi_fill_in_3_valid             => '0',                                       --    (terminated)
			asi_fill_in_3_ready             => open,                                      --    (terminated)
			asi_fill_in_3_data              => "000000000000000000000000000000000000000", --    (terminated)
			asi_fill_in_3_startofpacket     => '0',                                       --    (terminated)
			asi_fill_in_3_endofpacket       => '0',                                       --    (terminated)
			asi_fill_in_3_channel           => "0000",                                    --    (terminated)
			asi_fill_in_4_valid             => '0',                                       --    (terminated)
			asi_fill_in_4_ready             => open,                                      --    (terminated)
			asi_fill_in_4_data              => "000000000000000000000000000000000000000", --    (terminated)
			asi_fill_in_4_startofpacket     => '0',                                       --    (terminated)
			asi_fill_in_4_endofpacket       => '0',                                       --    (terminated)
			asi_fill_in_4_channel           => "0000",                                    --    (terminated)
			asi_fill_in_5_valid             => '0',                                       --    (terminated)
			asi_fill_in_5_ready             => open,                                      --    (terminated)
			asi_fill_in_5_data              => "000000000000000000000000000000000000000", --    (terminated)
			asi_fill_in_5_startofpacket     => '0',                                       --    (terminated)
			asi_fill_in_5_endofpacket       => '0',                                       --    (terminated)
			asi_fill_in_5_channel           => "0000",                                    --    (terminated)
			asi_fill_in_6_valid             => '0',                                       --    (terminated)
			asi_fill_in_6_ready             => open,                                      --    (terminated)
			asi_fill_in_6_data              => "000000000000000000000000000000000000000", --    (terminated)
			asi_fill_in_6_startofpacket     => '0',                                       --    (terminated)
			asi_fill_in_6_endofpacket       => '0',                                       --    (terminated)
			asi_fill_in_6_channel           => "0000",                                    --    (terminated)
			asi_fill_in_7_valid             => '0',                                       --    (terminated)
			asi_fill_in_7_ready             => open,                                      --    (terminated)
			asi_fill_in_7_data              => "000000000000000000000000000000000000000", --    (terminated)
			asi_fill_in_7_startofpacket     => '0',                                       --    (terminated)
			asi_fill_in_7_endofpacket       => '0',                                       --    (terminated)
			asi_fill_in_7_channel           => "0000"                                     --    (terminated)
		);

end architecture rtl; -- of scifi_datapath_system_v3_histogram_statistics_1
