// File name: ring_buffer_cam.sv
// Author  : Yifeng Wang (yifenwan@phys.ethz.ch), Codex migration
// Version : 26.2.10
// Date    : 20260507
// Change  : propagate the metadata-preserving rbCAM core defaults

module ring_buffer_cam #(
  parameter int SEARCH_KEY_WIDTH    = 8,
  parameter int RING_BUFFER_N_ENTRY = 512,
  parameter int SIDE_DATA_BITS      = 31,
  parameter int INTERLEAVING_FACTOR = 4,
  parameter int INTERLEAVING_INDEX  = 0,
  parameter int N_PARTITIONS        = 4,
  parameter int ENCODER_LEAF_WIDTH  = 16,
  parameter int ENCODER_PIPE_STAGES = 4,
  parameter int IP_UID              = 32'h5242_434d,
  parameter int VERSION_MAJOR       = 26,
  parameter int VERSION_MINOR       = 2,
  parameter int VERSION_PATCH       = 10,
  parameter int BUILD               = 507,
  parameter int VERSION_DATE        = 20260507,
  parameter int VERSION_GIT         = 0,
  parameter int INSTANCE_ID         = 0,
  parameter int DEBUG               = 1
) (
  output logic [31:0] avs_csr_readdata,
  input  logic        avs_csr_read,
  input  logic [4:0]  avs_csr_address,
  output logic        avs_csr_waitrequest,
  input  logic        avs_csr_write,
  input  logic [31:0] avs_csr_writedata,
  input  logic [3:0]  asi_hit_type1_channel,
  input  logic        asi_hit_type1_startofpacket,
  input  logic        asi_hit_type1_endofpacket,
  input  logic        asi_hit_type1_empty,
  input  logic [38:0] asi_hit_type1_data,
  input  logic        asi_hit_type1_valid,
  output logic        asi_hit_type1_ready,
  input  logic [0:0]  asi_hit_type1_error,
  input  logic [63:0] asi_hit_type1_metadata,
  input  logic        asi_hit_type1_metadata_valid,
  output logic [3:0]  aso_hit_type2_channel,
  output logic        aso_hit_type2_startofpacket,
  output logic        aso_hit_type2_endofpacket,
  output logic [35:0] aso_hit_type2_data,
  output logic        aso_hit_type2_valid,
  input  logic        aso_hit_type2_ready,
  output logic [0:0]  aso_hit_type2_error,
  output logic [63:0] aso_hit_type2_metadata,
  output logic        aso_hit_type2_metadata_valid,
  input  logic        i_clk,
  input  logic        i_rst,
  input  logic [8:0]  asi_ctrl_data,
  input  logic        asi_ctrl_valid,
  output logic        asi_ctrl_ready,
  output logic [15:0] aso_filllevel_data,
  output logic        aso_filllevel_valid,
  output logic [31:0] coe_debug_fill_level,
  output logic [31:0] coe_debug_fifo_level,
  output logic [31:0] coe_debug_queue_state
);
  ring_buffer_cam_core #(
    .SEARCH_KEY_WIDTH    (SEARCH_KEY_WIDTH),
    .RING_BUFFER_N_ENTRY (RING_BUFFER_N_ENTRY),
    .SIDE_DATA_BITS      (SIDE_DATA_BITS),
    .INTERLEAVING_FACTOR (INTERLEAVING_FACTOR),
    .INTERLEAVING_INDEX  (INTERLEAVING_INDEX),
    .N_PARTITIONS        (N_PARTITIONS),
    .ENCODER_LEAF_WIDTH  (ENCODER_LEAF_WIDTH),
    .ENCODER_PIPE_STAGES (ENCODER_PIPE_STAGES),
    .IP_UID              (IP_UID),
    .VERSION_MAJOR       (VERSION_MAJOR),
    .VERSION_MINOR       (VERSION_MINOR),
    .VERSION_PATCH       (VERSION_PATCH),
    .BUILD               (BUILD),
    .VERSION_DATE        (VERSION_DATE),
    .VERSION_GIT         (VERSION_GIT),
    .INSTANCE_ID         (INSTANCE_ID),
    .DEBUG               (DEBUG)
  ) v2_core (
    .avs_csr_readdata            (avs_csr_readdata),
    .avs_csr_read                (avs_csr_read),
    .avs_csr_address             (avs_csr_address),
    .avs_csr_waitrequest         (avs_csr_waitrequest),
    .avs_csr_write               (avs_csr_write),
    .avs_csr_writedata           (avs_csr_writedata),
    .asi_ctrl_data               (asi_ctrl_data),
    .asi_ctrl_valid              (asi_ctrl_valid),
    .asi_ctrl_ready              (asi_ctrl_ready),
    .asi_hit_type1_channel       (asi_hit_type1_channel),
    .asi_hit_type1_startofpacket (asi_hit_type1_startofpacket),
    .asi_hit_type1_endofpacket   (asi_hit_type1_endofpacket),
    .asi_hit_type1_empty         (asi_hit_type1_empty),
    .asi_hit_type1_data          (asi_hit_type1_data),
    .asi_hit_type1_valid         (asi_hit_type1_valid),
    .asi_hit_type1_ready         (asi_hit_type1_ready),
    .asi_hit_type1_error         (asi_hit_type1_error),
    .asi_hit_type1_metadata      (asi_hit_type1_metadata),
    .asi_hit_type1_metadata_valid(asi_hit_type1_metadata_valid),
    .aso_hit_type2_channel       (aso_hit_type2_channel),
    .aso_hit_type2_startofpacket (aso_hit_type2_startofpacket),
    .aso_hit_type2_endofpacket   (aso_hit_type2_endofpacket),
    .aso_hit_type2_data          (aso_hit_type2_data),
    .aso_hit_type2_valid         (aso_hit_type2_valid),
    .aso_hit_type2_ready         (aso_hit_type2_ready),
    .aso_hit_type2_error         (aso_hit_type2_error),
    .aso_hit_type2_metadata      (aso_hit_type2_metadata),
    .aso_hit_type2_metadata_valid(aso_hit_type2_metadata_valid),
    .aso_filllevel_valid         (aso_filllevel_valid),
    .aso_filllevel_data          (aso_filllevel_data),
    .coe_debug_fill_level        (coe_debug_fill_level),
    .coe_debug_fifo_level        (coe_debug_fifo_level),
    .coe_debug_queue_state       (coe_debug_queue_state),
    .i_rst                       (i_rst),
    .i_clk                       (i_clk)
  );
endmodule
