onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tile_sorter_tb/i_reset_n
add wave -noupdate /tile_sorter_tb/i_clk
add wave -noupdate /tile_sorter_tb/i_running
add wave -noupdate /tile_sorter_tb/i_currentts
add wave -noupdate -expand /tile_sorter_tb/i_hit
add wave -noupdate /tile_sorter_tb/i_clk156
add wave -noupdate /tile_sorter_tb/i_reset_n_regs
add wave -noupdate /tile_sorter_tb/i_reg_add
add wave -noupdate /tile_sorter_tb/i_reg_re
add wave -noupdate /tile_sorter_tb/o_reg_rdata
add wave -noupdate /tile_sorter_tb/i_reg_we
add wave -noupdate /tile_sorter_tb/i_reg_wdata
add wave -noupdate /tile_sorter_tb/i_dut/running_last
add wave -noupdate /tile_sorter_tb/i_dut/running_read
add wave -noupdate /tile_sorter_tb/i_dut/running_read_last
add wave -noupdate /tile_sorter_tb/i_dut/running_read_last2
add wave -noupdate /tile_sorter_tb/i_dut/running_seq
add wave -noupdate /tile_sorter_tb/i_dut/tslow
add wave -noupdate /tile_sorter_tb/i_dut/tshi
add wave -noupdate /tile_sorter_tb/i_dut/tsread
add wave -noupdate /tile_sorter_tb/i_dut/tsreadmemdelay
add wave -noupdate /tile_sorter_tb/i_dut/runstartup
add wave -noupdate -radix hexadecimal /tile_sorter_tb/data_out
add wave -noupdate /tile_sorter_tb/out_ena
add wave -noupdate -radix hexadecimal /tile_sorter_tb/out_type
add wave -noupdate /tile_sorter_tb/out_is_hit
add wave -noupdate /tile_sorter_tb/i_dut/runshutdown
add wave -noupdate /tile_sorter_tb/i_dut/runend
add wave -noupdate /tile_sorter_tb/i_dut/hit_last1
add wave -noupdate /tile_sorter_tb/i_dut/hit_last2
add wave -noupdate /tile_sorter_tb/i_dut/hit_last3
add wave -noupdate /tile_sorter_tb/i_dut/tshit
add wave -noupdate /tile_sorter_tb/i_dut/sametsafternext
add wave -noupdate /tile_sorter_tb/i_dut/sametsnext
add wave -noupdate /tile_sorter_tb/i_dut/dcountertemp
add wave -noupdate /tile_sorter_tb/i_dut/dcountertemp2
add wave -noupdate /tile_sorter_tb/i_dut/tomem
add wave -noupdate /tile_sorter_tb/i_dut/frommem
add wave -noupdate /tile_sorter_tb/i_dut/memwren
add wave -noupdate /tile_sorter_tb/i_dut/waddr
add wave -noupdate /tile_sorter_tb/i_dut/raddr
add wave -noupdate /tile_sorter_tb/i_dut/tocmem
add wave -noupdate /tile_sorter_tb/i_dut/tocmem_hitwriter
add wave -noupdate /tile_sorter_tb/i_dut/fromcmem
add wave -noupdate /tile_sorter_tb/i_dut/fromcmem_hitreader
add wave -noupdate /tile_sorter_tb/i_dut/cmemreadaddr
add wave -noupdate /tile_sorter_tb/i_dut/cmemwriteaddr
add wave -noupdate /tile_sorter_tb/i_dut/cmemreadaddr_hitwriter
add wave -noupdate /tile_sorter_tb/i_dut/cmemwriteaddr_hitwriter
add wave -noupdate /tile_sorter_tb/i_dut/cmemreadaddr_hitreader
add wave -noupdate /tile_sorter_tb/i_dut/addrcounterreset
add wave -noupdate /tile_sorter_tb/i_dut/cmemwren
add wave -noupdate /tile_sorter_tb/i_dut/cmemwren_hitwriter
add wave -noupdate /tile_sorter_tb/i_dut/reset
add wave -noupdate /tile_sorter_tb/i_dut/tofifo_counters
add wave -noupdate /tile_sorter_tb/i_dut/fromfifo_counters
add wave -noupdate /tile_sorter_tb/i_dut/read_counterfifo
add wave -noupdate /tile_sorter_tb/i_dut/write_counterfifo
add wave -noupdate /tile_sorter_tb/i_dut/counterfifo_almostfull
add wave -noupdate /tile_sorter_tb/i_dut/counterfifo_empty
add wave -noupdate /tile_sorter_tb/i_dut/block_nonempty_accumulate
add wave -noupdate /tile_sorter_tb/i_dut/block_empty_del2
add wave -noupdate /tile_sorter_tb/i_dut/stopwrite
add wave -noupdate /tile_sorter_tb/i_dut/stopwrite_del1
add wave -noupdate /tile_sorter_tb/i_dut/stopwrite_del2
add wave -noupdate /tile_sorter_tb/i_dut/stopwrite_del3
add wave -noupdate /tile_sorter_tb/i_dut/blockchange
add wave -noupdate /tile_sorter_tb/i_dut/blockchange_del1
add wave -noupdate /tile_sorter_tb/i_dut/blockchange_del2
add wave -noupdate /tile_sorter_tb/i_dut/mem_nnonempty
add wave -noupdate /tile_sorter_tb/i_dut/mem_neinputs
add wave -noupdate /tile_sorter_tb/i_dut/mem_neinputs2
add wave -noupdate /tile_sorter_tb/i_dut/mem_countinputs
add wave -noupdate /tile_sorter_tb/i_dut/mem_countinputs_m1
add wave -noupdate /tile_sorter_tb/i_dut/mem_countinputs_m2
add wave -noupdate /tile_sorter_tb/i_dut/hashits
add wave -noupdate /tile_sorter_tb/i_dut/mem_overflow
add wave -noupdate /tile_sorter_tb/i_dut/mem_overflow_del1
add wave -noupdate /tile_sorter_tb/i_dut/mem_overflow_del2
add wave -noupdate /tile_sorter_tb/i_dut/credits
add wave -noupdate /tile_sorter_tb/i_dut/credits32
add wave -noupdate /tile_sorter_tb/i_dut/credittemp
add wave -noupdate /tile_sorter_tb/i_dut/hitcounter_sum_m3_mem
add wave -noupdate /tile_sorter_tb/i_dut/hitcounter_sum_mem
add wave -noupdate /tile_sorter_tb/i_dut/hitcounter_sum
add wave -noupdate /tile_sorter_tb/i_dut/creditchange_reg
add wave -noupdate /tile_sorter_tb/i_dut/readcommand
add wave -noupdate /tile_sorter_tb/i_dut/readcommand_last1
add wave -noupdate /tile_sorter_tb/i_dut/readcommand_last2
add wave -noupdate /tile_sorter_tb/i_dut/readcommand_last3
add wave -noupdate /tile_sorter_tb/i_dut/readcommand_last4
add wave -noupdate /tile_sorter_tb/i_dut/readcommand_ena
add wave -noupdate /tile_sorter_tb/i_dut/readcommand_ena_last1
add wave -noupdate /tile_sorter_tb/i_dut/readcommand_ena_last2
add wave -noupdate /tile_sorter_tb/i_dut/readcommand_ena_last3
add wave -noupdate /tile_sorter_tb/i_dut/readcommand_ena_last4
add wave -noupdate /tile_sorter_tb/i_dut/outoverflow
add wave -noupdate /tile_sorter_tb/i_dut/overflow_last1
add wave -noupdate /tile_sorter_tb/i_dut/overflow_last2
add wave -noupdate /tile_sorter_tb/i_dut/overflow_last3
add wave -noupdate /tile_sorter_tb/i_dut/overflow_last4
add wave -noupdate /tile_sorter_tb/i_dut/header_counter
add wave -noupdate /tile_sorter_tb/i_dut/subheader_counter
add wave -noupdate /tile_sorter_tb/i_dut/memmultiplex
add wave -noupdate /tile_sorter_tb/i_dut/tscounter
add wave -noupdate /tile_sorter_tb/i_dut/terminate_output
add wave -noupdate /tile_sorter_tb/i_dut/terminated_output
add wave -noupdate /tile_sorter_tb/i_dut/debug_subheadercounter
add wave -noupdate /tile_sorter_tb/i_dut/debug_hitcounter
add wave -noupdate /tile_sorter_tb/i_dut/noutoftime
add wave -noupdate /tile_sorter_tb/i_dut/noverflow
add wave -noupdate /tile_sorter_tb/i_dut/nintime
add wave -noupdate /tile_sorter_tb/i_dut/nout
add wave -noupdate /tile_sorter_tb/i_dut/delay
add wave -noupdate /tile_sorter_tb/i_dut/noutoftime2
add wave -noupdate /tile_sorter_tb/i_dut/noverflow2
add wave -noupdate /tile_sorter_tb/i_dut/nintime2
add wave -noupdate /tile_sorter_tb/i_dut/nout2
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {25808 ns} 0}
quietly wave cursor active 1
configure wave -namecolwidth 244
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ns} {464 ns}
