// debug_sc_system_v3_lvdsctrl_cbb_mm_interconnect_2.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 18.1 625

`timescale 1 ps / 1 ps
module debug_sc_system_v3_lvdsctrl_cbb_mm_interconnect_2 (
		input  wire        clk156_clk_clk,                                    //                                  clk156_clk.clk
		input  wire        sc_hub_cmd_pipe_reset_reset_bridge_in_reset_reset, // sc_hub_cmd_pipe_reset_reset_bridge_in_reset.reset
		input  wire        sc_hub_hub_reset_reset_bridge_in_reset_reset,      //      sc_hub_hub_reset_reset_bridge_in_reset.reset
		input  wire [17:0] sc_hub_hub_address,                                //                                  sc_hub_hub.address
		output wire        sc_hub_hub_waitrequest,                            //                                            .waitrequest
		input  wire [8:0]  sc_hub_hub_burstcount,                             //                                            .burstcount
		input  wire        sc_hub_hub_read,                                   //                                            .read
		output wire [31:0] sc_hub_hub_readdata,                               //                                            .readdata
		output wire        sc_hub_hub_readdatavalid,                          //                                            .readdatavalid
		input  wire        sc_hub_hub_write,                                  //                                            .write
		input  wire [31:0] sc_hub_hub_writedata,                              //                                            .writedata
		output wire [1:0]  sc_hub_hub_response,                               //                                            .response
		output wire        sc_hub_hub_writeresponsevalid,                     //                                            .writeresponsevalid
		output wire [15:0] sc_hub_cmd_pipe_s0_address,                        //                          sc_hub_cmd_pipe_s0.address
		output wire        sc_hub_cmd_pipe_s0_write,                          //                                            .write
		output wire        sc_hub_cmd_pipe_s0_read,                           //                                            .read
		input  wire [31:0] sc_hub_cmd_pipe_s0_readdata,                       //                                            .readdata
		output wire [31:0] sc_hub_cmd_pipe_s0_writedata,                      //                                            .writedata
		output wire [0:0]  sc_hub_cmd_pipe_s0_burstcount,                     //                                            .burstcount
		output wire [3:0]  sc_hub_cmd_pipe_s0_byteenable,                     //                                            .byteenable
		input  wire        sc_hub_cmd_pipe_s0_readdatavalid,                  //                                            .readdatavalid
		input  wire        sc_hub_cmd_pipe_s0_waitrequest,                    //                                            .waitrequest
		output wire        sc_hub_cmd_pipe_s0_debugaccess,                    //                                            .debugaccess
		input  wire [1:0]  sc_hub_cmd_pipe_s0_response                        //                                            .response
	);

	wire         sc_hub_hub_translator_avalon_universal_master_0_debugaccess;        // sc_hub_hub_translator:uav_debugaccess -> sc_hub_hub_agent:av_debugaccess
	wire  [19:0] sc_hub_hub_translator_avalon_universal_master_0_address;            // sc_hub_hub_translator:uav_address -> sc_hub_hub_agent:av_address
	wire         sc_hub_hub_translator_avalon_universal_master_0_read;               // sc_hub_hub_translator:uav_read -> sc_hub_hub_agent:av_read
	wire   [3:0] sc_hub_hub_translator_avalon_universal_master_0_byteenable;         // sc_hub_hub_translator:uav_byteenable -> sc_hub_hub_agent:av_byteenable
	wire         sc_hub_hub_translator_avalon_universal_master_0_readdatavalid;      // sc_hub_hub_agent:av_readdatavalid -> sc_hub_hub_translator:uav_readdatavalid
	wire         sc_hub_hub_translator_avalon_universal_master_0_waitrequest;        // sc_hub_hub_agent:av_waitrequest -> sc_hub_hub_translator:uav_waitrequest
	wire  [31:0] sc_hub_hub_translator_avalon_universal_master_0_readdata;           // sc_hub_hub_agent:av_readdata -> sc_hub_hub_translator:uav_readdata
	wire   [1:0] sc_hub_hub_translator_avalon_universal_master_0_response;           // sc_hub_hub_agent:av_response -> sc_hub_hub_translator:uav_response
	wire         sc_hub_hub_translator_avalon_universal_master_0_lock;               // sc_hub_hub_translator:uav_lock -> sc_hub_hub_agent:av_lock
	wire         sc_hub_hub_translator_avalon_universal_master_0_write;              // sc_hub_hub_translator:uav_write -> sc_hub_hub_agent:av_write
	wire  [31:0] sc_hub_hub_translator_avalon_universal_master_0_writedata;          // sc_hub_hub_translator:uav_writedata -> sc_hub_hub_agent:av_writedata
	wire         sc_hub_hub_translator_avalon_universal_master_0_writeresponsevalid; // sc_hub_hub_agent:av_writeresponsevalid -> sc_hub_hub_translator:uav_writeresponsevalid
	wire  [10:0] sc_hub_hub_translator_avalon_universal_master_0_burstcount;         // sc_hub_hub_translator:uav_burstcount -> sc_hub_hub_agent:av_burstcount
	wire         rsp_mux_src_valid;                                                  // rsp_mux:src_valid -> sc_hub_hub_agent:rp_valid
	wire  [97:0] rsp_mux_src_data;                                                   // rsp_mux:src_data -> sc_hub_hub_agent:rp_data
	wire         rsp_mux_src_ready;                                                  // sc_hub_hub_agent:rp_ready -> rsp_mux:src_ready
	wire   [0:0] rsp_mux_src_channel;                                                // rsp_mux:src_channel -> sc_hub_hub_agent:rp_channel
	wire         rsp_mux_src_startofpacket;                                          // rsp_mux:src_startofpacket -> sc_hub_hub_agent:rp_startofpacket
	wire         rsp_mux_src_endofpacket;                                            // rsp_mux:src_endofpacket -> sc_hub_hub_agent:rp_endofpacket
	wire  [31:0] sc_hub_cmd_pipe_s0_agent_m0_readdata;                               // sc_hub_cmd_pipe_s0_translator:uav_readdata -> sc_hub_cmd_pipe_s0_agent:m0_readdata
	wire         sc_hub_cmd_pipe_s0_agent_m0_waitrequest;                            // sc_hub_cmd_pipe_s0_translator:uav_waitrequest -> sc_hub_cmd_pipe_s0_agent:m0_waitrequest
	wire         sc_hub_cmd_pipe_s0_agent_m0_debugaccess;                            // sc_hub_cmd_pipe_s0_agent:m0_debugaccess -> sc_hub_cmd_pipe_s0_translator:uav_debugaccess
	wire  [19:0] sc_hub_cmd_pipe_s0_agent_m0_address;                                // sc_hub_cmd_pipe_s0_agent:m0_address -> sc_hub_cmd_pipe_s0_translator:uav_address
	wire   [3:0] sc_hub_cmd_pipe_s0_agent_m0_byteenable;                             // sc_hub_cmd_pipe_s0_agent:m0_byteenable -> sc_hub_cmd_pipe_s0_translator:uav_byteenable
	wire         sc_hub_cmd_pipe_s0_agent_m0_read;                                   // sc_hub_cmd_pipe_s0_agent:m0_read -> sc_hub_cmd_pipe_s0_translator:uav_read
	wire         sc_hub_cmd_pipe_s0_agent_m0_readdatavalid;                          // sc_hub_cmd_pipe_s0_translator:uav_readdatavalid -> sc_hub_cmd_pipe_s0_agent:m0_readdatavalid
	wire   [1:0] sc_hub_cmd_pipe_s0_agent_m0_response;                               // sc_hub_cmd_pipe_s0_translator:uav_response -> sc_hub_cmd_pipe_s0_agent:m0_response
	wire         sc_hub_cmd_pipe_s0_agent_m0_lock;                                   // sc_hub_cmd_pipe_s0_agent:m0_lock -> sc_hub_cmd_pipe_s0_translator:uav_lock
	wire  [31:0] sc_hub_cmd_pipe_s0_agent_m0_writedata;                              // sc_hub_cmd_pipe_s0_agent:m0_writedata -> sc_hub_cmd_pipe_s0_translator:uav_writedata
	wire         sc_hub_cmd_pipe_s0_agent_m0_write;                                  // sc_hub_cmd_pipe_s0_agent:m0_write -> sc_hub_cmd_pipe_s0_translator:uav_write
	wire   [2:0] sc_hub_cmd_pipe_s0_agent_m0_burstcount;                             // sc_hub_cmd_pipe_s0_agent:m0_burstcount -> sc_hub_cmd_pipe_s0_translator:uav_burstcount
	wire         sc_hub_cmd_pipe_s0_agent_rf_source_valid;                           // sc_hub_cmd_pipe_s0_agent:rf_source_valid -> sc_hub_cmd_pipe_s0_agent_rsp_fifo:in_valid
	wire  [98:0] sc_hub_cmd_pipe_s0_agent_rf_source_data;                            // sc_hub_cmd_pipe_s0_agent:rf_source_data -> sc_hub_cmd_pipe_s0_agent_rsp_fifo:in_data
	wire         sc_hub_cmd_pipe_s0_agent_rf_source_ready;                           // sc_hub_cmd_pipe_s0_agent_rsp_fifo:in_ready -> sc_hub_cmd_pipe_s0_agent:rf_source_ready
	wire         sc_hub_cmd_pipe_s0_agent_rf_source_startofpacket;                   // sc_hub_cmd_pipe_s0_agent:rf_source_startofpacket -> sc_hub_cmd_pipe_s0_agent_rsp_fifo:in_startofpacket
	wire         sc_hub_cmd_pipe_s0_agent_rf_source_endofpacket;                     // sc_hub_cmd_pipe_s0_agent:rf_source_endofpacket -> sc_hub_cmd_pipe_s0_agent_rsp_fifo:in_endofpacket
	wire         sc_hub_cmd_pipe_s0_agent_rsp_fifo_out_valid;                        // sc_hub_cmd_pipe_s0_agent_rsp_fifo:out_valid -> sc_hub_cmd_pipe_s0_agent:rf_sink_valid
	wire  [98:0] sc_hub_cmd_pipe_s0_agent_rsp_fifo_out_data;                         // sc_hub_cmd_pipe_s0_agent_rsp_fifo:out_data -> sc_hub_cmd_pipe_s0_agent:rf_sink_data
	wire         sc_hub_cmd_pipe_s0_agent_rsp_fifo_out_ready;                        // sc_hub_cmd_pipe_s0_agent:rf_sink_ready -> sc_hub_cmd_pipe_s0_agent_rsp_fifo:out_ready
	wire         sc_hub_cmd_pipe_s0_agent_rsp_fifo_out_startofpacket;                // sc_hub_cmd_pipe_s0_agent_rsp_fifo:out_startofpacket -> sc_hub_cmd_pipe_s0_agent:rf_sink_startofpacket
	wire         sc_hub_cmd_pipe_s0_agent_rsp_fifo_out_endofpacket;                  // sc_hub_cmd_pipe_s0_agent_rsp_fifo:out_endofpacket -> sc_hub_cmd_pipe_s0_agent:rf_sink_endofpacket
	wire         sc_hub_hub_agent_cp_valid;                                          // sc_hub_hub_agent:cp_valid -> router:sink_valid
	wire  [97:0] sc_hub_hub_agent_cp_data;                                           // sc_hub_hub_agent:cp_data -> router:sink_data
	wire         sc_hub_hub_agent_cp_ready;                                          // router:sink_ready -> sc_hub_hub_agent:cp_ready
	wire         sc_hub_hub_agent_cp_startofpacket;                                  // sc_hub_hub_agent:cp_startofpacket -> router:sink_startofpacket
	wire         sc_hub_hub_agent_cp_endofpacket;                                    // sc_hub_hub_agent:cp_endofpacket -> router:sink_endofpacket
	wire         router_src_valid;                                                   // router:src_valid -> cmd_demux:sink_valid
	wire  [97:0] router_src_data;                                                    // router:src_data -> cmd_demux:sink_data
	wire         router_src_ready;                                                   // cmd_demux:sink_ready -> router:src_ready
	wire   [0:0] router_src_channel;                                                 // router:src_channel -> cmd_demux:sink_channel
	wire         router_src_startofpacket;                                           // router:src_startofpacket -> cmd_demux:sink_startofpacket
	wire         router_src_endofpacket;                                             // router:src_endofpacket -> cmd_demux:sink_endofpacket
	wire         router_001_src_valid;                                               // router_001:src_valid -> rsp_demux:sink_valid
	wire  [97:0] router_001_src_data;                                                // router_001:src_data -> rsp_demux:sink_data
	wire         router_001_src_ready;                                               // rsp_demux:sink_ready -> router_001:src_ready
	wire   [0:0] router_001_src_channel;                                             // router_001:src_channel -> rsp_demux:sink_channel
	wire         router_001_src_startofpacket;                                       // router_001:src_startofpacket -> rsp_demux:sink_startofpacket
	wire         router_001_src_endofpacket;                                         // router_001:src_endofpacket -> rsp_demux:sink_endofpacket
	wire         cmd_mux_src_valid;                                                  // cmd_mux:src_valid -> sc_hub_cmd_pipe_s0_burst_adapter:sink0_valid
	wire  [97:0] cmd_mux_src_data;                                                   // cmd_mux:src_data -> sc_hub_cmd_pipe_s0_burst_adapter:sink0_data
	wire         cmd_mux_src_ready;                                                  // sc_hub_cmd_pipe_s0_burst_adapter:sink0_ready -> cmd_mux:src_ready
	wire   [0:0] cmd_mux_src_channel;                                                // cmd_mux:src_channel -> sc_hub_cmd_pipe_s0_burst_adapter:sink0_channel
	wire         cmd_mux_src_startofpacket;                                          // cmd_mux:src_startofpacket -> sc_hub_cmd_pipe_s0_burst_adapter:sink0_startofpacket
	wire         cmd_mux_src_endofpacket;                                            // cmd_mux:src_endofpacket -> sc_hub_cmd_pipe_s0_burst_adapter:sink0_endofpacket
	wire         sc_hub_cmd_pipe_s0_burst_adapter_source0_valid;                     // sc_hub_cmd_pipe_s0_burst_adapter:source0_valid -> agent_pipeline:in_valid
	wire  [97:0] sc_hub_cmd_pipe_s0_burst_adapter_source0_data;                      // sc_hub_cmd_pipe_s0_burst_adapter:source0_data -> agent_pipeline:in_data
	wire         sc_hub_cmd_pipe_s0_burst_adapter_source0_ready;                     // agent_pipeline:in_ready -> sc_hub_cmd_pipe_s0_burst_adapter:source0_ready
	wire   [0:0] sc_hub_cmd_pipe_s0_burst_adapter_source0_channel;                   // sc_hub_cmd_pipe_s0_burst_adapter:source0_channel -> agent_pipeline:in_channel
	wire         sc_hub_cmd_pipe_s0_burst_adapter_source0_startofpacket;             // sc_hub_cmd_pipe_s0_burst_adapter:source0_startofpacket -> agent_pipeline:in_startofpacket
	wire         sc_hub_cmd_pipe_s0_burst_adapter_source0_endofpacket;               // sc_hub_cmd_pipe_s0_burst_adapter:source0_endofpacket -> agent_pipeline:in_endofpacket
	wire         agent_pipeline_source0_valid;                                       // agent_pipeline:out_valid -> sc_hub_cmd_pipe_s0_agent:cp_valid
	wire  [97:0] agent_pipeline_source0_data;                                        // agent_pipeline:out_data -> sc_hub_cmd_pipe_s0_agent:cp_data
	wire         agent_pipeline_source0_ready;                                       // sc_hub_cmd_pipe_s0_agent:cp_ready -> agent_pipeline:out_ready
	wire   [0:0] agent_pipeline_source0_channel;                                     // agent_pipeline:out_channel -> sc_hub_cmd_pipe_s0_agent:cp_channel
	wire         agent_pipeline_source0_startofpacket;                               // agent_pipeline:out_startofpacket -> sc_hub_cmd_pipe_s0_agent:cp_startofpacket
	wire         agent_pipeline_source0_endofpacket;                                 // agent_pipeline:out_endofpacket -> sc_hub_cmd_pipe_s0_agent:cp_endofpacket
	wire         sc_hub_cmd_pipe_s0_agent_rp_valid;                                  // sc_hub_cmd_pipe_s0_agent:rp_valid -> agent_pipeline_001:in_valid
	wire  [97:0] sc_hub_cmd_pipe_s0_agent_rp_data;                                   // sc_hub_cmd_pipe_s0_agent:rp_data -> agent_pipeline_001:in_data
	wire         sc_hub_cmd_pipe_s0_agent_rp_ready;                                  // agent_pipeline_001:in_ready -> sc_hub_cmd_pipe_s0_agent:rp_ready
	wire         sc_hub_cmd_pipe_s0_agent_rp_startofpacket;                          // sc_hub_cmd_pipe_s0_agent:rp_startofpacket -> agent_pipeline_001:in_startofpacket
	wire         sc_hub_cmd_pipe_s0_agent_rp_endofpacket;                            // sc_hub_cmd_pipe_s0_agent:rp_endofpacket -> agent_pipeline_001:in_endofpacket
	wire         agent_pipeline_001_source0_valid;                                   // agent_pipeline_001:out_valid -> router_001:sink_valid
	wire  [97:0] agent_pipeline_001_source0_data;                                    // agent_pipeline_001:out_data -> router_001:sink_data
	wire         agent_pipeline_001_source0_ready;                                   // router_001:sink_ready -> agent_pipeline_001:out_ready
	wire         agent_pipeline_001_source0_startofpacket;                           // agent_pipeline_001:out_startofpacket -> router_001:sink_startofpacket
	wire         agent_pipeline_001_source0_endofpacket;                             // agent_pipeline_001:out_endofpacket -> router_001:sink_endofpacket
	wire         cmd_demux_src0_valid;                                               // cmd_demux:src0_valid -> mux_pipeline:in_valid
	wire  [97:0] cmd_demux_src0_data;                                                // cmd_demux:src0_data -> mux_pipeline:in_data
	wire         cmd_demux_src0_ready;                                               // mux_pipeline:in_ready -> cmd_demux:src0_ready
	wire   [0:0] cmd_demux_src0_channel;                                             // cmd_demux:src0_channel -> mux_pipeline:in_channel
	wire         cmd_demux_src0_startofpacket;                                       // cmd_demux:src0_startofpacket -> mux_pipeline:in_startofpacket
	wire         cmd_demux_src0_endofpacket;                                         // cmd_demux:src0_endofpacket -> mux_pipeline:in_endofpacket
	wire         mux_pipeline_source0_valid;                                         // mux_pipeline:out_valid -> cmd_mux:sink0_valid
	wire  [97:0] mux_pipeline_source0_data;                                          // mux_pipeline:out_data -> cmd_mux:sink0_data
	wire         mux_pipeline_source0_ready;                                         // cmd_mux:sink0_ready -> mux_pipeline:out_ready
	wire   [0:0] mux_pipeline_source0_channel;                                       // mux_pipeline:out_channel -> cmd_mux:sink0_channel
	wire         mux_pipeline_source0_startofpacket;                                 // mux_pipeline:out_startofpacket -> cmd_mux:sink0_startofpacket
	wire         mux_pipeline_source0_endofpacket;                                   // mux_pipeline:out_endofpacket -> cmd_mux:sink0_endofpacket
	wire         rsp_demux_src0_valid;                                               // rsp_demux:src0_valid -> mux_pipeline_001:in_valid
	wire  [97:0] rsp_demux_src0_data;                                                // rsp_demux:src0_data -> mux_pipeline_001:in_data
	wire         rsp_demux_src0_ready;                                               // mux_pipeline_001:in_ready -> rsp_demux:src0_ready
	wire   [0:0] rsp_demux_src0_channel;                                             // rsp_demux:src0_channel -> mux_pipeline_001:in_channel
	wire         rsp_demux_src0_startofpacket;                                       // rsp_demux:src0_startofpacket -> mux_pipeline_001:in_startofpacket
	wire         rsp_demux_src0_endofpacket;                                         // rsp_demux:src0_endofpacket -> mux_pipeline_001:in_endofpacket
	wire         mux_pipeline_001_source0_valid;                                     // mux_pipeline_001:out_valid -> rsp_mux:sink0_valid
	wire  [97:0] mux_pipeline_001_source0_data;                                      // mux_pipeline_001:out_data -> rsp_mux:sink0_data
	wire         mux_pipeline_001_source0_ready;                                     // rsp_mux:sink0_ready -> mux_pipeline_001:out_ready
	wire   [0:0] mux_pipeline_001_source0_channel;                                   // mux_pipeline_001:out_channel -> rsp_mux:sink0_channel
	wire         mux_pipeline_001_source0_startofpacket;                             // mux_pipeline_001:out_startofpacket -> rsp_mux:sink0_startofpacket
	wire         mux_pipeline_001_source0_endofpacket;                               // mux_pipeline_001:out_endofpacket -> rsp_mux:sink0_endofpacket
	wire         sc_hub_cmd_pipe_s0_agent_rdata_fifo_src_valid;                      // sc_hub_cmd_pipe_s0_agent:rdata_fifo_src_valid -> avalon_st_adapter:in_0_valid
	wire  [33:0] sc_hub_cmd_pipe_s0_agent_rdata_fifo_src_data;                       // sc_hub_cmd_pipe_s0_agent:rdata_fifo_src_data -> avalon_st_adapter:in_0_data
	wire         sc_hub_cmd_pipe_s0_agent_rdata_fifo_src_ready;                      // avalon_st_adapter:in_0_ready -> sc_hub_cmd_pipe_s0_agent:rdata_fifo_src_ready
	wire         avalon_st_adapter_out_0_valid;                                      // avalon_st_adapter:out_0_valid -> sc_hub_cmd_pipe_s0_agent:rdata_fifo_sink_valid
	wire  [33:0] avalon_st_adapter_out_0_data;                                       // avalon_st_adapter:out_0_data -> sc_hub_cmd_pipe_s0_agent:rdata_fifo_sink_data
	wire         avalon_st_adapter_out_0_ready;                                      // sc_hub_cmd_pipe_s0_agent:rdata_fifo_sink_ready -> avalon_st_adapter:out_0_ready
	wire   [0:0] avalon_st_adapter_out_0_error;                                      // avalon_st_adapter:out_0_error -> sc_hub_cmd_pipe_s0_agent:rdata_fifo_sink_error

	altera_merlin_master_translator #(
		.AV_ADDRESS_W                (18),
		.AV_DATA_W                   (32),
		.AV_BURSTCOUNT_W             (9),
		.AV_BYTEENABLE_W             (4),
		.UAV_ADDRESS_W               (20),
		.UAV_BURSTCOUNT_W            (11),
		.USE_READ                    (1),
		.USE_WRITE                   (1),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (0),
		.USE_BURSTCOUNT              (1),
		.USE_READDATAVALID           (1),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (1),
		.USE_WRITERESPONSE           (1),
		.AV_SYMBOLS_PER_WORD         (4),
		.AV_ADDRESS_SYMBOLS          (0),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (1),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0)
	) sc_hub_hub_translator (
		.clk                    (clk156_clk_clk),                                                     //                       clk.clk
		.reset                  (sc_hub_hub_reset_reset_bridge_in_reset_reset),                       //                     reset.reset
		.uav_address            (sc_hub_hub_translator_avalon_universal_master_0_address),            // avalon_universal_master_0.address
		.uav_burstcount         (sc_hub_hub_translator_avalon_universal_master_0_burstcount),         //                          .burstcount
		.uav_read               (sc_hub_hub_translator_avalon_universal_master_0_read),               //                          .read
		.uav_write              (sc_hub_hub_translator_avalon_universal_master_0_write),              //                          .write
		.uav_waitrequest        (sc_hub_hub_translator_avalon_universal_master_0_waitrequest),        //                          .waitrequest
		.uav_readdatavalid      (sc_hub_hub_translator_avalon_universal_master_0_readdatavalid),      //                          .readdatavalid
		.uav_byteenable         (sc_hub_hub_translator_avalon_universal_master_0_byteenable),         //                          .byteenable
		.uav_readdata           (sc_hub_hub_translator_avalon_universal_master_0_readdata),           //                          .readdata
		.uav_writedata          (sc_hub_hub_translator_avalon_universal_master_0_writedata),          //                          .writedata
		.uav_lock               (sc_hub_hub_translator_avalon_universal_master_0_lock),               //                          .lock
		.uav_debugaccess        (sc_hub_hub_translator_avalon_universal_master_0_debugaccess),        //                          .debugaccess
		.uav_response           (sc_hub_hub_translator_avalon_universal_master_0_response),           //                          .response
		.uav_writeresponsevalid (sc_hub_hub_translator_avalon_universal_master_0_writeresponsevalid), //                          .writeresponsevalid
		.av_address             (sc_hub_hub_address),                                                 //      avalon_anti_master_0.address
		.av_waitrequest         (sc_hub_hub_waitrequest),                                             //                          .waitrequest
		.av_burstcount          (sc_hub_hub_burstcount),                                              //                          .burstcount
		.av_read                (sc_hub_hub_read),                                                    //                          .read
		.av_readdata            (sc_hub_hub_readdata),                                                //                          .readdata
		.av_readdatavalid       (sc_hub_hub_readdatavalid),                                           //                          .readdatavalid
		.av_write               (sc_hub_hub_write),                                                   //                          .write
		.av_writedata           (sc_hub_hub_writedata),                                               //                          .writedata
		.av_response            (sc_hub_hub_response),                                                //                          .response
		.av_writeresponsevalid  (sc_hub_hub_writeresponsevalid),                                      //                          .writeresponsevalid
		.av_byteenable          (4'b1111),                                                            //               (terminated)
		.av_beginbursttransfer  (1'b0),                                                               //               (terminated)
		.av_begintransfer       (1'b0),                                                               //               (terminated)
		.av_chipselect          (1'b0),                                                               //               (terminated)
		.av_lock                (1'b0),                                                               //               (terminated)
		.av_debugaccess         (1'b0),                                                               //               (terminated)
		.uav_clken              (),                                                                   //               (terminated)
		.av_clken               (1'b1)                                                                //               (terminated)
	);

	altera_merlin_slave_translator #(
		.AV_ADDRESS_W                   (16),
		.AV_DATA_W                      (32),
		.UAV_DATA_W                     (32),
		.AV_BURSTCOUNT_W                (1),
		.AV_BYTEENABLE_W                (4),
		.UAV_BYTEENABLE_W               (4),
		.UAV_ADDRESS_W                  (20),
		.UAV_BURSTCOUNT_W               (3),
		.AV_READLATENCY                 (0),
		.USE_READDATAVALID              (1),
		.USE_WAITREQUEST                (1),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (1),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (4),
		.AV_ADDRESS_SYMBOLS             (0),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (0),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0)
	) sc_hub_cmd_pipe_s0_translator (
		.clk                    (clk156_clk_clk),                                    //                      clk.clk
		.reset                  (sc_hub_cmd_pipe_reset_reset_bridge_in_reset_reset), //                    reset.reset
		.uav_address            (sc_hub_cmd_pipe_s0_agent_m0_address),               // avalon_universal_slave_0.address
		.uav_burstcount         (sc_hub_cmd_pipe_s0_agent_m0_burstcount),            //                         .burstcount
		.uav_read               (sc_hub_cmd_pipe_s0_agent_m0_read),                  //                         .read
		.uav_write              (sc_hub_cmd_pipe_s0_agent_m0_write),                 //                         .write
		.uav_waitrequest        (sc_hub_cmd_pipe_s0_agent_m0_waitrequest),           //                         .waitrequest
		.uav_readdatavalid      (sc_hub_cmd_pipe_s0_agent_m0_readdatavalid),         //                         .readdatavalid
		.uav_byteenable         (sc_hub_cmd_pipe_s0_agent_m0_byteenable),            //                         .byteenable
		.uav_readdata           (sc_hub_cmd_pipe_s0_agent_m0_readdata),              //                         .readdata
		.uav_writedata          (sc_hub_cmd_pipe_s0_agent_m0_writedata),             //                         .writedata
		.uav_lock               (sc_hub_cmd_pipe_s0_agent_m0_lock),                  //                         .lock
		.uav_debugaccess        (sc_hub_cmd_pipe_s0_agent_m0_debugaccess),           //                         .debugaccess
		.uav_response           (sc_hub_cmd_pipe_s0_agent_m0_response),              //                         .response
		.av_address             (sc_hub_cmd_pipe_s0_address),                        //      avalon_anti_slave_0.address
		.av_write               (sc_hub_cmd_pipe_s0_write),                          //                         .write
		.av_read                (sc_hub_cmd_pipe_s0_read),                           //                         .read
		.av_readdata            (sc_hub_cmd_pipe_s0_readdata),                       //                         .readdata
		.av_writedata           (sc_hub_cmd_pipe_s0_writedata),                      //                         .writedata
		.av_burstcount          (sc_hub_cmd_pipe_s0_burstcount),                     //                         .burstcount
		.av_byteenable          (sc_hub_cmd_pipe_s0_byteenable),                     //                         .byteenable
		.av_readdatavalid       (sc_hub_cmd_pipe_s0_readdatavalid),                  //                         .readdatavalid
		.av_waitrequest         (sc_hub_cmd_pipe_s0_waitrequest),                    //                         .waitrequest
		.av_debugaccess         (sc_hub_cmd_pipe_s0_debugaccess),                    //                         .debugaccess
		.av_response            (sc_hub_cmd_pipe_s0_response),                       //                         .response
		.av_begintransfer       (),                                                  //              (terminated)
		.av_beginbursttransfer  (),                                                  //              (terminated)
		.av_writebyteenable     (),                                                  //              (terminated)
		.av_lock                (),                                                  //              (terminated)
		.av_chipselect          (),                                                  //              (terminated)
		.av_clken               (),                                                  //              (terminated)
		.uav_clken              (1'b0),                                              //              (terminated)
		.av_outputenable        (),                                                  //              (terminated)
		.uav_writeresponsevalid (),                                                  //              (terminated)
		.av_writeresponsevalid  (1'b0)                                               //              (terminated)
	);

	altera_merlin_master_agent #(
		.PKT_ORI_BURST_SIZE_H      (97),
		.PKT_ORI_BURST_SIZE_L      (95),
		.PKT_RESPONSE_STATUS_H     (94),
		.PKT_RESPONSE_STATUS_L     (93),
		.PKT_QOS_H                 (82),
		.PKT_QOS_L                 (82),
		.PKT_DATA_SIDEBAND_H       (80),
		.PKT_DATA_SIDEBAND_L       (80),
		.PKT_ADDR_SIDEBAND_H       (79),
		.PKT_ADDR_SIDEBAND_L       (79),
		.PKT_BURST_TYPE_H          (78),
		.PKT_BURST_TYPE_L          (77),
		.PKT_CACHE_H               (92),
		.PKT_CACHE_L               (89),
		.PKT_THREAD_ID_H           (85),
		.PKT_THREAD_ID_L           (85),
		.PKT_BURST_SIZE_H          (76),
		.PKT_BURST_SIZE_L          (74),
		.PKT_TRANS_EXCLUSIVE       (61),
		.PKT_TRANS_LOCK            (60),
		.PKT_BEGIN_BURST           (81),
		.PKT_PROTECTION_H          (88),
		.PKT_PROTECTION_L          (86),
		.PKT_BURSTWRAP_H           (73),
		.PKT_BURSTWRAP_L           (73),
		.PKT_BYTE_CNT_H            (72),
		.PKT_BYTE_CNT_L            (62),
		.PKT_ADDR_H                (55),
		.PKT_ADDR_L                (36),
		.PKT_TRANS_COMPRESSED_READ (56),
		.PKT_TRANS_POSTED          (57),
		.PKT_TRANS_WRITE           (58),
		.PKT_TRANS_READ            (59),
		.PKT_DATA_H                (31),
		.PKT_DATA_L                (0),
		.PKT_BYTEEN_H              (35),
		.PKT_BYTEEN_L              (32),
		.PKT_SRC_ID_H              (83),
		.PKT_SRC_ID_L              (83),
		.PKT_DEST_ID_H             (84),
		.PKT_DEST_ID_L             (84),
		.ST_DATA_W                 (98),
		.ST_CHANNEL_W              (1),
		.AV_BURSTCOUNT_W           (11),
		.SUPPRESS_0_BYTEEN_RSP     (0),
		.ID                        (0),
		.BURSTWRAP_VALUE           (1),
		.CACHE_VALUE               (0),
		.SECURE_ACCESS_BIT         (1),
		.USE_READRESPONSE          (1),
		.USE_WRITERESPONSE         (1)
	) sc_hub_hub_agent (
		.clk                   (clk156_clk_clk),                                                     //       clk.clk
		.reset                 (sc_hub_hub_reset_reset_bridge_in_reset_reset),                       // clk_reset.reset
		.av_address            (sc_hub_hub_translator_avalon_universal_master_0_address),            //        av.address
		.av_write              (sc_hub_hub_translator_avalon_universal_master_0_write),              //          .write
		.av_read               (sc_hub_hub_translator_avalon_universal_master_0_read),               //          .read
		.av_writedata          (sc_hub_hub_translator_avalon_universal_master_0_writedata),          //          .writedata
		.av_readdata           (sc_hub_hub_translator_avalon_universal_master_0_readdata),           //          .readdata
		.av_waitrequest        (sc_hub_hub_translator_avalon_universal_master_0_waitrequest),        //          .waitrequest
		.av_readdatavalid      (sc_hub_hub_translator_avalon_universal_master_0_readdatavalid),      //          .readdatavalid
		.av_byteenable         (sc_hub_hub_translator_avalon_universal_master_0_byteenable),         //          .byteenable
		.av_burstcount         (sc_hub_hub_translator_avalon_universal_master_0_burstcount),         //          .burstcount
		.av_debugaccess        (sc_hub_hub_translator_avalon_universal_master_0_debugaccess),        //          .debugaccess
		.av_lock               (sc_hub_hub_translator_avalon_universal_master_0_lock),               //          .lock
		.av_response           (sc_hub_hub_translator_avalon_universal_master_0_response),           //          .response
		.av_writeresponsevalid (sc_hub_hub_translator_avalon_universal_master_0_writeresponsevalid), //          .writeresponsevalid
		.cp_valid              (sc_hub_hub_agent_cp_valid),                                          //        cp.valid
		.cp_data               (sc_hub_hub_agent_cp_data),                                           //          .data
		.cp_startofpacket      (sc_hub_hub_agent_cp_startofpacket),                                  //          .startofpacket
		.cp_endofpacket        (sc_hub_hub_agent_cp_endofpacket),                                    //          .endofpacket
		.cp_ready              (sc_hub_hub_agent_cp_ready),                                          //          .ready
		.rp_valid              (rsp_mux_src_valid),                                                  //        rp.valid
		.rp_data               (rsp_mux_src_data),                                                   //          .data
		.rp_channel            (rsp_mux_src_channel),                                                //          .channel
		.rp_startofpacket      (rsp_mux_src_startofpacket),                                          //          .startofpacket
		.rp_endofpacket        (rsp_mux_src_endofpacket),                                            //          .endofpacket
		.rp_ready              (rsp_mux_src_ready)                                                   //          .ready
	);

	altera_merlin_slave_agent #(
		.PKT_ORI_BURST_SIZE_H      (97),
		.PKT_ORI_BURST_SIZE_L      (95),
		.PKT_RESPONSE_STATUS_H     (94),
		.PKT_RESPONSE_STATUS_L     (93),
		.PKT_BURST_SIZE_H          (76),
		.PKT_BURST_SIZE_L          (74),
		.PKT_TRANS_LOCK            (60),
		.PKT_BEGIN_BURST           (81),
		.PKT_PROTECTION_H          (88),
		.PKT_PROTECTION_L          (86),
		.PKT_BURSTWRAP_H           (73),
		.PKT_BURSTWRAP_L           (73),
		.PKT_BYTE_CNT_H            (72),
		.PKT_BYTE_CNT_L            (62),
		.PKT_ADDR_H                (55),
		.PKT_ADDR_L                (36),
		.PKT_TRANS_COMPRESSED_READ (56),
		.PKT_TRANS_POSTED          (57),
		.PKT_TRANS_WRITE           (58),
		.PKT_TRANS_READ            (59),
		.PKT_DATA_H                (31),
		.PKT_DATA_L                (0),
		.PKT_BYTEEN_H              (35),
		.PKT_BYTEEN_L              (32),
		.PKT_SRC_ID_H              (83),
		.PKT_SRC_ID_L              (83),
		.PKT_DEST_ID_H             (84),
		.PKT_DEST_ID_L             (84),
		.PKT_SYMBOL_W              (8),
		.ST_CHANNEL_W              (1),
		.ST_DATA_W                 (98),
		.AVS_BURSTCOUNT_W          (3),
		.SUPPRESS_0_BYTEEN_CMD     (0),
		.PREVENT_FIFO_OVERFLOW     (1),
		.USE_READRESPONSE          (1),
		.USE_WRITERESPONSE         (0),
		.ECC_ENABLE                (0)
	) sc_hub_cmd_pipe_s0_agent (
		.clk                     (clk156_clk_clk),                                      //             clk.clk
		.reset                   (sc_hub_cmd_pipe_reset_reset_bridge_in_reset_reset),   //       clk_reset.reset
		.m0_address              (sc_hub_cmd_pipe_s0_agent_m0_address),                 //              m0.address
		.m0_burstcount           (sc_hub_cmd_pipe_s0_agent_m0_burstcount),              //                .burstcount
		.m0_byteenable           (sc_hub_cmd_pipe_s0_agent_m0_byteenable),              //                .byteenable
		.m0_debugaccess          (sc_hub_cmd_pipe_s0_agent_m0_debugaccess),             //                .debugaccess
		.m0_lock                 (sc_hub_cmd_pipe_s0_agent_m0_lock),                    //                .lock
		.m0_readdata             (sc_hub_cmd_pipe_s0_agent_m0_readdata),                //                .readdata
		.m0_readdatavalid        (sc_hub_cmd_pipe_s0_agent_m0_readdatavalid),           //                .readdatavalid
		.m0_read                 (sc_hub_cmd_pipe_s0_agent_m0_read),                    //                .read
		.m0_waitrequest          (sc_hub_cmd_pipe_s0_agent_m0_waitrequest),             //                .waitrequest
		.m0_writedata            (sc_hub_cmd_pipe_s0_agent_m0_writedata),               //                .writedata
		.m0_write                (sc_hub_cmd_pipe_s0_agent_m0_write),                   //                .write
		.m0_response             (sc_hub_cmd_pipe_s0_agent_m0_response),                //                .response
		.rp_endofpacket          (sc_hub_cmd_pipe_s0_agent_rp_endofpacket),             //              rp.endofpacket
		.rp_ready                (sc_hub_cmd_pipe_s0_agent_rp_ready),                   //                .ready
		.rp_valid                (sc_hub_cmd_pipe_s0_agent_rp_valid),                   //                .valid
		.rp_data                 (sc_hub_cmd_pipe_s0_agent_rp_data),                    //                .data
		.rp_startofpacket        (sc_hub_cmd_pipe_s0_agent_rp_startofpacket),           //                .startofpacket
		.cp_ready                (agent_pipeline_source0_ready),                        //              cp.ready
		.cp_valid                (agent_pipeline_source0_valid),                        //                .valid
		.cp_data                 (agent_pipeline_source0_data),                         //                .data
		.cp_startofpacket        (agent_pipeline_source0_startofpacket),                //                .startofpacket
		.cp_endofpacket          (agent_pipeline_source0_endofpacket),                  //                .endofpacket
		.cp_channel              (agent_pipeline_source0_channel),                      //                .channel
		.rf_sink_ready           (sc_hub_cmd_pipe_s0_agent_rsp_fifo_out_ready),         //         rf_sink.ready
		.rf_sink_valid           (sc_hub_cmd_pipe_s0_agent_rsp_fifo_out_valid),         //                .valid
		.rf_sink_startofpacket   (sc_hub_cmd_pipe_s0_agent_rsp_fifo_out_startofpacket), //                .startofpacket
		.rf_sink_endofpacket     (sc_hub_cmd_pipe_s0_agent_rsp_fifo_out_endofpacket),   //                .endofpacket
		.rf_sink_data            (sc_hub_cmd_pipe_s0_agent_rsp_fifo_out_data),          //                .data
		.rf_source_ready         (sc_hub_cmd_pipe_s0_agent_rf_source_ready),            //       rf_source.ready
		.rf_source_valid         (sc_hub_cmd_pipe_s0_agent_rf_source_valid),            //                .valid
		.rf_source_startofpacket (sc_hub_cmd_pipe_s0_agent_rf_source_startofpacket),    //                .startofpacket
		.rf_source_endofpacket   (sc_hub_cmd_pipe_s0_agent_rf_source_endofpacket),      //                .endofpacket
		.rf_source_data          (sc_hub_cmd_pipe_s0_agent_rf_source_data),             //                .data
		.rdata_fifo_sink_ready   (avalon_st_adapter_out_0_ready),                       // rdata_fifo_sink.ready
		.rdata_fifo_sink_valid   (avalon_st_adapter_out_0_valid),                       //                .valid
		.rdata_fifo_sink_data    (avalon_st_adapter_out_0_data),                        //                .data
		.rdata_fifo_sink_error   (avalon_st_adapter_out_0_error),                       //                .error
		.rdata_fifo_src_ready    (sc_hub_cmd_pipe_s0_agent_rdata_fifo_src_ready),       //  rdata_fifo_src.ready
		.rdata_fifo_src_valid    (sc_hub_cmd_pipe_s0_agent_rdata_fifo_src_valid),       //                .valid
		.rdata_fifo_src_data     (sc_hub_cmd_pipe_s0_agent_rdata_fifo_src_data),        //                .data
		.m0_writeresponsevalid   (1'b0)                                                 //     (terminated)
	);

	altera_avalon_sc_fifo #(
		.SYMBOLS_PER_BEAT    (1),
		.BITS_PER_SYMBOL     (99),
		.FIFO_DEPTH          (2),
		.CHANNEL_WIDTH       (0),
		.ERROR_WIDTH         (0),
		.USE_PACKETS         (1),
		.USE_FILL_LEVEL      (0),
		.EMPTY_LATENCY       (1),
		.USE_MEMORY_BLOCKS   (0),
		.USE_STORE_FORWARD   (0),
		.USE_ALMOST_FULL_IF  (0),
		.USE_ALMOST_EMPTY_IF (0)
	) sc_hub_cmd_pipe_s0_agent_rsp_fifo (
		.clk               (clk156_clk_clk),                                      //       clk.clk
		.reset             (sc_hub_cmd_pipe_reset_reset_bridge_in_reset_reset),   // clk_reset.reset
		.in_data           (sc_hub_cmd_pipe_s0_agent_rf_source_data),             //        in.data
		.in_valid          (sc_hub_cmd_pipe_s0_agent_rf_source_valid),            //          .valid
		.in_ready          (sc_hub_cmd_pipe_s0_agent_rf_source_ready),            //          .ready
		.in_startofpacket  (sc_hub_cmd_pipe_s0_agent_rf_source_startofpacket),    //          .startofpacket
		.in_endofpacket    (sc_hub_cmd_pipe_s0_agent_rf_source_endofpacket),      //          .endofpacket
		.out_data          (sc_hub_cmd_pipe_s0_agent_rsp_fifo_out_data),          //       out.data
		.out_valid         (sc_hub_cmd_pipe_s0_agent_rsp_fifo_out_valid),         //          .valid
		.out_ready         (sc_hub_cmd_pipe_s0_agent_rsp_fifo_out_ready),         //          .ready
		.out_startofpacket (sc_hub_cmd_pipe_s0_agent_rsp_fifo_out_startofpacket), //          .startofpacket
		.out_endofpacket   (sc_hub_cmd_pipe_s0_agent_rsp_fifo_out_endofpacket),   //          .endofpacket
		.csr_address       (2'b00),                                               // (terminated)
		.csr_read          (1'b0),                                                // (terminated)
		.csr_write         (1'b0),                                                // (terminated)
		.csr_readdata      (),                                                    // (terminated)
		.csr_writedata     (32'b00000000000000000000000000000000),                // (terminated)
		.almost_full_data  (),                                                    // (terminated)
		.almost_empty_data (),                                                    // (terminated)
		.in_empty          (1'b0),                                                // (terminated)
		.out_empty         (),                                                    // (terminated)
		.in_error          (1'b0),                                                // (terminated)
		.out_error         (),                                                    // (terminated)
		.in_channel        (1'b0),                                                // (terminated)
		.out_channel       ()                                                     // (terminated)
	);

	debug_sc_system_v3_lvdsctrl_cbb_mm_interconnect_2_router router (
		.sink_ready         (sc_hub_hub_agent_cp_ready),                    //      sink.ready
		.sink_valid         (sc_hub_hub_agent_cp_valid),                    //          .valid
		.sink_data          (sc_hub_hub_agent_cp_data),                     //          .data
		.sink_startofpacket (sc_hub_hub_agent_cp_startofpacket),            //          .startofpacket
		.sink_endofpacket   (sc_hub_hub_agent_cp_endofpacket),              //          .endofpacket
		.clk                (clk156_clk_clk),                               //       clk.clk
		.reset              (sc_hub_hub_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready          (router_src_ready),                             //       src.ready
		.src_valid          (router_src_valid),                             //          .valid
		.src_data           (router_src_data),                              //          .data
		.src_channel        (router_src_channel),                           //          .channel
		.src_startofpacket  (router_src_startofpacket),                     //          .startofpacket
		.src_endofpacket    (router_src_endofpacket)                        //          .endofpacket
	);

	debug_sc_system_v3_lvdsctrl_cbb_mm_interconnect_2_router_001 router_001 (
		.sink_ready         (agent_pipeline_001_source0_ready),                  //      sink.ready
		.sink_valid         (agent_pipeline_001_source0_valid),                  //          .valid
		.sink_data          (agent_pipeline_001_source0_data),                   //          .data
		.sink_startofpacket (agent_pipeline_001_source0_startofpacket),          //          .startofpacket
		.sink_endofpacket   (agent_pipeline_001_source0_endofpacket),            //          .endofpacket
		.clk                (clk156_clk_clk),                                    //       clk.clk
		.reset              (sc_hub_cmd_pipe_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready          (router_001_src_ready),                              //       src.ready
		.src_valid          (router_001_src_valid),                              //          .valid
		.src_data           (router_001_src_data),                               //          .data
		.src_channel        (router_001_src_channel),                            //          .channel
		.src_startofpacket  (router_001_src_startofpacket),                      //          .startofpacket
		.src_endofpacket    (router_001_src_endofpacket)                         //          .endofpacket
	);

	altera_merlin_burst_adapter #(
		.PKT_ADDR_H                (55),
		.PKT_ADDR_L                (36),
		.PKT_BEGIN_BURST           (81),
		.PKT_BYTE_CNT_H            (72),
		.PKT_BYTE_CNT_L            (62),
		.PKT_BYTEEN_H              (35),
		.PKT_BYTEEN_L              (32),
		.PKT_BURST_SIZE_H          (76),
		.PKT_BURST_SIZE_L          (74),
		.PKT_BURST_TYPE_H          (78),
		.PKT_BURST_TYPE_L          (77),
		.PKT_BURSTWRAP_H           (73),
		.PKT_BURSTWRAP_L           (73),
		.PKT_TRANS_COMPRESSED_READ (56),
		.PKT_TRANS_WRITE           (58),
		.PKT_TRANS_READ            (59),
		.OUT_NARROW_SIZE           (0),
		.IN_NARROW_SIZE            (0),
		.OUT_FIXED                 (0),
		.OUT_COMPLETE_WRAP         (0),
		.ST_DATA_W                 (98),
		.ST_CHANNEL_W              (1),
		.OUT_BYTE_CNT_H            (64),
		.OUT_BURSTWRAP_H           (73),
		.COMPRESSED_READ_SUPPORT   (1),
		.BYTEENABLE_SYNTHESIS      (1),
		.PIPE_INPUTS               (0),
		.NO_WRAP_SUPPORT           (0),
		.INCOMPLETE_WRAP_SUPPORT   (0),
		.BURSTWRAP_CONST_MASK      (1),
		.BURSTWRAP_CONST_VALUE     (1),
		.ADAPTER_VERSION           ("13.1")
	) sc_hub_cmd_pipe_s0_burst_adapter (
		.clk                   (clk156_clk_clk),                                         //       cr0.clk
		.reset                 (sc_hub_cmd_pipe_reset_reset_bridge_in_reset_reset),      // cr0_reset.reset
		.sink0_valid           (cmd_mux_src_valid),                                      //     sink0.valid
		.sink0_data            (cmd_mux_src_data),                                       //          .data
		.sink0_channel         (cmd_mux_src_channel),                                    //          .channel
		.sink0_startofpacket   (cmd_mux_src_startofpacket),                              //          .startofpacket
		.sink0_endofpacket     (cmd_mux_src_endofpacket),                                //          .endofpacket
		.sink0_ready           (cmd_mux_src_ready),                                      //          .ready
		.source0_valid         (sc_hub_cmd_pipe_s0_burst_adapter_source0_valid),         //   source0.valid
		.source0_data          (sc_hub_cmd_pipe_s0_burst_adapter_source0_data),          //          .data
		.source0_channel       (sc_hub_cmd_pipe_s0_burst_adapter_source0_channel),       //          .channel
		.source0_startofpacket (sc_hub_cmd_pipe_s0_burst_adapter_source0_startofpacket), //          .startofpacket
		.source0_endofpacket   (sc_hub_cmd_pipe_s0_burst_adapter_source0_endofpacket),   //          .endofpacket
		.source0_ready         (sc_hub_cmd_pipe_s0_burst_adapter_source0_ready)          //          .ready
	);

	debug_sc_system_v3_lvdsctrl_cbb_mm_interconnect_2_cmd_demux cmd_demux (
		.clk                (clk156_clk_clk),                               //       clk.clk
		.reset              (sc_hub_hub_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.sink_ready         (router_src_ready),                             //      sink.ready
		.sink_channel       (router_src_channel),                           //          .channel
		.sink_data          (router_src_data),                              //          .data
		.sink_startofpacket (router_src_startofpacket),                     //          .startofpacket
		.sink_endofpacket   (router_src_endofpacket),                       //          .endofpacket
		.sink_valid         (router_src_valid),                             //          .valid
		.src0_ready         (cmd_demux_src0_ready),                         //      src0.ready
		.src0_valid         (cmd_demux_src0_valid),                         //          .valid
		.src0_data          (cmd_demux_src0_data),                          //          .data
		.src0_channel       (cmd_demux_src0_channel),                       //          .channel
		.src0_startofpacket (cmd_demux_src0_startofpacket),                 //          .startofpacket
		.src0_endofpacket   (cmd_demux_src0_endofpacket)                    //          .endofpacket
	);

	debug_sc_system_v3_lvdsctrl_cbb_mm_interconnect_2_cmd_mux cmd_mux (
		.clk                 (clk156_clk_clk),                                    //       clk.clk
		.reset               (sc_hub_cmd_pipe_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready           (cmd_mux_src_ready),                                 //       src.ready
		.src_valid           (cmd_mux_src_valid),                                 //          .valid
		.src_data            (cmd_mux_src_data),                                  //          .data
		.src_channel         (cmd_mux_src_channel),                               //          .channel
		.src_startofpacket   (cmd_mux_src_startofpacket),                         //          .startofpacket
		.src_endofpacket     (cmd_mux_src_endofpacket),                           //          .endofpacket
		.sink0_ready         (mux_pipeline_source0_ready),                        //     sink0.ready
		.sink0_valid         (mux_pipeline_source0_valid),                        //          .valid
		.sink0_channel       (mux_pipeline_source0_channel),                      //          .channel
		.sink0_data          (mux_pipeline_source0_data),                         //          .data
		.sink0_startofpacket (mux_pipeline_source0_startofpacket),                //          .startofpacket
		.sink0_endofpacket   (mux_pipeline_source0_endofpacket)                   //          .endofpacket
	);

	debug_sc_system_v3_lvdsctrl_cbb_mm_interconnect_2_cmd_demux rsp_demux (
		.clk                (clk156_clk_clk),                                    //       clk.clk
		.reset              (sc_hub_cmd_pipe_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.sink_ready         (router_001_src_ready),                              //      sink.ready
		.sink_channel       (router_001_src_channel),                            //          .channel
		.sink_data          (router_001_src_data),                               //          .data
		.sink_startofpacket (router_001_src_startofpacket),                      //          .startofpacket
		.sink_endofpacket   (router_001_src_endofpacket),                        //          .endofpacket
		.sink_valid         (router_001_src_valid),                              //          .valid
		.src0_ready         (rsp_demux_src0_ready),                              //      src0.ready
		.src0_valid         (rsp_demux_src0_valid),                              //          .valid
		.src0_data          (rsp_demux_src0_data),                               //          .data
		.src0_channel       (rsp_demux_src0_channel),                            //          .channel
		.src0_startofpacket (rsp_demux_src0_startofpacket),                      //          .startofpacket
		.src0_endofpacket   (rsp_demux_src0_endofpacket)                         //          .endofpacket
	);

	debug_sc_system_v3_lvdsctrl_cbb_mm_interconnect_2_rsp_mux rsp_mux (
		.clk                 (clk156_clk_clk),                               //       clk.clk
		.reset               (sc_hub_hub_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready           (rsp_mux_src_ready),                            //       src.ready
		.src_valid           (rsp_mux_src_valid),                            //          .valid
		.src_data            (rsp_mux_src_data),                             //          .data
		.src_channel         (rsp_mux_src_channel),                          //          .channel
		.src_startofpacket   (rsp_mux_src_startofpacket),                    //          .startofpacket
		.src_endofpacket     (rsp_mux_src_endofpacket),                      //          .endofpacket
		.sink0_ready         (mux_pipeline_001_source0_ready),               //     sink0.ready
		.sink0_valid         (mux_pipeline_001_source0_valid),               //          .valid
		.sink0_channel       (mux_pipeline_001_source0_channel),             //          .channel
		.sink0_data          (mux_pipeline_001_source0_data),                //          .data
		.sink0_startofpacket (mux_pipeline_001_source0_startofpacket),       //          .startofpacket
		.sink0_endofpacket   (mux_pipeline_001_source0_endofpacket)          //          .endofpacket
	);

	altera_avalon_st_pipeline_stage #(
		.SYMBOLS_PER_BEAT (1),
		.BITS_PER_SYMBOL  (98),
		.USE_PACKETS      (1),
		.USE_EMPTY        (0),
		.EMPTY_WIDTH      (0),
		.CHANNEL_WIDTH    (1),
		.PACKET_WIDTH     (2),
		.ERROR_WIDTH      (0),
		.PIPELINE_READY   (1)
	) agent_pipeline (
		.clk               (clk156_clk_clk),                                         //       cr0.clk
		.reset             (sc_hub_cmd_pipe_reset_reset_bridge_in_reset_reset),      // cr0_reset.reset
		.in_ready          (sc_hub_cmd_pipe_s0_burst_adapter_source0_ready),         //     sink0.ready
		.in_valid          (sc_hub_cmd_pipe_s0_burst_adapter_source0_valid),         //          .valid
		.in_startofpacket  (sc_hub_cmd_pipe_s0_burst_adapter_source0_startofpacket), //          .startofpacket
		.in_endofpacket    (sc_hub_cmd_pipe_s0_burst_adapter_source0_endofpacket),   //          .endofpacket
		.in_data           (sc_hub_cmd_pipe_s0_burst_adapter_source0_data),          //          .data
		.in_channel        (sc_hub_cmd_pipe_s0_burst_adapter_source0_channel),       //          .channel
		.out_ready         (agent_pipeline_source0_ready),                           //   source0.ready
		.out_valid         (agent_pipeline_source0_valid),                           //          .valid
		.out_startofpacket (agent_pipeline_source0_startofpacket),                   //          .startofpacket
		.out_endofpacket   (agent_pipeline_source0_endofpacket),                     //          .endofpacket
		.out_data          (agent_pipeline_source0_data),                            //          .data
		.out_channel       (agent_pipeline_source0_channel),                         //          .channel
		.in_empty          (1'b0),                                                   // (terminated)
		.out_empty         (),                                                       // (terminated)
		.out_error         (),                                                       // (terminated)
		.in_error          (1'b0)                                                    // (terminated)
	);

	altera_avalon_st_pipeline_stage #(
		.SYMBOLS_PER_BEAT (1),
		.BITS_PER_SYMBOL  (98),
		.USE_PACKETS      (1),
		.USE_EMPTY        (0),
		.EMPTY_WIDTH      (0),
		.CHANNEL_WIDTH    (0),
		.PACKET_WIDTH     (2),
		.ERROR_WIDTH      (0),
		.PIPELINE_READY   (1)
	) agent_pipeline_001 (
		.clk               (clk156_clk_clk),                                    //       cr0.clk
		.reset             (sc_hub_cmd_pipe_reset_reset_bridge_in_reset_reset), // cr0_reset.reset
		.in_ready          (sc_hub_cmd_pipe_s0_agent_rp_ready),                 //     sink0.ready
		.in_valid          (sc_hub_cmd_pipe_s0_agent_rp_valid),                 //          .valid
		.in_startofpacket  (sc_hub_cmd_pipe_s0_agent_rp_startofpacket),         //          .startofpacket
		.in_endofpacket    (sc_hub_cmd_pipe_s0_agent_rp_endofpacket),           //          .endofpacket
		.in_data           (sc_hub_cmd_pipe_s0_agent_rp_data),                  //          .data
		.out_ready         (agent_pipeline_001_source0_ready),                  //   source0.ready
		.out_valid         (agent_pipeline_001_source0_valid),                  //          .valid
		.out_startofpacket (agent_pipeline_001_source0_startofpacket),          //          .startofpacket
		.out_endofpacket   (agent_pipeline_001_source0_endofpacket),            //          .endofpacket
		.out_data          (agent_pipeline_001_source0_data),                   //          .data
		.in_empty          (1'b0),                                              // (terminated)
		.out_empty         (),                                                  // (terminated)
		.out_error         (),                                                  // (terminated)
		.in_error          (1'b0),                                              // (terminated)
		.out_channel       (),                                                  // (terminated)
		.in_channel        (1'b0)                                               // (terminated)
	);

	altera_avalon_st_pipeline_stage #(
		.SYMBOLS_PER_BEAT (1),
		.BITS_PER_SYMBOL  (98),
		.USE_PACKETS      (1),
		.USE_EMPTY        (0),
		.EMPTY_WIDTH      (0),
		.CHANNEL_WIDTH    (1),
		.PACKET_WIDTH     (2),
		.ERROR_WIDTH      (0),
		.PIPELINE_READY   (1)
	) mux_pipeline (
		.clk               (clk156_clk_clk),                                    //       cr0.clk
		.reset             (sc_hub_cmd_pipe_reset_reset_bridge_in_reset_reset), // cr0_reset.reset
		.in_ready          (cmd_demux_src0_ready),                              //     sink0.ready
		.in_valid          (cmd_demux_src0_valid),                              //          .valid
		.in_startofpacket  (cmd_demux_src0_startofpacket),                      //          .startofpacket
		.in_endofpacket    (cmd_demux_src0_endofpacket),                        //          .endofpacket
		.in_data           (cmd_demux_src0_data),                               //          .data
		.in_channel        (cmd_demux_src0_channel),                            //          .channel
		.out_ready         (mux_pipeline_source0_ready),                        //   source0.ready
		.out_valid         (mux_pipeline_source0_valid),                        //          .valid
		.out_startofpacket (mux_pipeline_source0_startofpacket),                //          .startofpacket
		.out_endofpacket   (mux_pipeline_source0_endofpacket),                  //          .endofpacket
		.out_data          (mux_pipeline_source0_data),                         //          .data
		.out_channel       (mux_pipeline_source0_channel),                      //          .channel
		.in_empty          (1'b0),                                              // (terminated)
		.out_empty         (),                                                  // (terminated)
		.out_error         (),                                                  // (terminated)
		.in_error          (1'b0)                                               // (terminated)
	);

	altera_avalon_st_pipeline_stage #(
		.SYMBOLS_PER_BEAT (1),
		.BITS_PER_SYMBOL  (98),
		.USE_PACKETS      (1),
		.USE_EMPTY        (0),
		.EMPTY_WIDTH      (0),
		.CHANNEL_WIDTH    (1),
		.PACKET_WIDTH     (2),
		.ERROR_WIDTH      (0),
		.PIPELINE_READY   (1)
	) mux_pipeline_001 (
		.clk               (clk156_clk_clk),                               //       cr0.clk
		.reset             (sc_hub_hub_reset_reset_bridge_in_reset_reset), // cr0_reset.reset
		.in_ready          (rsp_demux_src0_ready),                         //     sink0.ready
		.in_valid          (rsp_demux_src0_valid),                         //          .valid
		.in_startofpacket  (rsp_demux_src0_startofpacket),                 //          .startofpacket
		.in_endofpacket    (rsp_demux_src0_endofpacket),                   //          .endofpacket
		.in_data           (rsp_demux_src0_data),                          //          .data
		.in_channel        (rsp_demux_src0_channel),                       //          .channel
		.out_ready         (mux_pipeline_001_source0_ready),               //   source0.ready
		.out_valid         (mux_pipeline_001_source0_valid),               //          .valid
		.out_startofpacket (mux_pipeline_001_source0_startofpacket),       //          .startofpacket
		.out_endofpacket   (mux_pipeline_001_source0_endofpacket),         //          .endofpacket
		.out_data          (mux_pipeline_001_source0_data),                //          .data
		.out_channel       (mux_pipeline_001_source0_channel),             //          .channel
		.in_empty          (1'b0),                                         // (terminated)
		.out_empty         (),                                             // (terminated)
		.out_error         (),                                             // (terminated)
		.in_error          (1'b0)                                          // (terminated)
	);

	debug_sc_system_v3_lvdsctrl_cbb_mm_interconnect_0_avalon_st_adapter #(
		.inBitsPerSymbol (34),
		.inUsePackets    (0),
		.inDataWidth     (34),
		.inChannelWidth  (0),
		.inErrorWidth    (0),
		.inUseEmptyPort  (0),
		.inUseValid      (1),
		.inUseReady      (1),
		.inReadyLatency  (0),
		.outDataWidth    (34),
		.outChannelWidth (0),
		.outErrorWidth   (1),
		.outUseEmptyPort (0),
		.outUseValid     (1),
		.outUseReady     (1),
		.outReadyLatency (0)
	) avalon_st_adapter (
		.in_clk_0_clk   (clk156_clk_clk),                                    // in_clk_0.clk
		.in_rst_0_reset (sc_hub_cmd_pipe_reset_reset_bridge_in_reset_reset), // in_rst_0.reset
		.in_0_data      (sc_hub_cmd_pipe_s0_agent_rdata_fifo_src_data),      //     in_0.data
		.in_0_valid     (sc_hub_cmd_pipe_s0_agent_rdata_fifo_src_valid),     //         .valid
		.in_0_ready     (sc_hub_cmd_pipe_s0_agent_rdata_fifo_src_ready),     //         .ready
		.out_0_data     (avalon_st_adapter_out_0_data),                      //    out_0.data
		.out_0_valid    (avalon_st_adapter_out_0_valid),                     //         .valid
		.out_0_ready    (avalon_st_adapter_out_0_ready),                     //         .ready
		.out_0_error    (avalon_st_adapter_out_0_error)                      //         .error
	);

endmodule
