// File name: ring_buffer_cam_sector_lock_formal_top.sv
// Purpose  : Formal wrapper that exposes rbCAM sector-lock assertions.

module ring_buffer_cam_sector_lock_formal_top (
  output logic [31:0] avs_csr_readdata,
  input  logic        avs_csr_read,
  input  logic [4:0]  avs_csr_address,
  output logic        avs_csr_waitrequest,
  input  logic        avs_csr_write,
  input  logic [31:0] avs_csr_writedata,
  input  logic [3:0]  asi_hit_type1_channel,
  input  logic        asi_hit_type1_startofpacket,
  input  logic        asi_hit_type1_endofpacket,
  input  logic        asi_hit_type1_empty,
  input  logic [38:0] asi_hit_type1_data,
  input  logic        asi_hit_type1_valid,
  output logic        asi_hit_type1_ready,
  input  logic [0:0]  asi_hit_type1_error,
  input  logic [63:0] asi_hit_type1_metadata,
  input  logic        asi_hit_type1_metadata_valid,
  output logic [3:0]  aso_hit_type2_channel,
  output logic        aso_hit_type2_startofpacket,
  output logic        aso_hit_type2_endofpacket,
  output logic [35:0] aso_hit_type2_data,
  output logic        aso_hit_type2_valid,
  input  logic        aso_hit_type2_ready,
  output logic [0:0]  aso_hit_type2_error,
  output logic [63:0] aso_hit_type2_metadata,
  output logic        aso_hit_type2_metadata_valid,
  input  logic        i_clk,
  input  logic        i_rst,
  input  logic [8:0]  asi_ctrl_data,
  input  logic        asi_ctrl_valid,
  output logic        asi_ctrl_ready,
  output logic [15:0] aso_filllevel_data,
  output logic        aso_filllevel_valid,
  output logic [31:0] coe_debug_fill_level,
  output logic [31:0] coe_debug_fifo_level,
  output logic [31:0] coe_debug_queue_state
);

  // Sector-lock safety does not depend on the debug metadata payload. Tie the
  // sideband off here so the proof state space stays focused on arbiter timing.
  ring_buffer_cam dut (
    .avs_csr_readdata            (avs_csr_readdata),
    .avs_csr_read                (avs_csr_read),
    .avs_csr_address             (avs_csr_address),
    .avs_csr_waitrequest         (avs_csr_waitrequest),
    .avs_csr_write               (avs_csr_write),
    .avs_csr_writedata           (avs_csr_writedata),
    .asi_hit_type1_channel       (asi_hit_type1_channel),
    .asi_hit_type1_startofpacket (asi_hit_type1_startofpacket),
    .asi_hit_type1_endofpacket   (asi_hit_type1_endofpacket),
    .asi_hit_type1_empty         (asi_hit_type1_empty),
    .asi_hit_type1_data          (asi_hit_type1_data),
    .asi_hit_type1_valid         (asi_hit_type1_valid),
    .asi_hit_type1_ready         (asi_hit_type1_ready),
    .asi_hit_type1_error         (asi_hit_type1_error),
    .asi_hit_type1_metadata      (64'd0),
    .asi_hit_type1_metadata_valid(1'b0),
    .aso_hit_type2_channel       (aso_hit_type2_channel),
    .aso_hit_type2_startofpacket (aso_hit_type2_startofpacket),
    .aso_hit_type2_endofpacket   (aso_hit_type2_endofpacket),
    .aso_hit_type2_data          (aso_hit_type2_data),
    .aso_hit_type2_valid         (aso_hit_type2_valid),
    .aso_hit_type2_ready         (aso_hit_type2_ready),
    .aso_hit_type2_error         (aso_hit_type2_error),
    .aso_hit_type2_metadata      (aso_hit_type2_metadata),
    .aso_hit_type2_metadata_valid(aso_hit_type2_metadata_valid),
    .i_clk                       (i_clk),
    .i_rst                       (i_rst),
    .asi_ctrl_data               (asi_ctrl_data),
    .asi_ctrl_valid              (asi_ctrl_valid),
    .asi_ctrl_ready              (asi_ctrl_ready),
    .aso_filllevel_data          (aso_filllevel_data),
    .aso_filllevel_valid         (aso_filllevel_valid),
    .coe_debug_fill_level        (coe_debug_fill_level),
    .coe_debug_fifo_level        (coe_debug_fifo_level),
    .coe_debug_queue_state       (coe_debug_queue_state)
  );

  ring_buffer_cam_sector_lock_sva sector_lock_sva (
    .i_clk                    (i_clk),
    .i_rst                    (i_rst),
    .pop_engine_state         (dut.v2_core.pop_engine_state),
    .push_write_grant         (dut.v2_core.push_write_grant),
    .push_erase_grant         (dut.v2_core.push_erase_grant),
    .pop_erase_grant          (dut.v2_core.pop_erase_grant),
    .pop_flush_grant          (dut.v2_core.pop_flush_grant),
    .push_write_sector_locked (dut.v2_core.push_write_sector_locked),
    .push_erase_sector_locked (dut.v2_core.push_erase_sector_locked),
    .pop_flush_req            (dut.v2_core.pop_flush_req),
    .push_erase_req           (dut.v2_core.push_erase_req)
  );

endmodule
