# TCL File Generated by Component Editor 18.1
# Mon Mar 04 13:53:05 CET 2024
# DO NOT MODIFY


# 
# dbg_counter_fab "(Debug) Counter Interconnect" v1.0.1
# Yifeng Wang 2024.03.04.13:53:05
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module dbg_counter_fab
# 
set_module_property DESCRIPTION ""
set_module_property NAME dbg_counter_fab
set_module_property VERSION 1.0.1
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Mu3e Data Plane/Debug"
set_module_property AUTHOR "Yifeng Wang"
set_module_property DISPLAY_NAME "(Debug) Counter Interconnect"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL dbg_counter_fab
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file dbg_counter_fab.vhd VHDL PATH dbg_counter_fab.vhd TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point to_source
# 
add_interface to_source conduit end
set_interface_property to_source associatedClock clock_sink
set_interface_property to_source associatedReset ""
set_interface_property to_source ENABLED true
set_interface_property to_source EXPORT_OF ""
set_interface_property to_source PORT_NAME_MAP ""
set_interface_property to_source CMSIS_SVD_VARIABLES ""
set_interface_property to_source SVD_ADDRESS_GROUP ""

add_interface_port to_source source source Input 2


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink i_clk clk Input 1


# 
# connection point clock_sink_1
# 
add_interface clock_sink_1 clock end
set_interface_property clock_sink_1 clockRate 0
set_interface_property clock_sink_1 ENABLED true
set_interface_property clock_sink_1 EXPORT_OF ""
set_interface_property clock_sink_1 PORT_NAME_MAP ""
set_interface_property clock_sink_1 CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink_1 SVD_ADDRESS_GROUP ""

add_interface_port clock_sink_1 i_clk1 clk Input 1


# 
# connection point to_counter_control_port_b
# 
add_interface to_counter_control_port_b conduit end
set_interface_property to_counter_control_port_b associatedClock clock_sink_1
set_interface_property to_counter_control_port_b associatedReset ""
set_interface_property to_counter_control_port_b ENABLED true
set_interface_property to_counter_control_port_b EXPORT_OF ""
set_interface_property to_counter_control_port_b PORT_NAME_MAP ""
set_interface_property to_counter_control_port_b CMSIS_SVD_VARIABLES ""
set_interface_property to_counter_control_port_b SVD_ADDRESS_GROUP ""

add_interface_port to_counter_control_port_b sclr1 sclr Output 1


# 
# connection point to_counter_control_port_a
# 
add_interface to_counter_control_port_a conduit end
set_interface_property to_counter_control_port_a associatedClock clock_sink_1
set_interface_property to_counter_control_port_a associatedReset ""
set_interface_property to_counter_control_port_a ENABLED true
set_interface_property to_counter_control_port_a EXPORT_OF ""
set_interface_property to_counter_control_port_a PORT_NAME_MAP ""
set_interface_property to_counter_control_port_a CMSIS_SVD_VARIABLES ""
set_interface_property to_counter_control_port_a SVD_ADDRESS_GROUP ""

add_interface_port to_counter_control_port_a enable enable Output 1
add_interface_port to_counter_control_port_a sclr sclr Output 1
