-- feb_system_v3_pipe_avalon_st_adapter_001.vhd

-- This file was auto-generated from altera_avalon_st_adapter_hw.tcl.  If you edit it your changes
-- will probably be lost.
-- 
-- Generated using ACDS version 18.1 625

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity feb_system_v3_pipe_avalon_st_adapter_001 is
	generic (
		inBitsPerSymbol : integer := 9;
		inUsePackets    : integer := 0;
		inDataWidth     : integer := 9;
		inChannelWidth  : integer := 4;
		inErrorWidth    : integer := 3;
		inUseEmptyPort  : integer := 0;
		inUseValid      : integer := 0;
		inUseReady      : integer := 0;
		inReadyLatency  : integer := 0;
		outDataWidth    : integer := 9;
		outChannelWidth : integer := 0;
		outErrorWidth   : integer := 3;
		outUseEmptyPort : integer := 0;
		outUseValid     : integer := 0;
		outUseReady     : integer := 0;
		outReadyLatency : integer := 0
	);
	port (
		in_clk_0_clk   : in  std_logic                    := '0';             -- in_clk_0.clk
		in_rst_0_reset : in  std_logic                    := '0';             -- in_rst_0.reset
		in_0_data      : in  std_logic_vector(8 downto 0) := (others => '0'); --     in_0.data
		in_0_error     : in  std_logic_vector(2 downto 0) := (others => '0'); --         .error
		in_0_channel   : in  std_logic_vector(3 downto 0) := (others => '0'); --         .channel
		out_0_data     : out std_logic_vector(8 downto 0);                    --    out_0.data
		out_0_error    : out std_logic_vector(2 downto 0)                     --         .error
	);
end entity feb_system_v3_pipe_avalon_st_adapter_001;

architecture rtl of feb_system_v3_pipe_avalon_st_adapter_001 is
	component feb_system_v3_pipe_avalon_st_adapter_001_channel_adapter_0 is
		port (
			clk        : in  std_logic                    := 'X';             -- clk
			reset_n    : in  std_logic                    := 'X';             -- reset_n
			in_data    : in  std_logic_vector(8 downto 0) := (others => 'X'); -- data
			in_valid   : in  std_logic                    := 'X';             -- valid
			in_error   : in  std_logic_vector(2 downto 0) := (others => 'X'); -- error
			in_channel : in  std_logic_vector(3 downto 0) := (others => 'X'); -- channel
			out_data   : out std_logic_vector(8 downto 0);                    -- data
			out_valid  : out std_logic;                                       -- valid
			out_error  : out std_logic_vector(2 downto 0)                     -- error
		);
	end component feb_system_v3_pipe_avalon_st_adapter_001_channel_adapter_0;

	component feb_system_v3_pipe_avalon_st_adapter_001_timing_adapter_0 is
		port (
			clk         : in  std_logic                    := 'X';             -- clk
			reset_n     : in  std_logic                    := 'X';             -- reset_n
			in_data     : in  std_logic_vector(8 downto 0) := (others => 'X'); -- data
			in_error    : in  std_logic_vector(2 downto 0) := (others => 'X'); -- error
			in_channel  : in  std_logic_vector(3 downto 0) := (others => 'X'); -- channel
			out_data    : out std_logic_vector(8 downto 0);                    -- data
			out_valid   : out std_logic;                                       -- valid
			out_error   : out std_logic_vector(2 downto 0);                    -- error
			out_channel : out std_logic_vector(3 downto 0)                     -- channel
		);
	end component feb_system_v3_pipe_avalon_st_adapter_001_timing_adapter_0;

	component feb_system_v3_pipe_avalon_st_adapter_001_timing_adapter_1 is
		port (
			clk       : in  std_logic                    := 'X';             -- clk
			reset_n   : in  std_logic                    := 'X';             -- reset_n
			in_data   : in  std_logic_vector(8 downto 0) := (others => 'X'); -- data
			in_valid  : in  std_logic                    := 'X';             -- valid
			in_error  : in  std_logic_vector(2 downto 0) := (others => 'X'); -- error
			out_data  : out std_logic_vector(8 downto 0);                    -- data
			out_error : out std_logic_vector(2 downto 0)                     -- error
		);
	end component feb_system_v3_pipe_avalon_st_adapter_001_timing_adapter_1;

	signal timing_adapter_0_out_valid   : std_logic;                    -- timing_adapter_0:out_valid -> channel_adapter_0:in_valid
	signal timing_adapter_0_out_data    : std_logic_vector(8 downto 0); -- timing_adapter_0:out_data -> channel_adapter_0:in_data
	signal timing_adapter_0_out_channel : std_logic_vector(3 downto 0); -- timing_adapter_0:out_channel -> channel_adapter_0:in_channel
	signal timing_adapter_0_out_error   : std_logic_vector(2 downto 0); -- timing_adapter_0:out_error -> channel_adapter_0:in_error
	signal channel_adapter_0_out_valid  : std_logic;                    -- channel_adapter_0:out_valid -> timing_adapter_1:in_valid
	signal channel_adapter_0_out_data   : std_logic_vector(8 downto 0); -- channel_adapter_0:out_data -> timing_adapter_1:in_data
	signal channel_adapter_0_out_error  : std_logic_vector(2 downto 0); -- channel_adapter_0:out_error -> timing_adapter_1:in_error
	signal in_rst_0_reset_ports_inv     : std_logic;                    -- in_rst_0_reset:inv -> [channel_adapter_0:reset_n, timing_adapter_0:reset_n, timing_adapter_1:reset_n]

begin

	inbitspersymbol_check : if inBitsPerSymbol /= 9 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	inusepackets_check : if inUsePackets /= 0 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	indatawidth_check : if inDataWidth /= 9 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	inchannelwidth_check : if inChannelWidth /= 4 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	inerrorwidth_check : if inErrorWidth /= 3 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	inuseemptyport_check : if inUseEmptyPort /= 0 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	inusevalid_check : if inUseValid /= 0 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	inuseready_check : if inUseReady /= 0 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	inreadylatency_check : if inReadyLatency /= 0 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	outdatawidth_check : if outDataWidth /= 9 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	outchannelwidth_check : if outChannelWidth /= 0 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	outerrorwidth_check : if outErrorWidth /= 3 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	outuseemptyport_check : if outUseEmptyPort /= 0 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	outusevalid_check : if outUseValid /= 0 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	outuseready_check : if outUseReady /= 0 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	outreadylatency_check : if outReadyLatency /= 0 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	channel_adapter_0 : component feb_system_v3_pipe_avalon_st_adapter_001_channel_adapter_0
		port map (
			clk        => in_clk_0_clk,                 --   clk.clk
			reset_n    => in_rst_0_reset_ports_inv,     -- reset.reset_n
			in_data    => timing_adapter_0_out_data,    --    in.data
			in_valid   => timing_adapter_0_out_valid,   --      .valid
			in_error   => timing_adapter_0_out_error,   --      .error
			in_channel => timing_adapter_0_out_channel, --      .channel
			out_data   => channel_adapter_0_out_data,   --   out.data
			out_valid  => channel_adapter_0_out_valid,  --      .valid
			out_error  => channel_adapter_0_out_error   --      .error
		);

	timing_adapter_0 : component feb_system_v3_pipe_avalon_st_adapter_001_timing_adapter_0
		port map (
			clk         => in_clk_0_clk,                 --   clk.clk
			reset_n     => in_rst_0_reset_ports_inv,     -- reset.reset_n
			in_data     => in_0_data,                    --    in.data
			in_error    => in_0_error,                   --      .error
			in_channel  => in_0_channel,                 --      .channel
			out_data    => timing_adapter_0_out_data,    --   out.data
			out_valid   => timing_adapter_0_out_valid,   --      .valid
			out_error   => timing_adapter_0_out_error,   --      .error
			out_channel => timing_adapter_0_out_channel  --      .channel
		);

	timing_adapter_1 : component feb_system_v3_pipe_avalon_st_adapter_001_timing_adapter_1
		port map (
			clk       => in_clk_0_clk,                --   clk.clk
			reset_n   => in_rst_0_reset_ports_inv,    -- reset.reset_n
			in_data   => channel_adapter_0_out_data,  --    in.data
			in_valid  => channel_adapter_0_out_valid, --      .valid
			in_error  => channel_adapter_0_out_error, --      .error
			out_data  => out_0_data,                  --   out.data
			out_error => out_0_error                  --      .error
		);

	in_rst_0_reset_ports_inv <= not in_rst_0_reset;

end architecture rtl; -- of feb_system_v3_pipe_avalon_st_adapter_001
