# Module name strings
HWTCL_MODULE_DISPLAY_NAME = LVDS SERDES Intel FPGA IP
HWTCL_MODULE_DESCRIPTION = LVDS SERDES Intel FPGA IP

# GUI tab names
TAB_GENERAL_NAME = General Settings
TAB_CLOCKING_NAME =  PLL & Clocking Settings 
TAB_RX_SETTINGS_NAME = Receiver Settings
TAB_TX_SETTINGS_NAME = Transmitter Settings

TAB_TOP_LEVEL_SETTINGS_NAME = Top Level Settings
TAB_PLL_SETTINGS_NAME = PLL Settings
TAB_CLOCK_RESOURCES_NAME = Clock Resource Summary 
TAB_DPA_SETTINGS_NAME = DPA Settings
TAB_BITSLIP_SETTINGS_NAME = Bitslip Settings
TAB_NON_DPA_SETTINGS_NAME = Non-DPA Settings 

# GUI group names
#GRP_PHY_IF_NAME = Interface
#GRP_PHY_CLKS_NAME = Clocks
#GRP_PHY_IO_NAME = I/O

###############################################################################
# Common Non-Derived Parameters
###############################################################################

PARAM_MODE_NAME = Functional mode
PARAM_MODE_DESC = Specifies the top level configuration of the interface.

PARAM_USE_EXTERNAL_PLL_NAME = Use external PLL
PARAM_USE_EXTERNAL_PLL_DESC = When enabled, the LVDS IP does not instantiate a PLL locally. Instead, a series of clock connections are elaborated with the prefix "ext" that should be connected to an externally generated PLL.

PARAM_USE_CLOCK_PIN_NAME = Use clock-pin drive
PARAM_USE_CLOCK_PIN_DESC = When enabled the IP bypasses the PLL, and interface is driven with a clock pin. This feature is not supported in the current version of the Quartus Prime software.

PARAM_NUM_CHANNELS_NAME = Number of channels
PARAM_NUM_CHANNELS_DESC = Specifies the number of serial channels in the LVDS interface.

PARAM_J_FACTOR_NAME = SERDES factor
PARAM_J_FACTOR_DESC = Specifies the serialization rate (TX) or deserialization rate (RX) for the LVDS interface.

PARAM_DATA_RATE_NAME = Data rate
PARAM_DATA_RATE_DESC = Specifies the data rate in Mbps of a single serial channel.

PARAM_INCLOCK_FREQUENCY_NAME = Desired inclock frequency
PARAM_INCLOCK_FREQUENCY_DESC = Specifies the ideal frequency of the interface's reference clock. This may differ from the actual frequency the interface expects.

PARAM_ACTUAL_INCLOCK_FREQUENCY_NAME = Actual inclock frequency
PARAM_ACTUAL_INCLOCK_FREQUENCY_DESC = Specifies the inclock frequency that will be used to drive the desired interface.  

PARAM_ENABLE_MIGRATABLE_PORT_MAPPINGS_NAME = Use backwards-compatible port names
PARAM_ENABLE_MIGRATABLE_PORT_MAPPINGS_DESC = When enabled, the LVDS IP uses legacy top-level names compatible with ALTLVDS_TX and ALTLVDS_RX.

###########################################################################
## RX Non-Derived Parameters
###########################################################################

PARAM_RX_INCLOCK_PHASE_SHIFT_NAME = Desired receiver inclock phase shift (degrees)
PARAM_RX_INCLOCK_PHASE_SHIFT_DESC = Specifies the ideal phase delay of the inclock with respect to transitions in the incoming serial data in degrees of the LVDS fast clock. For example, specifying 180 degrees implies the inclock is center aligned with the incoming data. 

PARAM_RX_INCLOCK_PHASE_SHIFT_ACTUAL_NAME = Actual receiver inclock phase shift (degrees)
PARAM_RX_INCLOCK_PHASE_SHIFT_ACTUAL_DESC = Specifies the phase shift of the inclock that will be accounted for by the LVDS interface.

PARAM_RX_RCCS_VAL_NAME = RCCS (ps)
PARAM_RX_RCCS_VAL_DESC = Specifies the Receiver Channel-to-Channel Skew (RCCS).  

PARAM_RX_USE_BITSLIP_NAME = Enable bitslip mode
PARAM_RX_USE_BITSLIP_DESC = When enabled, adds a bitslip block to the receiver's data paths and exposes the rx_bitslip_ctrl port (one input per channel). Every assertion of rx_bitslip_ctrl adds one bit of serial latency to that channel's data path. 

PARAM_RX_BITSLIP_USE_RESET_NAME = Enable rx_bitslip_reset port  
PARAM_RX_BITSLIP_USE_RESET_DESC = When enabled, exposes the rx_bitslip_reset port (one input per channel) which is used to reset the bitslip. 

PARAM_RX_BITSLIP_ASSERT_MAX_NAME = Enable rx_bitslip_max port
PARAM_RX_BITSLIP_ASSERT_MAX_DESC = When enabled, exposes the rx_bitslip_max port (one output per channel). When asserted, the next rising edge of rx_bitslip_ctrl will reset the bitslip's latency to zero. 

PARAM_RX_BITSLIP_ROLLOVER_NAME = Bitslip rollover value
PARAM_RX_BITSLIP_ROLLOVER_DESC = Sets the maximum latency that can be injected using bitslip. When it reaches that value, it rolls over and the rx_bitslip_max signal is asserted.

PARAM_RX_DPA_USE_RESET_NAME = Enable rx_dpa_reset port 
PARAM_RX_DPA_USE_RESET_DESC = When enabled, exposes the rx_dpa_reset port which can be used to reset each channel's DPA logic independently. Formerly known as rx_reset. 

PARAM_RX_DPA_LOSE_LOCK_ON_ONE_CHANGE_NAME = Enable DPA loss of lock on one change
PARAM_RX_DPA_LOSE_LOCK_ON_ONE_CHANGE_DESC = When enabled, DPA logic will deassert lock whenever it chooses a new ideal phase. Otherwise, it will wait for two sucessive changes.

PARAM_RX_DPA_ALIGN_TO_RISING_EDGE_ONLY_NAME = Enable DPA alignment only to rising edges of data
PARAM_RX_DPA_ALIGN_TO_RISING_EDGE_ONLY_DESC = When enabled, DPA logic will only count rising edges on the incoming serial data. Otherwise, it counts both rising and falling edges.

PARAM_RX_DPA_LOCKED_USED_NAME = Enable rx_dpa_locked port
PARAM_RX_DPA_LOCKED_USED_DESC = When enabled, exposes the rx_dpa_locked port (one output per channel). The DPA logic asserts rx_dpa_locked when it has settled on an ideal phase for that given channel.

PARAM_RX_CDR_SIMULATION_PPM_DRIFT_NAME = (Simulation only) Specify PPM drift on the recovered clock(s).
PARAM_RX_CDR_SIMULATION_PPM_DRIFT_DESC = Specifies the amount of phase drift the simulation model should add to the recovered rx_divfwdclks. This feature is not supported in the current version of the Quartus Prime software.

PARAM_RX_FIFO_USE_RESET_NAME = Enable rx_fifo_reset port
PARAM_RX_FIFO_USE_RESET_DESC = When enabled, exposes the rx_fifo_reset port which can be used to reset the FIFO in DPA-FIFO mode.

PARAM_RX_DPA_USE_HOLD_NAME = Enable rx_dpa_hold port
PARAM_RX_DPA_USE_HOLD_DESC = When enabled, exposes the rx_dpa_hold input port (one input per channel). When set high, the DPA logic in the corresponding channel will not switch sampling phases. (Formerly known as rx_dpll_hold) 

PARAM_ENABLE_DIV_RECONFIG_NAME = Enable dynamic reconfig interface for DPA divider
PARAM_ENABLE_DIV_RECONFIG_DESC = When enabled, exposes the user_dprio_* interface which can be used to dynamically reconfig the DPA or VCO clock dividers.

###########################################################################
## TX Non-Derived Parameters
###########################################################################

PARAM_TX_REGISTER_CLOCK_NAME = TX core registers clock
PARAM_TX_REGISTER_CLOCK_DESC = Specifies the source clock for the TX core registers. If the inclock is selected, its frequency must be equal to the data rate divided by the serialization factor.

PARAM_TX_USE_OUTCLOCK_NAME = Enable tx_outclock port 
PARAM_TX_USE_OUTCLOCK_DESC = When enabled, exposes the tx_outclock port, and generates an output clock of specified phase and frequency that is source-synchronous to the outgoing serial data. 

PARAM_TX_OUTCLOCK_PHASE_SHIFT_NAME = Desired tx_outclock phase shift (degrees)
PARAM_TX_OUTCLOCK_PHASE_SHIFT_DESC = Specifies the ideal phase relationship between the outclock and outgoing serial data in degrees of the LVDS fast clock. 

PARAM_TX_OUTCLOCK_PHASE_SHIFT_ACTUAL_NAME = Actual tx_outclock phase shift (degrees)
PARAM_TX_OUTCLOCK_PHASE_SHIFT_ACTUAL_DESC = Specifies the applied phase shift of the transmitter outclock.

PARAM_TX_OUTCLOCK_DIVISION_NAME = Tx_outclock division factor
PARAM_TX_OUTCLOCK_DIVISION_DESC = Specifies the ratio of the fast clock frequency to the outclock frequency. 

PARAM_TX_EXPORT_CORECLOCK_NAME = Enable tx_coreclock port 
PARAM_TX_EXPORT_CORECLOCK_DESC = When enabled, exposes the tx_coreclock port which should be used to drive core logic feeding the transmitter.

###########################################################################
## PLL Non-Derived Parameters
###########################################################################

PARAM_PLL_CORECLOCK_RESOURCE_NAME = Core clock resource type
PARAM_PLL_CORECLOCK_RESOURCE_DESC = Specifies which clock network the LVDS IP should export the internally generated coreclock onto. For timing closure at higher coreclock frequencies, it is recommended to use Periphery Clock. The Global Clock, however, is able to reach more core logic.

PARAM_PLL_SPEED_GRADE_NAME = FPGA/PLL speed grade
PARAM_PLL_SPEED_GRADE_DESC = Specifies the speed grade of the PLLs on the target part.

PARAM_PLL_EXPORT_LOCK_NAME = Enable pll_locked port
PARAM_PLL_EXPORT_LOCK_DESC = When enabled, exposes the pll_locked port, which is asserted when the internal PLL locks onto the reference clock. (Formerly known as rx_locked, tx_locked) 

PARAM_PLL_USE_RESET_NAME = Enable pll_areset port
PARAM_PLL_USE_RESET_DESC = When enabled, exposes the pll_areset port, which can be used to reset the entire LVDS interface.

###########################################################################
## Derived Parameters
###########################################################################

PARAM_GUI_CLOCK_PARAM_NAMES_NAME = Clock Parameters
PARAM_GUI_CLOCK_PARAM_NAMES_DESC = Specifies the characteristics of all the clocks required by the currently specified interface. 

PARAM_GUI_CLOCK_PARAM_VALUES_NAME = Clock Parameter Values
PARAM_GUI_CLOCK_PARAM_VALUES_DESC = Specifies the values of each of clock characteristics required by the currently specified interface. 


###########################################################################
## Additional GUI text - GENERAL TAB 
###########################################################################

TEXT_INCLOCK_FREQ_INFO1 = PLL construction imposes certain constraints on allowable inclock frequencies for a given LVDS channel specification. 
TEXT_INCLOCK_FREQ_INFO2 = The Actual Inclock Frequency parameter will specify the closest frequency to the "Ideal Inclock Frequency" that can be used
TEXT_INCLOCK_FREQ_INFO3 = clock this ALTERA_LVDS inteface. For proper interface operation, the Actual and not the Ideal frequency inclock must be provided. 



